import type {EvidenceFieldRef,EvidenceItem,EvidenceProvider,LayeredKnowledgeContext,RawChannelInput} from './types';
import type {CanonicalEvidenceDocument} from './canonicalEvidencePlane';

export const EVIDENCE_DOCUMENT_SCHEMA_VERSION='evidence-document-v1';
export const EVIDENCE_ASSERTION_SCHEMA_VERSION='classification-assertion-v1';
export const EVIDENCE_COVERAGE_SCHEMA_VERSION='evidence-coverage-v1';
export type EvidenceDocumentType='CHANNEL_TITLE'|'CHANNEL_ABOUT'|'VIDEO_TITLE'|'VIDEO_DESCRIPTION'|'PLAYLIST_TITLE'|'PLAYLIST_DESCRIPTION'|'TRANSCRIPT_EXCERPT'|'EXTERNAL_LINK'|'COMMUNITY_METADATA'|'VISUAL_OBSERVATION'|'SEARCH_MATCH_CONTEXT'|'PINNED_COMMENT'|'LOCATION'|'ACTIVITY_METADATA';
export interface EvidenceDocumentObservation {documentKey:string;canonicalDocumentId:string;subjectEntityId:string;channelId:string;documentType:EvidenceDocumentType;provider:string;providerNativeId?:string;canonicalLocator:Record<string,unknown>;sourceFamilyId:string;sourceEntityId?:string;language?:string;script?:string;contentType?:string;publishedAt?:string;observedAt:string;normalizedText:string;textChecksum:string;rawPayloadChecksum:string;provenance:Record<string,unknown>;schemaVersion:string}
export interface EvidenceAssertionObservation {assertionKey:string;subjectEntityId:string;channelId:string;assertionType:string;hypothesis:string;polarity:'POSITIVE'|'NEGATIVE'|'ABSTAIN';confidenceBasisPoints:number;reliability:EvidenceItem['reliability'];documentKeys:string[];sourceFamilyIds:string[];modelOrRuleVersion:string;provider:string;languageCapability:Record<string,unknown>;reasonCodes:string[];derivation:Record<string,unknown>;observedAt:string}
export interface EvidenceCoverageSnapshot {snapshotKey:string;channelId:string;subjectEntityId:string;classificationDiagnosticId?:string;requestedSamplingStrategy:Record<string,unknown>;observedDocumentCounts:Record<string,number>;temporalCoverage:Record<string,unknown>;languageCoverage:Record<string,unknown>;independentFamilyCount:number;providerAvailability:Array<Record<string,unknown>>;acquisitionFailures:Array<Record<string,unknown>>;oldestDocumentAt?:string;latestDocumentAt?:string;expectedDocumentCount:number;observedDocumentCount:number;completenessDisposition:'MISSING'|'INSUFFICIENT'|'SUFFICIENT';reasonCodes:string[];inputChecksum:string;policyVersion:string;schemaVersion:string;observedAt:string}
export interface EvidenceProviderV2 {name:string;acquireDocuments(input:RawChannelInput,context:LayeredKnowledgeContext):Promise<EvidenceDocumentObservation[]>;deriveAssertions(documents:EvidenceDocumentObservation[],input:RawChannelInput,context:LayeredKnowledgeContext):Promise<EvidenceAssertionObservation[]>}
export interface ProviderV2Adapter {provider:EvidenceProvider;documents:CanonicalEvidenceDocument[];fieldRefs:EvidenceFieldRef[]}
