export const CREATOR_FOCUS_HYPOTHESES=['ACTIVE_TRADING_CREATOR','TRADING_EDUCATOR','INVESTING_EDUCATOR','FINANCIAL_NEWS','PERSONAL_FINANCE','MARKET_INSTITUTION','TRADING_ADJACENT','MIXED_FINANCE','ONE_OFF_TRADING_DOCUMENT','HYPE_OR_PROMOTION','UNRELATED_CREATOR','INSUFFICIENT_COVERAGE','UNSUPPORTED_LANGUAGE','AMBIGUOUS'] as const;
export type CreatorFocusHypothesis=typeof CREATOR_FOCUS_HYPOTHESES[number];
export type CreatorFocusDistribution=Record<CreatorFocusHypothesis,number>;
export function emptyCreatorFocusDistribution():CreatorFocusDistribution{return Object.fromEntries(CREATOR_FOCUS_HYPOTHESES.map(key=>[key,0])) as CreatorFocusDistribution;}
export const TRADING_FOCUS_HYPOTHESES:CreatorFocusHypothesis[]=['ACTIVE_TRADING_CREATOR','TRADING_EDUCATOR'];
export const ALTERNATIVE_FOCUS_HYPOTHESES:CreatorFocusHypothesis[]=['INVESTING_EDUCATOR','FINANCIAL_NEWS','PERSONAL_FINANCE','MARKET_INSTITUTION','TRADING_ADJACENT','HYPE_OR_PROMOTION','UNRELATED_CREATOR'];
