import {getDb} from '../db';
/** Fixed-cutoff Release-1 baseline. Counts retain explicit denominators and do not infer unlabeled precision/recall. */
export async function getCandidateAdmissionBaseline(cutoff:string){const at=new Date(cutoff);if(!Number.isFinite(at.getTime()))throw new Error('VALID_CUTOFF_REQUIRED');const db=await getDb();const [funnels,reviews,providers,paths,classification,quality,evaluation]=await Promise.all([
 db.query(`SELECT r.country,r.retrieval_lane,r.selection_strategy,q.intent query_semantic_class,q.generation_mode,COUNT(*)::int query_runs,SUM(r.distinct_results)::int nominations,SUM(r.trading_confirmed)::int confirmed,SUM(r.needs_review)::int needs_review,SUM(r.non_trading)::int non_trading,SUM(r.quality_channels)::int quality_creators,SUM(r.communities_discovered)::int communities,SUM(r.quota_used)::int quota_used FROM query_runs r JOIN query_library q ON q.id=r.query_id WHERE r.completed_at<=$1 GROUP BY r.country,r.retrieval_lane,r.selection_strategy,q.intent,q.generation_mode ORDER BY r.country,r.retrieval_lane,r.selection_strategy,q.intent,q.generation_mode`,[at.toISOString()]),
 db.query(`SELECT c.country,d.decision,COUNT(*)::int decisions FROM channel_review_decisions d JOIN channels c USING(channel_id) WHERE d.decided_at<=$1 GROUP BY c.country,d.decision ORDER BY c.country,d.decision`,[at.toISOString()]),
 db.query(`SELECT p.item->>'provider' provider,p.item->>'outcome' outcome,COUNT(*)::int observations FROM production_classification_diagnostics d CROSS JOIN LATERAL jsonb_array_elements(d.provider_execution) p(item) WHERE d.created_at<=$1 GROUP BY p.item->>'provider',p.item->>'outcome' ORDER BY provider,outcome`,[at.toISOString()]),
 db.query(`SELECT COALESCE(n.source_type,'LEGACY_SIGHTING') source_type,COALESCE(n.retrieval_lane,s.search_lane) retrieval_lane,COUNT(*)::int nominations FROM channel_sightings s LEFT JOIN discovery_nominations n ON n.query_run_id=s.query_run_id AND n.channel_id=s.channel_id AND n.page_number=s.page_number WHERE s.observed_at<=$1 GROUP BY 1,2 ORDER BY 1,2`,[at.toISOString()]),
 db.query(`SELECT normalized_input->>'country' country,COALESCE(normalized_input#>>'{detected_languages,0,language}','UNKNOWN') language,decision->>'status' status,staged_report->>'lifecycleAction' lifecycle_action,COUNT(*)::int decisions FROM production_classification_diagnostics WHERE created_at<=$1 GROUP BY 1,2,3,4 ORDER BY 1,2,3,4`,[at.toISOString()]),
 db.query(`SELECT country,trading_status,discord_status,COUNT(*)::int channels,AVG(quality_score)::float average_quality FROM channels WHERE first_seen<=$1 GROUP BY country,trading_status,discord_status ORDER BY country,trading_status,discord_status`,[at.toISOString()]),
 db.query(`SELECT cohort,COUNT(*)::int assignments,AVG(inclusion_basis_points)::float average_inclusion_basis_points FROM evaluation_cohort_assignments WHERE assigned_at<=$1 GROUP BY cohort ORDER BY cohort`,[at.toISOString()])
 ]);return {cutoff:at.toISOString(),denominators:{funnels:'completed query runs at or before cutoff',reviews:'immutable review decisions at or before cutoff',providers:'provider executions recorded in immutable production diagnostics',paths:'durable query sightings/nominations',classification:'immutable production diagnostics at or before cutoff',quality:'channel projection first observed by cutoff',evaluation:'propensity-bearing cohort assignments by cutoff'},segments:{funnels:funnels.rows,reviews:reviews.rows,providers:providers.rows,paths:paths.rows,classification:classification.rows,quality:quality.rows,evaluation:evaluation.rows},limitations:['Recall and protected-audit precision must be computed from propensity-aware labels; this endpoint exposes their denominators but never substitutes production outcomes for ground truth.','Reviewer-hour metrics require an external workforce-time source not present in the repository; review decision counts are reported without fabricated duration.','Legacy sightings may not contain complete source-path provenance.']};}
