-- Phase 2 reuses research_programs but keeps Creator Intelligence state shadow-only.
ALTER TABLE research_programs ADD COLUMN IF NOT EXISTS creator_objective_key TEXT;
ALTER TABLE research_programs ADD COLUMN IF NOT EXISTS creator_objective_version INTEGER CHECK(creator_objective_version>0);
ALTER TABLE research_programs ADD COLUMN IF NOT EXISTS creator_contract_version TEXT;
ALTER TABLE research_programs ADD COLUMN IF NOT EXISTS creator_lifecycle TEXT CHECK(creator_lifecycle IN('DRAFT','ACTIVE','SLEEPING','SATURATED','PAUSED','COMPLETE'));
ALTER TABLE research_programs ADD COLUMN IF NOT EXISTS creator_shadow_only BOOLEAN NOT NULL DEFAULT false;
CREATE UNIQUE INDEX IF NOT EXISTS creator_program_objective_version_idx ON research_programs(creator_objective_key,creator_objective_version) WHERE creator_shadow_only=true;

CREATE TABLE IF NOT EXISTS creator_state_projection_control(singleton BOOLEAN PRIMARY KEY DEFAULT true CHECK(singleton),enabled BOOLEAN NOT NULL DEFAULT false,mode TEXT NOT NULL DEFAULT 'SHADOW' CHECK(mode='SHADOW'),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_by TEXT NOT NULL DEFAULT 'system:migration');
INSERT INTO creator_state_projection_control(singleton) VALUES(true) ON CONFLICT(singleton) DO NOTHING;
CREATE TABLE IF NOT EXISTS creator_program_contract_versions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,objective_key TEXT NOT NULL,objective_version INTEGER NOT NULL CHECK(objective_version>0),objective JSONB NOT NULL CHECK(jsonb_typeof(objective)='object'),budget JSONB NOT NULL CHECK(jsonb_typeof(budget)='object'),creator_lifecycle TEXT NOT NULL CHECK(creator_lifecycle IN('DRAFT','ACTIVE','SLEEPING','SATURATED','PAUSED','COMPLETE')),contract_version TEXT NOT NULL,policy_version TEXT NOT NULL,effective_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(program_id,objective_key,objective_version));
CREATE TABLE IF NOT EXISTS creator_program_coverage_targets(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),target_key TEXT NOT NULL UNIQUE,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,coordinates JSONB NOT NULL CHECK(jsonb_typeof(coordinates)='object'),required BOOLEAN NOT NULL,definition JSONB NOT NULL CHECK(jsonb_typeof(definition)='object'),policy_version TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS creator_program_query_run_links(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),link_key TEXT NOT NULL UNIQUE,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,query_run_id UUID NOT NULL REFERENCES query_runs(id) ON DELETE RESTRICT,coverage_target_keys JSONB NOT NULL CHECK(jsonb_typeof(coverage_target_keys)='array'),attribution_basis TEXT NOT NULL CHECK(attribution_basis IN('EXPLICIT','LEGACY_INFERRED')),actor TEXT NOT NULL,observed_at TIMESTAMPTZ NOT NULL,policy_version TEXT NOT NULL,UNIQUE(program_id,query_run_id));
CREATE TABLE IF NOT EXISTS creator_coverage_projection_runs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),run_key TEXT NOT NULL UNIQUE,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,cutoff_at TIMESTAMPTZ NOT NULL,projection_version TEXT NOT NULL,contract_version TEXT NOT NULL,policy_version TEXT NOT NULL,input_checksum TEXT NOT NULL CHECK(input_checksum~'^[a-f0-9]{64}$'),output_checksum TEXT NOT NULL CHECK(output_checksum~'^[a-f0-9]{64}$'),coverage_count INTEGER NOT NULL CHECK(coverage_count>=0),frontier_count INTEGER NOT NULL CHECK(frontier_count>=0),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS creator_coverage_shadow_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),snapshot_key TEXT NOT NULL UNIQUE,projection_run_id UUID NOT NULL REFERENCES creator_coverage_projection_runs(id) ON DELETE RESTRICT,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,target_key TEXT NOT NULL REFERENCES creator_program_coverage_targets(target_key) ON DELETE RESTRICT,coordinates JSONB NOT NULL,observed_accounts INTEGER NOT NULL CHECK(observed_accounts>=0),observed_creator_clusters INTEGER NOT NULL CHECK(observed_creator_clusters>=0),verified_active_creators INTEGER NOT NULL CHECK(verified_active_creators>=0),estimated_unexplored DOUBLE PRECISION,uncertainty DOUBLE PRECISION NOT NULL CHECK(uncertainty BETWEEN 0 AND 1),marginal_verified_yield DOUBLE PRECISION NOT NULL CHECK(marginal_verified_yield>=0),lifecycle TEXT NOT NULL CHECK(lifecycle IN('ACTIVE','SLEEPING','SATURATED','PAUSED','UNREACHABLE')),as_of TIMESTAMPTZ NOT NULL,policy_version TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS creator_frontier_shadow_snapshots(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),frontier_key TEXT NOT NULL UNIQUE,projection_run_id UUID NOT NULL REFERENCES creator_coverage_projection_runs(id) ON DELETE RESTRICT,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,target_key TEXT NOT NULL REFERENCES creator_program_coverage_targets(target_key) ON DELETE RESTRICT,state TEXT NOT NULL CHECK(state IN('UNEXPLORED','PARTIALLY_OBSERVED','OBSERVED','UNKNOWN','SLEEPING')),observed_creator_clusters INTEGER NOT NULL CHECK(observed_creator_clusters>=0),estimated_unexplored DOUBLE PRECISION,uncertainty DOUBLE PRECISION NOT NULL CHECK(uncertainty BETWEEN 0 AND 1),reason_codes JSONB NOT NULL CHECK(jsonb_typeof(reason_codes)='array'),as_of TIMESTAMPTZ NOT NULL,policy_version TEXT NOT NULL,serving_authority BOOLEAN NOT NULL DEFAULT false CHECK(serving_authority=false));
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['creator_program_contract_versions','creator_program_coverage_targets','creator_program_query_run_links','creator_coverage_projection_runs','creator_coverage_shadow_snapshots','creator_frontier_shadow_snapshots'] LOOP EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_immutable_event_mutation()',t,t); END LOOP; END $$;
COMMENT ON TABLE creator_frontier_shadow_snapshots IS 'Phase 2 opportunity state only; rows cannot materialize jobs, queries, or discovery actions.';
