-- Phase 3 records counterfactual SEARCH_YOUTUBE proposals only. It has no job,
-- scheduler, assignment, provider execution, or canary integration.
CREATE TABLE IF NOT EXISTS creator_action_proposal_control(singleton BOOLEAN PRIMARY KEY DEFAULT true CHECK(singleton),enabled BOOLEAN NOT NULL DEFAULT false,mode TEXT NOT NULL DEFAULT 'SHADOW' CHECK(mode='SHADOW'),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),updated_by TEXT NOT NULL DEFAULT 'system:migration');
INSERT INTO creator_action_proposal_control(singleton) VALUES(true) ON CONFLICT(singleton) DO NOTHING;
CREATE TABLE IF NOT EXISTS creator_action_proposal_runs(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),run_key TEXT NOT NULL UNIQUE,cutoff_at TIMESTAMPTZ NOT NULL,projection_version TEXT NOT NULL,policy_version TEXT NOT NULL,input_checksum TEXT NOT NULL CHECK(input_checksum~'^[a-f0-9]{64}$'),output_checksum TEXT NOT NULL CHECK(output_checksum~'^[a-f0-9]{64}$'),opportunity_count INTEGER NOT NULL CHECK(opportunity_count>=0),proposal_count INTEGER NOT NULL CHECK(proposal_count=opportunity_count),created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS creator_action_shadow_proposals(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),proposal_key TEXT NOT NULL UNIQUE,projection_run_id UUID NOT NULL REFERENCES creator_action_proposal_runs(id) ON DELETE RESTRICT,program_id UUID NOT NULL REFERENCES research_programs(id) ON DELETE RESTRICT,hypothesis_id UUID NOT NULL REFERENCES discovery_hypotheses(id) ON DELETE RESTRICT,objective_key TEXT NOT NULL,scheduling_query_run_id UUID NOT NULL REFERENCES query_runs(id) ON DELETE RESTRICT,action_type TEXT NOT NULL CHECK(action_type='SEARCH_YOUTUBE'),provider_key TEXT NOT NULL CHECK(provider_key='youtube-search'),normalized_target TEXT NOT NULL,expected_creator_value DOUBLE PRECISION NOT NULL CHECK(expected_creator_value>=0),expected_coverage_gain DOUBLE PRECISION NOT NULL CHECK(expected_coverage_gain>=0),expected_information_gain DOUBLE PRECISION NOT NULL CHECK(expected_information_gain>=0),expected_uncertainty_reduction DOUBLE PRECISION NOT NULL CHECK(expected_uncertainty_reduction>=0),expected_provider_cost DOUBLE PRECISION NOT NULL CHECK(expected_provider_cost>=0),expected_review_cost DOUBLE PRECISION NOT NULL CHECK(expected_review_cost>=0),expected_utility DOUBLE PRECISION NOT NULL,confidence DOUBLE PRECISION NOT NULL CHECK(confidence BETWEEN 0 AND 1),supporting_evidence JSONB NOT NULL CHECK(jsonb_typeof(supporting_evidence)='array'),reasoning TEXT NOT NULL,provenance JSONB NOT NULL CHECK(jsonb_typeof(provenance)='object'),policy_version TEXT NOT NULL,serving_authority BOOLEAN NOT NULL DEFAULT false CHECK(serving_authority=false));
CREATE TABLE IF NOT EXISTS creator_action_counterfactual_comparisons(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),comparison_key TEXT NOT NULL UNIQUE,projection_run_id UUID NOT NULL REFERENCES creator_action_proposal_runs(id) ON DELETE RESTRICT,proposal_id UUID NOT NULL REFERENCES creator_action_shadow_proposals(id) ON DELETE RESTRICT,actual_query_run_id UUID NOT NULL REFERENCES query_runs(id) ON DELETE RESTRICT,actual_query_id INTEGER NOT NULL REFERENCES query_library(id) ON DELETE RESTRICT,proposed_query_id INTEGER REFERENCES query_library(id) ON DELETE RESTRICT,agrees BOOLEAN NOT NULL,difference_codes JSONB NOT NULL CHECK(jsonb_typeof(difference_codes)='array'),actual_expected_utility DOUBLE PRECISION NOT NULL,creator_expected_utility DOUBLE PRECISION NOT NULL,confidence DOUBLE PRECISION NOT NULL CHECK(confidence BETWEEN 0 AND 1),supporting_evidence JSONB NOT NULL CHECK(jsonb_typeof(supporting_evidence)='array'),actual_selection JSONB NOT NULL CHECK(jsonb_typeof(actual_selection)='object'),creator_proposal JSONB NOT NULL CHECK(jsonb_typeof(creator_proposal)='object'),policy_version TEXT NOT NULL,serving_authority BOOLEAN NOT NULL DEFAULT false CHECK(serving_authority=false));
DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['creator_action_proposal_runs','creator_action_shadow_proposals','creator_action_counterfactual_comparisons'] LOOP EXECUTE format('CREATE TRIGGER %I_immutable BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION reject_immutable_event_mutation()',t,t); END LOOP; END $$;
COMMENT ON TABLE creator_action_shadow_proposals IS 'Counterfactual proposals only; Phase 3 cannot enqueue, materialize, assign, or execute an action.';
