import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { CREATOR_READINESS_POLICY_VERSION, type ShadowAllocationCandidate } from './readiness';
import { CREATOR_SEARCH_CANARY_POLICY_VERSION, creatorCanaryBucket, decideCreatorCanaryArm, type CreatorCanaryControl } from './canary';
import { resolveFeaturedChannelLineage, type FeaturedChannelLineageCandidate } from './featuredChannelLineageReconciler';

const at='2026-08-09T00:00:00.000Z',candidate:ShadowAllocationCandidate={programId:'program-1',programKey:'de-futures',objective:{objectiveKey:'de-futures',version:2,title:'German futures',statement:'Find creators.',coordinates:{country:'Germany'},criteria:{},coverageDefinition:{},evaluationHorizonDays:30,createdAt:at,policyVersion:'objective-v2'},hypothesisId:'hypothesis-1',hypothesisKey:'gap-1',hypothesisConfidence:.8,frontierUncertainty:.7,evidenceKeys:['frontier-1']};
const control:CreatorCanaryControl={enabled:true,killSwitch:false,servingAuthorityEnabled:true,topLevelAuthorityEnabled:true,playlistAuthorityEnabled:false,playlistRolloutBasisPoints:0,featuredChannelAuthorityEnabled:true,featuredChannelRolloutBasisPoints:1000,rolloutBasisPoints:1000,globalDailyAllocationCap:10,globalDailyQuotaCap:1000,maximumReadinessAgeHours:24,minimumAttributionCompleteness:1,readinessPolicyVersion:CREATOR_READINESS_POLICY_VERSION,policyVersion:CREATOR_SEARCH_CANARY_POLICY_VERSION,configurationVersion:3};
const opportunity=(()=>{for(let i=0;i<100000;i++)if(creatorCanaryBucket(`featured-${i}`)<1000)return `featured-${i}`;throw new Error('NO_TEST_BUCKET')})();

test('featured treatment reuses shared deterministic assignment and propensity ledger',()=>{const input={opportunityKey:opportunity,country:'Germany',assignedAt:at,estimatedQuotaUnits:1,control,safetyReasons:[],candidate,readinessRunId:'readiness-1',eligibilityChecksum:'a'.repeat(64),actionType:'INSPECT_FEATURED_CHANNELS' as const,nonQueryProposalId:'proposal-1'},assignment=decideCreatorCanaryArm(input);assert.deepEqual(assignment,decideCreatorCanaryArm(input));assert.equal(assignment.assignmentStatus,'CANARY_ALLOCATED');assert.equal(assignment.actionType,'INSPECT_FEATURED_CHANNELS');assert.equal(assignment.behaviorPropensityBasisPoints,1000)});
test('any featured safety failure deterministically becomes non-serving control',()=>{const assignment=decideCreatorCanaryArm({opportunityKey:opportunity,country:'Germany',assignedAt:at,estimatedQuotaUnits:1,control,safetyReasons:['FEATURED_CHANNEL_ADAPTER_DISABLED'],candidate,readinessRunId:'readiness-1',eligibilityChecksum:'b'.repeat(64),actionType:'INSPECT_FEATURED_CHANNELS',nonQueryProposalId:'proposal-1'});assert.equal(assignment.arm,'CONTROL');assert.equal(assignment.servingAuthority,false);assert.equal(assignment.treatmentPropensityBasisPoints,0)});

test('Phase 8 migration extends only shared canary structures and defaults featured authority off',()=>{const sql=readFileSync(new URL('../db/migrations/080_creator_featured_channel_canary.sql',import.meta.url),'utf8');assert.match(sql,/featured_channel_authority_enabled BOOLEAN NOT NULL DEFAULT false/);assert.match(sql,/featured_channel_rollout_basis_points INTEGER NOT NULL DEFAULT 0/);assert.match(sql,/action_type IN\('SEARCH_YOUTUBE','INSPECT_PLAYLIST','INSPECT_FEATURED_CHANNELS'\)/);assert.match(sql,/creator_featured_channel_canary_execution_links/);assert.match(sql,/reconciliation_events_immutable/);assert.doesNotMatch(sql,/INSPECT_COLLABORATOR|INSPECT_WEBSITE_AUTHOR|RESOLVE_EXTERNAL_ENTITY|CREATE TABLE .*assignments/i)});

test('materializer consumes only completed attributable featured proposals and treatment alone enqueues',()=>{const source=readFileSync(new URL('./featuredChannelCanary.ts',import.meta.url),'utf8');assert.match(source,/acquisition_type='INSPECT_FEATURED_CHANNELS'/);assert.match(source,/r\.disposition='COMPLETED'/);assert.match(source,/outcome\.identity_confidence='CONFIRMED'/);assert.match(source,/assignment\.assignmentStatus==='CANARY_ALLOCATED'/);assert.match(source,/enqueueFeaturedChannelCanary/);assert.doesNotMatch(source,/searchYouTube|INSPECT_COLLABORATOR|INSPECT_WEBSITE_AUTHOR|RESOLVE_EXTERNAL_ENTITY/)});

test('worker executes one existing adapter request and creates no recursive or search work',()=>{const worker=readFileSync(new URL('../featuredChannelAdapterWorker.ts',import.meta.url),'utf8');assert.match(worker,/fetchYouTubeFeaturedChannels/);assert.match(worker,/validateFeaturedChannelPayload/);assert.match(worker,/sourceType:'FEATURED_CHANNEL'/);assert.match(worker,/featured_channel_authority_enabled/);assert.doesNotMatch(worker,/INSERT INTO frontier_actions|enqueueFeaturedChannelCanary|searchYouTube|channelSections|INSPECT_COLLABORATOR|INSPECT_WEBSITE/)});

test('featured reconciliation passes one complete path and abstains otherwise',()=>{const item:FeaturedChannelLineageCandidate={frontierActionId:'frontier-1',semanticActionKey:'semantic-1',jobId:'job-1',jobIdempotencyKey:'featured-channels:semantic-1',sourceChannelId:'UC_x5XG1OV2P6uZZ5FSM9Ttw',sourceCanonicalEntityId:'22222222-2222-4222-8222-222222222222'};assert.equal(resolveFeaturedChannelLineage([item]).result,'PASS');assert.equal(resolveFeaturedChannelLineage([]).result,'ABSTAIN');assert.deepEqual(resolveFeaturedChannelLineage([item,{...item,jobId:'job-2'}]).reasonCodes,['FEATURED_CHANNEL_LINEAGE_EVIDENCE_AMBIGUOUS']);const source=readFileSync(new URL('./featuredChannelLineageReconciler.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/enqueue|fetchYouTube|completeJob|UPDATE (jobs|frontier_actions|acquisition_adapter_runs)/i)});

test('readiness reconciles featured lineage before projections and makes it a required check',()=>{const source=readFileSync(new URL('./readiness.ts',import.meta.url),'utf8'),reconcile=source.indexOf('await reconcileCreatorFeaturedChannelLineage(cutoffAt)'),outcomes=source.indexOf('await projectShadowCreatorOutcomes(cutoffAt)'),guards=source.indexOf('await projectShadowGuardrails(');assert.ok(reconcile>=0&&reconcile<outcomes&&reconcile<guards);assert.match(source,/featuredChannelLineageReconciliation: featuredChannelLineage\.result/)});

test('kill switch, serving disablement, and zero rollout remove featured authority through audited shared control',()=>{const source=readFileSync(new URL('./canary.ts',import.meta.url),'utf8');assert.match(source,/featuredChannelAuthority = !enabled \|\| killSwitch \|\| !requestedAuthority \|\| featuredChannelRollout === 0 \? false/);assert.match(source,/creator_search_canary_control_events/)});

test('queue and enqueue recheck every rollback control before provider execution',()=>{const queue=readFileSync(new URL('../queueManager.ts',import.meta.url),'utf8'),adapter=readFileSync(new URL('../evidenceGraphAdapters.ts',import.meta.url),'utf8');for(const source of [queue,adapter]){assert.match(source,/featured_channel_authority_enabled/);assert.match(source,/featured_channel_rollout_basis_points/);assert.match(source,/serving_authority_enabled/);assert.match(source,/kill_switch/)}assert.match(queue,/adapter\.mode='CANARY'/);assert.match(adapter,/CREATOR_FEATURED_CHANNEL_AUTHORITY_DISABLED/)});
