import { getDb } from '../db';
import { enqueueFeaturedChannelCanary } from '../evidenceGraphAdapters';
import { FEATURED_CHANNEL_ADAPTER_POLICY_VERSION, FEATURED_CHANNEL_PROVIDER_COST } from '../featuredChannelAdapter';
import { creatorIntelligenceChecksum } from './contracts';
import { allocateCreatorSearchCanary } from './canary';

export const CREATOR_FEATURED_CHANNEL_CANARY_POLICY_VERSION='creator-featured-channel-canary-v1';

export async function materializeCreatorFeaturedChannelCanary(cutoffAt:string):Promise<{considered:number;treatment:number;control:number;queued:number;fallback:number}>{
 if(!Number.isFinite(new Date(cutoffAt).getTime()))throw new Error('INVALID_FEATURED_CHANNEL_CANARY_CUTOFF');const db=await getDb();
 const [controlResult,adapterResult]=await Promise.all([db.query(`SELECT * FROM creator_search_canary_control WHERE singleton=true`),db.query(`SELECT * FROM acquisition_adapter_controls WHERE adapter_type='INSPECT_FEATURED_CHANNELS'`)]),control=controlResult.rows[0],adapter=adapterResult.rows[0];
 if(!control?.featured_channel_authority_enabled||Number(control.featured_channel_rollout_basis_points)<=0)return {considered:0,treatment:0,control:0,queued:0,fallback:0};
 const rows=await db.query(`SELECT p.id proposal_id,p.proposal_key,p.program_id,p.objective_key,p.objective_version,p.hypothesis_id,p.normalized_target,r.readiness_run_id,l.source_allocation_run_id,cv.objective,f.id frontier_action_id,f.semantic_action_key,b.entity_id source_canonical_entity_id FROM creator_non_query_shadow_proposals p JOIN creator_non_query_shadow_runs r ON r.id=p.projection_run_id AND r.disposition='COMPLETED' JOIN creator_non_query_shadow_lineage l ON l.proposal_id=p.id JOIN creator_program_contract_versions cv ON cv.program_id=p.program_id AND cv.objective_key=p.objective_key AND cv.objective_version=p.objective_version JOIN LATERAL(SELECT min(entity_id::text)::uuid entity_id FROM entity_bindings WHERE namespace='YOUTUBE_CHANNEL_ID' AND normalized_value=p.normalized_target AND status='APPROVED' HAVING count(*)=1)b ON true JOIN LATERAL(SELECT action.* FROM frontier_actions action WHERE action.program_id=p.program_id AND action.action_type='INSPECT_FEATURED_CHANNELS' AND action.lifecycle='PROPOSED' AND action.normalized_target='channel:'||p.normalized_target AND action.validity_start<=$1 AND action.validity_end>$1 AND NOT EXISTS(SELECT 1 FROM creator_featured_channel_canary_execution_links prior WHERE prior.frontier_action_id=action.id) AND EXISTS(SELECT 1 FROM jsonb_array_elements_text(l.creator_outcome_ids) ids(outcome_id) JOIN creator_outcome_records outcome ON outcome.id=ids.outcome_id::uuid WHERE outcome.channel_id=p.normalized_target AND outcome.identity_confidence='CONFIRMED' AND (action.source_query_run_id IS NULL OR outcome.query_run_id=action.source_query_run_id)) ORDER BY action.validity_start,action.semantic_action_key LIMIT 1)f ON true WHERE p.acquisition_type='INSPECT_FEATURED_CHANNELS' AND p.serving_authority=false AND p.execution_propensity_basis_points=0 AND p.proposed_at<=$1 AND NOT EXISTS(SELECT 1 FROM creator_featured_channel_canary_execution_links prior WHERE prior.proposal_id=p.id) ORDER BY p.proposed_at,p.proposal_key LIMIT 1`,[cutoffAt]);
 if(!rows.rowCount)return {considered:0,treatment:0,control:0,queued:0,fallback:0};const proposal=rows.rows[0],objective=typeof proposal.objective==='string'?JSON.parse(proposal.objective):proposal.objective,country=String(objective?.coordinates?.country||''),reasons:string[]=[];
 if(!country)reasons.push('FEATURED_CHANNEL_COUNTRY_MISSING');if(!adapter||adapter.mode!=='CANARY'||adapter.paused||adapter.kill_switch)reasons.push('FEATURED_CHANNEL_ADAPTER_DISABLED');if(adapter?.policy_version!==FEATURED_CHANNEL_ADAPTER_POLICY_VERSION)reasons.push('FEATURED_CHANNEL_ADAPTER_POLICY_MISMATCH');
 const daily=await db.query(`SELECT COUNT(*)::int count FROM acquisition_adapter_runs WHERE adapter_type='INSPECT_FEATURED_CHANNELS' AND created_at>=date_trunc('day',$1::timestamptz AT TIME ZONE 'UTC') AT TIME ZONE 'UTC'`,[cutoffAt]);if(adapter&&Number(daily.rows[0]?.count)+FEATURED_CHANNEL_PROVIDER_COST>Number(adapter.daily_quota_cap))reasons.push('FEATURED_CHANNEL_ADAPTER_DAILY_CAP');if(adapter&&Number(adapter.consumed_quota)+FEATURED_CHANNEL_PROVIDER_COST>Number(adapter.total_quota_cap))reasons.push('FEATURED_CHANNEL_ADAPTER_TOTAL_CAP');
 const opportunityKey=creatorIntelligenceChecksum({proposalKey:proposal.proposal_key,frontierActionId:proposal.frontier_action_id,validityDay:new Date(cutoffAt).toISOString().slice(0,10),policyVersion:CREATOR_FEATURED_CHANNEL_CANARY_POLICY_VERSION}),assignment=await allocateCreatorSearchCanary({opportunityKey,country:country||'UNKNOWN',assignedAt:cutoffAt,estimatedQuotaUnits:FEATURED_CHANNEL_PROVIDER_COST,requiredProgramId:proposal.program_id,requiredHypothesisId:proposal.hypothesis_id,additionalSafetyReasons:reasons,actionType:'INSPECT_FEATURED_CHANNELS',nonQueryProposalId:proposal.proposal_id,rolloutBasisPointsOverride:Number(control.featured_channel_rollout_basis_points)});
 let disposition:'CONTROL'|'QUEUED'|'ADAPTER_FALLBACK'='CONTROL',reasonCodes=assignment.reasonCodes,jobId:string|undefined;if(assignment.assignmentStatus==='CANARY_ALLOCATED'){const result=await enqueueFeaturedChannelCanary(proposal.frontier_action_id,country,proposal.source_canonical_entity_id);if(result.queued){disposition='QUEUED';jobId=result.jobId;reasonCodes=['FEATURED_CHANNEL_CANARY_QUEUED'];}else{disposition='ADAPTER_FALLBACK';reasonCodes=[result.reason||'FEATURED_CHANNEL_ADAPTER_FALLBACK'];}}
 const readinessRunId=assignment.readinessRunId||proposal.readiness_run_id;if(!assignment.assignmentId||!readinessRunId||!proposal.source_allocation_run_id)throw new Error('FEATURED_CHANNEL_CANARY_ASSIGNMENT_LINEAGE_MISSING');const lineage={assignmentKey:assignment.assignmentKey,proposalKey:proposal.proposal_key,frontierActionId:proposal.frontier_action_id,readinessRunId,sourceAllocationRunId:proposal.source_allocation_run_id,disposition,reasonCodes,jobId:jobId||null},linkKey=creatorIntelligenceChecksum({...lineage,policyVersion:CREATOR_FEATURED_CHANNEL_CANARY_POLICY_VERSION});
 await db.query(`INSERT INTO creator_featured_channel_canary_execution_links(link_key,assignment_id,proposal_id,frontier_action_id,job_id,disposition,reason_codes,readiness_run_id,source_allocation_run_id,lineage_checksum,assignment_policy_version,adapter_policy_version,linked_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) ON CONFLICT(link_key) DO NOTHING`,[linkKey,assignment.assignmentId,proposal.proposal_id,proposal.frontier_action_id,jobId||null,disposition,JSON.stringify(reasonCodes),readinessRunId,proposal.source_allocation_run_id,creatorIntelligenceChecksum(lineage),assignment.policyVersion,FEATURED_CHANNEL_ADAPTER_POLICY_VERSION,cutoffAt]);
 return {considered:1,treatment:assignment.assignmentStatus==='CANARY_ALLOCATED'?1:0,control:assignment.arm==='CONTROL'?1:0,queued:disposition==='QUEUED'?1:0,fallback:disposition==='ADAPTER_FALLBACK'?1:0};
}
