import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {creatorActionUtility,proposeShadowCreatorAction,type ActualQuerySelection,type CreatorActionHypothesis,type CreatorSearchCandidate} from './shadowPlanner';
import type {CreatorDiscoveryObjective} from './contracts';

const at='2026-08-09T00:00:00.000Z',objective:CreatorDiscoveryObjective={objectiveKey:'german-futures',version:1,title:'German futures creators',statement:'Find active German futures educators.',coordinates:{country:'Germany',language:'de',market:'futures'},criteria:{roles:['EDUCATOR'],activityRequirement:'ACTIVE'},coverageDefinition:{dimensions:['country','market']},evaluationHorizonDays:90,createdAt:at,policyVersion:'objective-v1'},hypothesis:CreatorActionHypothesis={hypothesisId:'00000000-0000-0000-0000-000000000010',statement:'DAX analysis searches expose the uncovered futures-educator segment.',confidence:.8,sourceFamilyIds:['source-family-1'],supportingEvidence:['hypothesis:event'],provenance:{sourceBound:true}},candidate=(id:number,query:string,patch:Partial<CreatorSearchCandidate>={}):CreatorSearchCandidate=>({queryId:id,query,expectedIncrementalCreators:.2,expectedCoverageGain:.5,expectedInformationGain:.5,expectedUncertaintyReduction:.4,expectedProviderCost:100,expectedReviewCost:.1,supportingEvidence:[`query:${id}`],...patch}),actual:ActualQuerySelection={queryRunId:'00000000-0000-0000-0000-000000000020',queryId:1,query:'DAX Trading',country:'Germany',selectedAt:at,selectionStrategy:'UCB1_EXPLOITATION',selectionReason:'legacy selection',expectedUtility:candidate(1,'DAX Trading'),sourceEventKey:'query-run:actual:selected:v1'};
test('shadow planner deterministically chooses highest creator utility with stable tie breaking',()=>{const inputs={programId:'00000000-0000-0000-0000-000000000001',objective,hypothesis,frontier:{targetKey:'germany:futures',uncertainty:.8,estimatedUnexplored:null,state:'UNEXPLORED',evidenceKeys:['frontier:1']},candidates:[candidate(1,'DAX Trading'),candidate(2,'DAX Analyse',{expectedIncrementalCreators:.8})],actual},a=proposeShadowCreatorAction(inputs),b=proposeShadowCreatorAction({...inputs,candidates:[...inputs.candidates].reverse()});assert.deepEqual(a,b);assert.equal(a.proposal.proposedQueryId,2);assert.equal(a.proposal.action.actionType,'SEARCH_YOUTUBE');assert.equal(a.proposal.servingAuthority,false);assert.equal(a.comparison.agrees,false);assert.ok(a.comparison.differenceCodes.includes('QUERY_ID_DIFFERS'));});
test('agreement is explicit when both systems select the same query',()=>{const result=proposeShadowCreatorAction({programId:'p',objective,hypothesis,frontier:{targetKey:'t',uncertainty:.2,estimatedUnexplored:1,state:'PARTIALLY_OBSERVED',evidenceKeys:['f']},candidates:[candidate(1,'DAX Trading')],actual});assert.equal(result.comparison.agrees,true);assert.deepEqual(result.comparison.differenceCodes,['SAME_QUERY']);});
test('utility includes creator, coverage, information, uncertainty, provider, and review terms',()=>{assert.ok(creatorActionUtility(candidate(1,'a',{expectedIncrementalCreators:1}))>creatorActionUtility(candidate(1,'a',{expectedIncrementalCreators:0})));assert.ok(creatorActionUtility(candidate(1,'a',{expectedProviderCost:200}))<creatorActionUtility(candidate(1,'a',{expectedProviderCost:100})));});
test('Phase 3 migration is immutable, disabled, shadow-only, and SEARCH_YOUTUBE-only',()=>{const sql=readFileSync(new URL('../db/migrations/072_creator_action_counterfactual_shadow.sql',import.meta.url),'utf8');for(const table of ['creator_action_proposal_control','creator_action_proposal_runs','creator_action_shadow_proposals','creator_action_counterfactual_comparisons'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/enabled BOOLEAN NOT NULL DEFAULT false/);assert.match(sql,/action_type='SEARCH_YOUTUBE'/);assert.match(sql,/serving_authority=false/);assert.match(sql,/proposal_count=opportunity_count/);assert.match(sql,/reject_immutable_event_mutation/);assert.doesNotMatch(sql,/INSERT INTO jobs|discovery_action_assignments|mode='CANARY'|DROP TABLE|DROP COLUMN|TRUNCATE/i);});
test('Phase 3 planner has no production, queue, provider, or scheduler wiring',()=>{for(const file of ['../../server.ts','../autonomousDiscovery.ts','../queueManager.ts','../queryIntelligence.ts','../persistentResearchController.ts'])assert.doesNotMatch(readFileSync(new URL(file,import.meta.url),'utf8'),/projectShadowCreatorActionProposals|creator_action_shadow_proposals/);const module=readFileSync(new URL('./shadowPlanner.ts',import.meta.url),'utf8');assert.doesNotMatch(module,/enqueueJob|scheduleAutonomousQueryRuns|searchYouTube|fetch\s*\(/);});
