import assert from 'node:assert/strict';
import test from 'node:test';
import {readFileSync} from 'node:fs';
import {CREATOR_INTELLIGENCE_CONTRACT_VERSION,type CreatorCoverageTarget,type CreatorOutcome,type CreatorProgram} from './contracts';
import {projectCreatorProgramState} from './shadowState';

const now='2026-08-09T00:00:00.000Z';
const program:CreatorProgram={programId:'00000000-0000-0000-0000-000000000001',programKey:'german-futures-educators',objective:{objectiveKey:'german-futures-educators',version:1,title:'German futures educators',statement:'Find active German futures educators.',coordinates:{country:'Germany',language:'de',market:'futures'},criteria:{roles:['EDUCATOR'],activityRequirement:'ACTIVE',requiresEducationalContent:true,requiresCommunity:false,minimumQualityScore:55,inclusion:['independent creators'],exclusion:['financial news']},coverageDefinition:{dimensions:['country','language','market','creatorCluster']},evaluationHorizonDays:90,createdAt:now,policyVersion:'objective-v1'},lifecycle:'ACTIVE',budget:{providerUnits:1000,reviewUnits:10},servingAuthority:false,createdAt:now,updatedAt:now,policyVersion:'program-v1'};
const target:CreatorCoverageTarget={targetKey:'germany:de:futures',programId:program.programId,coordinates:{country:'Germany',language:'de',market:'futures'},required:true,definition:{creatorRole:'EDUCATOR'},policyVersion:'target-v1'};
const outcome=(patch:Partial<CreatorOutcome>={}):CreatorOutcome=>({outcomeKey:'outcome-1',actionId:'legacy-query-run:1',objectiveKey:program.objective.objectiveKey,creator:{canonicalCreatorId:'00000000-0000-0000-0000-000000000002',sourceAccountId:'channel-1',sourceAccountType:'YOUTUBE_CHANNEL',identityConfidence:'CONFIRMED',entityClusterKey:'cluster-1'},outcomeType:'NEW_VERIFIED_CREATOR',maturity:'TERMINAL',incremental:true,activeCreatorCredit:true,verifiedCreatorCredit:true,coverageCellKeys:[],cost:{providerUnits:100,reviewUnits:0},evidence:{sourceEventKeys:['event-1'],countryStatus:'CONFIRMED',tradingStatus:'TRADING_CONFIRMED',activity:{status:'ACTIVE',observedAt:now,evidenceSourceIds:['activity-1'],policyVersion:'activity-v1'}},observedAt:now,effectiveAt:now,policyVersion:'outcome-v1',contractVersion:CREATOR_INTELLIGENCE_CONTRACT_VERSION,...patch});

test('coverage projection counts accounts, resolved clusters, active creators, and marginal verified yield',()=>{const projected=projectCreatorProgramState(program,[target],[{outcome:outcome(),coverageTargetKeys:[target.targetKey]}],now);assert.deepEqual({accounts:projected.coverage[0].observedAccounts,clusters:projected.coverage[0].observedCanonicalCreators,active:projected.coverage[0].verifiedActiveCreators,yield:projected.coverage[0].marginalVerifiedYield},{accounts:1,clusters:1,active:1,yield:1});assert.equal(projected.coverage[0].estimatedUnseenCreators,null);assert.ok(projected.frontier[0].reasonCodes.includes('UNEXPLORED_COVERAGE_NOT_ESTIMABLE'));});
test('unobserved declared targets remain explicit frontier without generating actions',()=>{const projected=projectCreatorProgramState(program,[target],[],now);assert.equal(projected.frontier[0].state,'UNEXPLORED');assert.equal(projected.frontier[0].servingAuthority,false);assert.equal(projected.coverage[0].uncertainty,1);});
test('uncertain and unresolved outcomes preserve partial coverage uncertainty',()=>{const unresolved=outcome({creator:{sourceAccountId:'channel-2',sourceAccountType:'YOUTUBE_CHANNEL',identityConfidence:'UNRESOLVED'},outcomeType:'NEEDS_REVIEW',maturity:'ENRICHED',incremental:false,activeCreatorCredit:false,verifiedCreatorCredit:false});const projected=projectCreatorProgramState(program,[target],[{outcome:unresolved,coverageTargetKeys:[target.targetKey]}],now);assert.equal(projected.frontier[0].state,'PARTIALLY_OBSERVED');assert.equal(projected.coverage[0].observedCanonicalCreators,0);assert.equal(projected.coverage[0].uncertainty,1);});
test('independent retrieval lanes can produce a directional unexplored estimate',()=>{const second=outcome({outcomeKey:'outcome-2',creator:{...outcome().creator,canonicalCreatorId:'00000000-0000-0000-0000-000000000003',sourceAccountId:'channel-2',entityClusterKey:'cluster-2'}}),third=outcome({outcomeKey:'outcome-3',creator:{...outcome().creator,canonicalCreatorId:'00000000-0000-0000-0000-000000000004',sourceAccountId:'channel-3',entityClusterKey:'cluster-3'}}),projected=projectCreatorProgramState(program,[target],[{outcome:outcome(),coverageTargetKeys:[target.targetKey],sourceLane:'VIDEO'},{outcome:second,coverageTargetKeys:[target.targetKey],sourceLane:'VIDEO'},{outcome:second,coverageTargetKeys:[target.targetKey],sourceLane:'CHANNEL'},{outcome:third,coverageTargetKeys:[target.targetKey],sourceLane:'CHANNEL'}],now);assert.notEqual(projected.coverage[0].estimatedUnseenCreators,null);assert.ok(projected.frontier[0].reasonCodes.includes('SOURCE_CORRELATION_MUST_BE_AUDITED'));});
test('sleeping programs project sleeping coverage and frontier without execution authority',()=>{const projected=projectCreatorProgramState({...program,lifecycle:'SLEEPING'},[target],[],now);assert.equal(projected.coverage[0].lifecycle,'SLEEPING');assert.equal(projected.frontier[0].state,'SLEEPING');});
test('projection is cutoff-bound, deterministic, and rejects cross-program targets',()=>{const future=outcome({effectiveAt:'2026-09-01T00:00:00.000Z'}),a=projectCreatorProgramState(program,[target],[{outcome:future,coverageTargetKeys:[target.targetKey]}],now),b=projectCreatorProgramState(program,[target],[{outcome:future,coverageTargetKeys:[target.targetKey]}],now);assert.deepEqual(a,b);assert.equal(a.coverage[0].observedAccounts,0);assert.throws(()=>projectCreatorProgramState(program,[{...target,programId:'other'}],[],now),/PROGRAM_MISMATCH/);});
test('Phase 2 migration reuses research programs and remains additive, immutable, disabled, and shadow-only',()=>{const sql=readFileSync(new URL('../db/migrations/071_creator_program_coverage_shadow.sql',import.meta.url),'utf8');assert.match(sql,/ALTER TABLE research_programs/);for(const table of ['creator_state_projection_control','creator_program_contract_versions','creator_program_coverage_targets','creator_program_query_run_links','creator_coverage_projection_runs','creator_coverage_shadow_snapshots','creator_frontier_shadow_snapshots'])assert.match(sql,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(sql,/enabled BOOLEAN NOT NULL DEFAULT false/);assert.match(sql,/serving_authority=false/);assert.match(sql,/reject_immutable_event_mutation/);assert.doesNotMatch(sql,/CREATE TABLE IF NOT EXISTS creator_programs|INSERT INTO jobs|discovery_actions|DROP TABLE|DROP COLUMN|TRUNCATE/i);});
test('Phase 2 state has no production wiring or scheduling vocabulary',()=>{for(const file of ['../../server.ts','../autonomousDiscovery.ts','../queueManager.ts','../queryIntelligence.ts','../persistentResearchController.ts'])assert.doesNotMatch(readFileSync(new URL(file,import.meta.url),'utf8'),/projectShadowCreatorProgramState|creator_frontier_shadow_snapshots/);const module=readFileSync(new URL('./shadowState.ts',import.meta.url),'utf8');assert.doesNotMatch(module,/enqueueJob|scheduleAutonomousQueryRuns|proposeDiscoveryAction/);});
