import { createHash } from 'node:crypto';
import { completeJob, enqueueJob, getDb } from './db';

export const CORPUS_POLICY_VERSION='corpus-policy-v1';
export const EXTRACTOR_VERSION='deterministic-ngram-v1';
export const OFFSET_SCHEME='UNICODE_CODE_POINT_V1';
const word=/[\p{L}\p{N}][\p{L}\p{N}\p{M}'’.-]*/gu;
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
export interface CandidateSpan { literal:string; normalized:string; startOffset:number; endOffset:number; ngramSize:number; occurrenceKey:string }
export function contentHash(text:string):string{return sha(text.normalize('NFC'));}
export function sliceCodePoints(text:string,start:number,end:number):string{return Array.from(text)[Symbol.iterator] && Array.from(text).slice(start,end).join('');}
export function extractCandidateSpans(text:string,documentHash=contentHash(text)):CandidateSpan[]{
  const points=Array.from(text.normalize('NFC')); const normalized=points.join(''); const tokens:Array<{text:string;start:number;end:number}>=[];
  for(const match of normalized.matchAll(word)){const utf16=match.index!;const start=Array.from(normalized.slice(0,utf16)).length;tokens.push({text:match[0],start,end:start+Array.from(match[0]).length});}
  const spans:CandidateSpan[]=[];
  for(let i=0;i<tokens.length;i++)for(let n=1;n<=5&&i+n<=tokens.length;n++){
    const selected=tokens.slice(i,i+n);const literal=points.slice(selected[0].start,selected.at(-1)!.end).join('');
    const canonical=literal.normalize('NFKC').toLocaleLowerCase('und').replace(/\s+/g,' ').trim();
    spans.push({literal,normalized:canonical,startOffset:selected[0].start,endOffset:selected.at(-1)!.end,ngramSize:n,occurrenceKey:sha(`${documentHash}|${EXTRACTOR_VERSION}|${selected[0].start}|${selected.at(-1)!.end}|${canonical}`)});
  } return spans;
}
export function retentionDisposition(input:{now:string;expiresAt:string|null;deletedAt:string|null}):'RETAINED'|'EXPIRED'|'DELETED'{if(input.deletedAt)return 'DELETED';return input.expiresAt&&new Date(input.expiresAt)<=new Date(input.now)?'EXPIRED':'RETAINED';}
export type HarvestLineage='AUTONOMOUS'|'HUMAN_APPROVED'|'MANUAL_UNAPPROVED'|'LEGACY';
export async function enqueueTermHarvest(input:{channelId:string;text:string;lineage:HarvestLineage;entityClusterKey?:string;observedAt?:string;approved?:boolean}):Promise<{queued:boolean;reason?:string}> {
  const clean=input.text.normalize('NFC').trim();if(!clean)return {queued:false,reason:'EMPTY_DOCUMENT'};
  const eligible=input.lineage==='AUTONOMOUS'||(input.lineage==='HUMAN_APPROVED'&&input.approved===true);if(!eligible)return {queued:false,reason:'LINEAGE_NOT_APPROVED'};
  const hash=contentHash(clean);await enqueueJob('TERM_HARVEST',{payloadSchemaVersion:1,channelId:input.channelId,text:clean,contentHash:hash,lineage:input.lineage,entityClusterKey:input.entityClusterKey||input.channelId,observedAt:input.observedAt||new Date().toISOString(),extractorVersion:EXTRACTOR_VERSION},{priority:5,maxAttempts:3,idempotencyKey:`term-harvest:${hash}:${EXTRACTOR_VERSION}`});return {queued:true};
}
export async function processTermHarvestJob(job:{id:string;payload:any}):Promise<void>{
  const p=job.payload;if(p.payloadSchemaVersion!==1||p.extractorVersion!==EXTRACTOR_VERSION)throw new Error('Unsupported TERM_HARVEST payload version.');
  if(contentHash(String(p.text))!==p.contentHash)throw new Error('TERM_HARVEST content hash mismatch.');const spans=extractCandidateSpans(p.text,p.contentHash);const db=await getDb();const client=await db.connect();
  try{await client.query('BEGIN');const control=await client.query('SELECT * FROM corpus_controls WHERE singleton=true');if(!control.rowCount||control.rows[0].paused)throw new Error('TERM_HARVEST is paused.');
    const consumed=await client.query(`SELECT count(*)::int n FROM corpus_extraction_runs WHERE completed_at>=date_trunc('day',now())`);if(consumed.rows[0].n>=control.rows[0].daily_compute_documents)throw new Error('TERM_HARVEST daily compute budget is exhausted.');
    const artifact=await client.query(`WITH inserted AS (INSERT INTO corpus_source_artifacts(source_type,source_key,creator_channel_id,discovery_lineage,entity_cluster_key,observed_at,policy_version) VALUES('CHANNEL_METADATA',$1,$1,$2,$3,$4,$5) ON CONFLICT(source_type,source_key,observed_at) DO NOTHING RETURNING id) SELECT id FROM inserted UNION ALL SELECT id FROM corpus_source_artifacts WHERE source_type='CHANNEL_METADATA' AND source_key=$1 AND observed_at=$4 LIMIT 1`,[p.channelId,p.lineage,p.entityClusterKey,p.observedAt,CORPUS_POLICY_VERSION]);
    const document=await client.query(`INSERT INTO corpus_documents(artifact_id,document_kind,content_hash,retained_excerpt,retention_class,extractor_eligible,retention_expires_at) VALUES($1,'CHANNEL_METADATA',$2,$3,'MINIMAL_EXCERPT',true,now()+interval '90 days') ON CONFLICT(content_hash,document_kind) DO UPDATE SET content_hash=excluded.content_hash RETURNING id`,[artifact.rows[0].id,p.contentHash,String(p.text).slice(0,8000)]);const documentId=document.rows[0].id;
    const window=new Date(p.observedAt);window.setUTCHours(0,0,0,0);const used=await client.query(`SELECT count(*)::int n FROM corpus_qualification_decisions WHERE entity_cluster_key=$1 AND window_start=$2 AND decision='QUALIFIED'`,[p.entityClusterKey,window.toISOString()]);const qualified=used.rows[0].n<control.rows[0].cluster_window_cap;
    await client.query(`INSERT INTO corpus_qualification_decisions(document_id,decision,reason_codes,policy_version,entity_cluster_key,window_start,idempotency_key) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(idempotency_key) DO NOTHING`,[documentId,qualified?'QUALIFIED':'CAPPED',JSON.stringify([qualified?'ELIGIBLE_CONFIRMED_CREATOR':'ENTITY_CLUSTER_WINDOW_CAP']),CORPUS_POLICY_VERSION,p.entityClusterKey,window.toISOString(),`qualify:${documentId}:${CORPUS_POLICY_VERSION}`]);
    const run=await client.query(`INSERT INTO corpus_extraction_runs(document_id,extractor_version,status,token_count,candidate_count) VALUES($1,$2,$3,$4,$5) ON CONFLICT(document_id,extractor_version) DO NOTHING RETURNING id`,[documentId,EXTRACTOR_VERSION,qualified?'COMPLETED':'REJECTED',spans.length?Math.max(...spans.map(s=>s.ngramSize)):0,qualified?spans.length:0]);
    if(run.rowCount&&qualified)for(const s of spans)await client.query(`INSERT INTO corpus_candidate_occurrences(extraction_run_id,document_id,literal_span,normalized_span,start_offset,end_offset,ngram_size,occurrence_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(occurrence_key) DO NOTHING`,[run.rows[0].id,documentId,s.literal,s.normalized,s.startOffset,s.endOffset,s.ngramSize,s.occurrenceKey]);
    await client.query('COMMIT');await completeJob(job.id);
  }catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}
export async function inspectCorpus(limit=100):Promise<unknown>{const db=await getDb();const docs=await db.query(`SELECT d.id,d.document_kind,d.content_hash,d.retention_class,d.offset_scheme,d.extractor_eligible,d.retention_expires_at,d.deleted_at,a.source_type,a.source_key,a.discovery_lineage,a.entity_cluster_key,a.observed_at FROM corpus_documents d JOIN corpus_source_artifacts a ON a.id=d.artifact_id ORDER BY d.created_at DESC LIMIT $1`,[Math.min(500,Math.max(1,limit))]);const counts=await db.query(`SELECT (SELECT count(*) FROM corpus_documents) documents,(SELECT count(*) FROM corpus_candidate_occurrences) occurrences,(SELECT count(*) FROM corpus_extraction_runs) extraction_runs`);return {mode:'SHADOW',activationEnabled:false,policyVersion:CORPUS_POLICY_VERSION,extractorVersion:EXTRACTOR_VERSION,offsetScheme:OFFSET_SCHEME,counts:counts.rows[0],documents:docs.rows};}
export async function inspectDocument(id:string):Promise<unknown>{const db=await getDb();const d=await db.query(`SELECT d.*,a.source_type,a.source_key,a.discovery_lineage,a.entity_cluster_key,a.observed_at FROM corpus_documents d JOIN corpus_source_artifacts a ON a.id=d.artifact_id WHERE d.id=$1`,[id]);if(!d.rowCount)throw new Error('Corpus document not found.');const c=await db.query(`SELECT literal_span,normalized_span,start_offset,end_offset,ngram_size,occurrence_key FROM corpus_candidate_occurrences WHERE document_id=$1 ORDER BY start_offset,end_offset`,[id]);return {...d.rows[0],candidates:c.rows};}
export async function applyRetentionDeletion(id:string,reason:string):Promise<boolean>{if(!reason.trim())throw new Error('Deletion reason is required.');const db=await getDb();const client=await db.connect();try{await client.query('BEGIN');const changed=await client.query(`UPDATE corpus_documents SET retained_excerpt=NULL,extractor_eligible=false,deleted_at=COALESCE(deleted_at,now()),deletion_reason=COALESCE(deletion_reason,$2) WHERE id=$1 AND deleted_at IS NULL RETURNING artifact_id`,[id,reason.trim()]);if(changed.rowCount)await client.query(`INSERT INTO corpus_qualification_decisions(document_id,decision,reason_codes,policy_version,entity_cluster_key,window_start,idempotency_key) SELECT d.id,'DELETED','["RETENTION_POLICY"]'::jsonb,$2,a.entity_cluster_key,date_trunc('day',now()),'delete:'||d.id::text FROM corpus_documents d JOIN corpus_source_artifacts a ON a.id=d.artifact_id WHERE d.id=$1 ON CONFLICT(idempotency_key) DO NOTHING`,[id,CORPUS_POLICY_VERSION]);await client.query('COMMIT');return !!changed.rowCount;}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
