import { randomUUID } from 'node:crypto';
import { getDb } from './db';
import { checksum } from './offlineEvaluation';

export type LifecycleState='CANDIDATE'|'ELIGIBLE'|'PROVEN'|'STALE'|'SATURATED'|'HARMFUL'|'INVALID';
const transitions:Record<LifecycleState,ReadonlySet<LifecycleState>>={
 CANDIDATE:new Set(['ELIGIBLE','INVALID']),ELIGIBLE:new Set(['PROVEN','STALE','HARMFUL','INVALID']),
 PROVEN:new Set(['STALE','SATURATED','HARMFUL','INVALID']),STALE:new Set(['ELIGIBLE','INVALID']),
 SATURATED:new Set(['ELIGIBLE','STALE','INVALID']),HARMFUL:new Set(['ELIGIBLE','INVALID']),INVALID:new Set()
};
export function canTransition(from:LifecycleState,to:LifecycleState){return transitions[from].has(to);}
export function assertLifecycleTransition(input:{from:LifecycleState;to:LifecycleState;now:Date;cooldownUntil?:Date|null;manualOverride?:boolean}){
 if(!canTransition(input.from,input.to))throw new Error('LIFECYCLE_TRANSITION_NOT_ALLOWED');
 if(!input.manualOverride&&input.cooldownUntil&&input.cooldownUntil>input.now)throw new Error('LIFECYCLE_COOLDOWN_ACTIVE');
}
export function reconstructCatalogChecksum(entries:Array<{ordinal:number;country:string;locale:string;lane:string;candidateKey:string;surfaceText:string;origin:string;querySpec:unknown}>){return checksum([...entries].sort((a,b)=>a.ordinal-b.ordinal));}
export function selectCatalogEntry<T extends {country:string;locale:string;lane:string;ordinal:number}>(entries:T[],scope:{country:string;locale:string;lane:string}){return entries.filter(e=>e.country===scope.country&&e.locale===scope.locale&&e.lane===scope.lane).sort((a,b)=>a.ordinal-b.ordinal)[0]??null;}

export async function stageCatalog(input:{sourceCatalogId:string;policyVersion:string;curatedShareBasisPoints:number;actor:string}){
 if(input.curatedShareBasisPoints<9500||input.curatedShareBasisPoints>10000)throw new Error('CURATED_FLOOR_VIOLATION');
 const db=await getDb(),client=await db.connect();try{await client.query('BEGIN');
  const source=await client.query(`SELECT * FROM candidate_catalogs WHERE id=$1 AND status='REVIEWED' FOR SHARE`,[input.sourceCatalogId]);if(!source.rowCount)throw new Error('CATALOG_NOT_REVIEWED');
  const rows=await client.query(`SELECT e.ordinal,e.country,'und' locale,e.lane,e.candidate_key "candidateKey",COALESCE(s.literal,e.candidate_key) "surfaceText",e.entry_checksum
    FROM candidate_catalog_entries e LEFT JOIN candidate_evaluation_results r ON r.id=e.evaluation_result_id LEFT JOIN term_surfaces s ON s.id=r.surface_id
    WHERE e.catalog_id=$1 ORDER BY e.ordinal`,[input.sourceCatalogId]);
  const entries=rows.rows.map(r=>({...r,origin:'PROVEN_CANDIDATE',querySpec:{term:r.surfaceText}}));const sum=reconstructCatalogChecksum(entries);
  const created=await client.query(`INSERT INTO serving_catalog_versions(source_catalog_id,version,checksum,policy_version,kind,curated_share_basis_points,created_by)
    VALUES($1,COALESCE((SELECT max(version)+1 FROM serving_catalog_versions),1),$2,$3,'CANDIDATE',$4,$5) ON CONFLICT(checksum) DO UPDATE SET checksum=excluded.checksum RETURNING *`,[input.sourceCatalogId,sum,input.policyVersion,input.curatedShareBasisPoints,input.actor]);
  for(const e of entries){await client.query(`INSERT INTO serving_catalog_entries(catalog_version_id,ordinal,country,locale,lane,candidate_key,surface_text,query_spec,origin,entry_checksum) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT DO NOTHING`,[created.rows[0].id,e.ordinal,e.country,e.locale,e.lane,e.candidateKey,e.surfaceText,JSON.stringify(e.querySpec),e.origin,e.entry_checksum]);await client.query(`INSERT INTO catalog_lifecycle_heads(lifecycle_key,state) VALUES($1,'CANDIDATE') ON CONFLICT DO NOTHING`,[`${e.country}\u001f${e.locale}\u001f${e.lane}\u001f${e.candidateKey}`]);}
  await client.query('COMMIT');return created.rows[0];
 }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}
export async function approveCatalog(input:{catalogVersionId:string;expectedStatus:'DRAFT';idempotencyKey:string;actor:string;reason:string}){if(!input.idempotencyKey||!input.reason)throw new Error('idempotencyKey and reason are required.');const db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const prior=await client.query('SELECT * FROM catalog_publication_approvals_v2 WHERE idempotency_key=$1',[input.idempotencyKey]);if(prior.rowCount){await client.query('COMMIT');return prior.rows[0];}const row=await client.query('SELECT status FROM serving_catalog_versions WHERE id=$1 FOR UPDATE',[input.catalogVersionId]);if(!row.rowCount||row.rows[0].status!==input.expectedStatus)throw new Error('CATALOG_VERSION_CONFLICT');const saved=await client.query(`INSERT INTO catalog_publication_approvals_v2(id,catalog_version_id,idempotency_key,expected_status,actor,reason) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[randomUUID(),input.catalogVersionId,input.idempotencyKey,input.expectedStatus,input.actor,input.reason]);await client.query(`UPDATE serving_catalog_versions SET status='APPROVED' WHERE id=$1`,[input.catalogVersionId]);await client.query('COMMIT');return saved.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function publishCatalog(input:{catalogVersionId:string;scope:{country:string;locale:string;lane:string};expectedPointerVersion:number;idempotencyKey:string;actor:string;reason:string;action?:'PUBLISH'|'ROLLBACK'}){if(!input.idempotencyKey||!input.reason)throw new Error('idempotencyKey and reason are required.');const scopeKey=`${input.scope.country}\u001f${input.scope.locale}\u001f${input.scope.lane}`,db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const prior=await client.query('SELECT * FROM catalog_publication_events WHERE idempotency_key=$1',[input.idempotencyKey]);if(prior.rowCount){await client.query('COMMIT');return prior.rows[0];}const target=await client.query(`SELECT * FROM serving_catalog_versions WHERE id=$1 FOR UPDATE`,[input.catalogVersionId]);const count=await client.query(`SELECT COUNT(*)::int entry_count,COUNT(*) FILTER(WHERE e.origin='PROVEN_CANDIDATE' AND h.state IS DISTINCT FROM 'PROVEN')::int unproven FROM serving_catalog_entries e LEFT JOIN catalog_lifecycle_heads h ON h.lifecycle_key=e.country||chr(31)||e.locale||chr(31)||e.lane||chr(31)||e.candidate_key WHERE e.catalog_version_id=$1 AND e.country=$2 AND e.locale=$3 AND e.lane=$4`,[input.catalogVersionId,input.scope.country,input.scope.locale,input.scope.lane]);if(!target.rowCount||target.rows[0].status!=='APPROVED'||!count.rows[0].entry_count||count.rows[0].unproven)throw new Error('CATALOG_NOT_SERVABLE');const pointer=await client.query('SELECT * FROM active_catalog_pointers WHERE scope_key=$1 FOR UPDATE',[scopeKey]);const current=pointer.rows[0],version=current?.pointer_version??0;if(version!==input.expectedPointerVersion)throw new Error('CATALOG_POINTER_CONFLICT');const next=version+1;await client.query(`INSERT INTO active_catalog_pointers(scope_key,country,locale,lane,catalog_version_id,pointer_version) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(scope_key) DO UPDATE SET catalog_version_id=excluded.catalog_version_id,pointer_version=excluded.pointer_version,updated_at=now()`,[scopeKey,input.scope.country,input.scope.locale,input.scope.lane,input.catalogVersionId,next]);const event=await client.query(`INSERT INTO catalog_publication_events(id,idempotency_key,scope_key,from_catalog_version_id,to_catalog_version_id,from_pointer_version,to_pointer_version,action,checksum,actor,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[randomUUID(),input.idempotencyKey,scopeKey,current?.catalog_version_id??null,input.catalogVersionId,version,next,input.action??'PUBLISH',target.rows[0].checksum,input.actor,input.reason]);await client.query('COMMIT');return event.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function getActiveCatalogPin(country:string,locale='und',lane='SEARCH'){const db=await getDb();const row=await db.query(`SELECT p.catalog_version_id "catalogVersionId",p.pointer_version "pointerVersion",v.policy_version "policyVersion",v.checksum FROM active_catalog_pointers p JOIN serving_catalog_versions v ON v.id=p.catalog_version_id WHERE p.country=$1 AND p.locale=$2 AND p.lane=$3`,[country,locale,lane]);return row.rows[0]??null;}
export async function transitionLifecycle(input:{lifecycleKey:string;to:LifecycleState;expectedVersion:number;policyVersion:string;evidenceChecksum:string;cooldownUntil?:string;idempotencyKey:string;actor:string;reason:string;manualOverride?:boolean}){if(!input.idempotencyKey||!input.reason||!input.evidenceChecksum)throw new Error('idempotencyKey, reason, and evidenceChecksum are required.');const db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const prior=await client.query('SELECT * FROM catalog_lifecycle_transitions WHERE idempotency_key=$1',[input.idempotencyKey]);if(prior.rowCount){await client.query('COMMIT');return prior.rows[0];}const head=await client.query('SELECT * FROM catalog_lifecycle_heads WHERE lifecycle_key=$1 FOR UPDATE',[input.lifecycleKey]);const current=head.rows[0];if(!current||current.version!==input.expectedVersion)throw new Error('LIFECYCLE_VERSION_CONFLICT');assertLifecycleTransition({from:current.state,to:input.to,now:new Date(),cooldownUntil:current.cooldown_until?new Date(current.cooldown_until):null,manualOverride:input.manualOverride});const id=randomUUID();const event=await client.query(`INSERT INTO catalog_lifecycle_transitions(id,lifecycle_key,idempotency_key,from_state,to_state,policy_version,evidence_checksum,cooldown_until,actor,reason) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id,input.lifecycleKey,input.idempotencyKey,current.state,input.to,input.policyVersion,input.evidenceChecksum,input.cooldownUntil||null,input.actor,input.reason]);await client.query(`UPDATE catalog_lifecycle_heads SET state=$1,version=version+1,cooldown_until=$2,last_transition_id=$3,updated_at=now() WHERE lifecycle_key=$4`,[input.to,input.cooldownUntil||null,id,input.lifecycleKey]);if(input.manualOverride)await client.query(`INSERT INTO catalog_manual_overrides(lifecycle_key,idempotency_key,forced_state,expected_version,actor,reason) VALUES($1,$2,$3,$4,$5,$6)`,[input.lifecycleKey,`${input.idempotencyKey}:override`,input.to,input.expectedVersion,input.actor,input.reason]);await client.query('COMMIT');return event.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function inspectCatalogs(limit=100){const db=await getDb(),n=Math.min(500,Math.max(1,limit));const [versions,pointers,events,lifecycle]=await Promise.all([db.query('SELECT * FROM serving_catalog_versions ORDER BY version DESC LIMIT $1',[n]),db.query(`SELECT p.*,v.checksum,v.policy_version FROM active_catalog_pointers p JOIN serving_catalog_versions v ON v.id=p.catalog_version_id ORDER BY p.scope_key`),db.query('SELECT * FROM catalog_publication_events ORDER BY occurred_at DESC LIMIT $1',[n]),db.query('SELECT * FROM catalog_lifecycle_heads ORDER BY lifecycle_key LIMIT $1',[n])]);return {servingDependency:'IMMUTABLE_COMPACT_CATALOG',graphOnOnlinePath:false,fallback:'LAST_KNOWN_GOOD_CURATED',versions:versions.rows,activePointers:pointers.rows,events:events.rows,lifecycle:lifecycle.rows};}
