import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateContinuation } from './continuationPolicy';

const base = { pageNumber:1,maxPages:3,hasNextPage:true,distinctCreators:10,cumulativeDistinctCreators:10,newCreators:8,confirmedCreators:5,qualityConfirmedCreators:3,countryPrecision:.9,communityDiversity:.4,duplicateRatio:.1,consecutiveLowYieldPages:0,maxConsecutiveLowYieldPages:2 };
test('continues a productive page with explainable utility',()=>{const d=evaluateContinuation(base);assert.equal(d.shouldContinue,true);assert.equal(d.lowYield,false);assert.equal(d.primaryReason,'CONTINUE_PRODUCTIVE');assert.ok(d.marginalUtility>.2);});
test('allows one exploratory low-yield page with novel creators but stops consecutive low yield',()=>{const first=evaluateContinuation({...base,confirmedCreators:0,qualityConfirmedCreators:0,newCreators:1});assert.equal(first.shouldContinue,true);assert.equal(first.lowYield,true);assert.equal(first.reasonCodes.includes('ZERO_CONFIRMED_VALUE'),false);const second=evaluateContinuation({...base,confirmedCreators:0,qualityConfirmedCreators:0,newCreators:1,consecutiveLowYieldPages:1});assert.equal(second.shouldContinue,false);assert.equal(second.primaryReason,'CONSECUTIVE_LOW_YIELD');});
test('reports duplicate-heavy and wrong-country pages',()=>{const d=evaluateContinuation({...base,duplicateRatio:.9,countryPrecision:.2});assert.ok(d.reasonCodes.includes('DUPLICATE_HEAVY'));assert.ok(d.reasonCodes.includes('WRONG_COUNTRY'));});
test('honors token and safety ceilings deterministically',()=>{assert.equal(evaluateContinuation({...base,hasNextPage:false}).primaryReason,'NO_NEXT_PAGE');assert.equal(evaluateContinuation({...base,pageNumber:3}).primaryReason,'PAGE_CEILING');assert.deepEqual(evaluateContinuation(base),evaluateContinuation(base));});
test('deep adaptive ceiling allows productive page 3 to continue and stops at page 10',()=>{const deep={...base,maxPages:10};const page3=evaluateContinuation({...deep,pageNumber:3});assert.equal(page3.shouldContinue,true);assert.equal(page3.primaryReason,'CONTINUE_PRODUCTIVE');const page10=evaluateContinuation({...deep,pageNumber:10});assert.equal(page10.shouldContinue,false);assert.equal(page10.primaryReason,'PAGE_CEILING');});
