import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { applyIsotonic, assignEvaluationCohort, benchmarkDecisions, decidePromotion, fitBinnedIsotonic, type LabeledDecision, type SamplingPolicy } from './decisionEvaluation';

const policy:SamplingPolicy={policyKey:'audit',version:1,salt:'stable-test-salt',protectedAuditBasisPoints:1000,targetedAuditBasisPoints:1000};
test('cohort assignment is deterministic and carries a known inclusion probability',()=>{
  const stratum={country:'GLOBAL',language:'und',script:'UNKNOWN',evidenceBand:'SPARSE',providerState:'AVAILABLE',discoveryOrigin:'AUTONOMOUS'};
  const first=assignEvaluationCohort('channel:one',stratum,policy),second=assignEvaluationCohort('channel:one',stratum,policy);
  assert.deepEqual(first,second);assert.match(first.assignmentKey,/^[a-f0-9]{64}$/);assert.ok(first.inclusionBasisPoints>=0&&first.inclusionBasisPoints<=10000);if(first.cohort!=='NOT_SELECTED')assert.equal(first.inclusionBasisPoints,2000);
});
test('invalid sampling allocations fail closed',()=>assert.throws(()=>assignEvaluationCohort('x',{country:'GLOBAL',language:'und',script:'UNKNOWN',evidenceBand:'SPARSE',providerState:'AVAILABLE',discoveryOrigin:'AUTO'},{...policy,protectedAuditBasisPoints:9000,targetedAuditBasisPoints:2000}),/cannot exceed/));

function examples(n:number,predicted:'TRADING_CONFIRMED'|'NON_TRADING'|'UNCERTAIN'='TRADING_CONFIRMED',truth:'TRADING_CONFIRMED'|'NON_TRADING'='TRADING_CONFIRMED'):LabeledDecision[]{return Array.from({length:n},(_,i)=>({key:String(i),truth,predicted,score:predicted==='TRADING_CONFIRMED'?.9:.1,inclusionProbability:.1,segment:{language:'en'}}));}
test('benchmark reports weighted calibration, effective sample size, and confidence bounds',()=>{const result=benchmarkDecisions([...examples(50),...examples(5,'TRADING_CONFIRMED','NON_TRADING')],30);assert.equal(result.metrics.sampleSize,55);assert.ok(result.metrics.precision!<1);assert.ok(result.intervals.precision?.lower!<result.metrics.precision!);assert.deepEqual(result.reasonCodes,[]);assert.equal(result.calibration.bins.length,10);});
test('isotonic calibration is monotone and fitted only from labeled probabilities',()=>{const rows:LabeledDecision[]=[{key:'a',truth:'TRADING_CONFIRMED',predicted:'TRADING_CONFIRMED',score:.1,inclusionProbability:1},{key:'b',truth:'NON_TRADING',predicted:'TRADING_CONFIRMED',score:.2,inclusionProbability:1},{key:'c',truth:'TRADING_CONFIRMED',predicted:'TRADING_CONFIRMED',score:.8,inclusionProbability:1},{key:'d',truth:'TRADING_CONFIRMED',predicted:'TRADING_CONFIRMED',score:.9,inclusionProbability:1}],points=fitBinnedIsotonic(rows);for(let i=1;i<points.length;i++)assert.ok(points[i].probability>=points[i-1].probability);assert.ok(applyIsotonic(.85,points)>=applyIsotonic(.15,points));});
test('promotion gates reject precision regressions and abstain on inadequate evidence',()=>{const baseline=benchmarkDecisions(examples(60),30),bad=benchmarkDecisions([...examples(20),...examples(40,'TRADING_CONFIRMED','NON_TRADING')],30),small=benchmarkDecisions(examples(5),30);const gate={minimumEffectiveSampleSize:30,minimumPrecisionLowerBound:.8,maximumRecallRegression:.02,maximumAbstentionIncrease:.02,maximumBrierRegression:.02,requiredSegments:[]};assert.equal(decidePromotion(baseline,bad,gate).decision,'REJECT');assert.ok(decidePromotion(baseline,bad,gate).reasonCodes.includes('PRECISION_LOWER_BOUND'));assert.equal(decidePromotion(baseline,small,gate).decision,'INSUFFICIENT_EVIDENCE');});
test('evaluation schema is additive, immutable, propensity-aware, and cannot activate serving',()=>{const migration=readFileSync(new URL('./db/migrations/037_decision_evaluation_control_plane.sql',import.meta.url),'utf8'),module=readFileSync(new URL('./decisionEvaluation.ts',import.meta.url),'utf8');for(const table of ['evaluation_cohort_assignments','evaluation_ground_truth_labels','decision_evaluation_datasets','decision_evaluation_examples','decision_benchmark_runs','calibration_artifacts','decision_promotion_gates'])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(migration,/decision_evaluation_sampling_enabled','false'/);assert.match(migration,/reject_immutable_event_mutation/);assert.match(module,/servingAuthority:false,automaticPromotion:false/);assert.doesNotMatch(module,/UPDATE\s+(evaluation_|decision_)/i);});
test('authoritative review commits before the evaluation observer and does not await it',()=>{const reviews=readFileSync(new URL('./reviewStore.ts',import.meta.url),'utf8'),commit=reviews.indexOf("await client.query('COMMIT')"),observer=reviews.indexOf('void recordEvaluationGroundTruth');assert.ok(commit>=0&&observer>commit);assert.doesNotMatch(reviews,/await recordEvaluationGroundTruth/);});
