import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { assessEntityResolution, collapseSourceIndependentObservations, deterministicUuid, normalizeIdentifier, sourceFamilyIdentity } from './entityResolution';
import { evaluateClassificationStages } from './evidenceEngine/stagedClassification';

test('identifier normalization is Unicode-safe, namespace-aware, and strips tracking identity',()=>{assert.equal(normalizeIdentifier('YOUTUBE_CHANNEL_ID',' UC_AbC '),'UC_AbC');assert.equal(normalizeIdentifier('DOMAIN','https://www.BÜCHER.de/path'),'xn--bcher-kva.de');assert.equal(normalizeIdentifier('CANONICAL_URL','https://Example.com/path/?utm_source=x&id=1#frag'),'https://example.com/path?id=1');assert.equal(deterministicUuid('channel','abc'),deterministicUuid('channel','abc'));});
test('source families collapse explicit syndication and identical content without language assumptions',()=>{const a=sourceFamilyIdentity({provider:'web',syndicationId:'wire:42'}),b=sourceFamilyIdentity({provider:'web',syndicationId:'wire:42'}),c=sourceFamilyIdentity({provider:'web',contentHash:'sha256:other'});assert.equal(a.familyId,b.familyId);assert.notEqual(a.familyId,c.familyId);});
test('entity resolution abstains on conflict and never auto-merges multisource identities',()=>{const conflict=assessEntityResolution({nativeIdentifier:false,matches:[{entityId:'a',sourceFamilyId:'f1',sourceEntityId:'s1',approved:true},{entityId:'b',sourceFamilyId:'f2',sourceEntityId:'s2',approved:true}]});assert.equal(conflict.disposition,'ABSTAIN_CONFLICT');assert.equal(conflict.entityId,null);const proposal=assessEntityResolution({nativeIdentifier:false,matches:[{entityId:'a',sourceFamilyId:'f1',sourceEntityId:'s1',approved:true},{entityId:'a',sourceFamilyId:'f2',sourceEntityId:'s2',approved:true}]});assert.equal(proposal.disposition,'PROPOSE_LINK');assert.equal(proposal.entityId,'a');});
test('correlated observations count once while independent documents remain distinct',()=>{const result=collapseSourceIndependentObservations([{observationId:'one',sourceFamilyId:'wire',sourceEntityId:'publisher'},{observationId:'copy',sourceFamilyId:'wire',sourceEntityId:'republisher'},{observationId:'native',sourceFamilyId:'native',sourceEntityId:'creator'}]);assert.equal(result.independentFamilyCount,2);assert.equal(result.independentEntityCount,3);assert.deepEqual(result.families.find(f=>f.familyId==='wire')?.observationIds,['copy','one']);});
test('classification cannot manufacture corroboration from two emissions in one source family',()=>{const evidence:any[]=[{id:'a',source:'channel_metadata',polarity:'POSITIVE',category:'INSTRUMENT',rawMatches:['x'],reliability:'HIGH',finalWeight:10,provenance:{fields:[{field:'channel_bio',sourceId:'bio',sourceFamilyId:'same'}]}},{id:'b',source:'gemini_semantic',polarity:'POSITIVE',category:'METHODOLOGY_CONCEPT',rawMatches:['y'],reliability:'MEDIUM',finalWeight:10,provenance:{fields:[{field:'video_title',sourceId:'copy',sourceFamilyId:'same'}]}}],collection:any={sufficiency:'SUFFICIENT',sparseMetadata:false,degraded:false,fieldsPresent:['channel_bio','video_title'],reasonCodes:[],providers:[]},report=evaluateClassificationStages({channel_name:'x',description:'y'},evidence,collection),corroboration=report.stages.find(stage=>stage.stage==='CORROBORATION')!;assert.equal(corroboration.disposition,'ABSTAIN');assert.deepEqual(corroboration.reasonCodes,['SOURCE_FAMILY_INDEPENDENCE_REQUIRED']);assert.equal(corroboration.metrics.sourceFamilies,1);});
test('classification accepts attributable evidence from two independent source families',()=>{const evidence:any[]=[{id:'a',source:'channel_metadata',polarity:'POSITIVE',category:'INSTRUMENT',rawMatches:['x'],reliability:'HIGH',finalWeight:10,provenance:{fields:[{field:'channel_bio',sourceId:'bio',sourceFamilyId:'native'}]}},{id:'b',source:'gemini_semantic',polarity:'POSITIVE',category:'METHODOLOGY_CONCEPT',rawMatches:['y'],reliability:'MEDIUM',finalWeight:10,provenance:{fields:[{field:'video_title',sourceId:'video',sourceFamilyId:'video'}]}}],collection:any={sufficiency:'SUFFICIENT',sparseMetadata:false,degraded:false,fieldsPresent:['channel_bio','video_title'],reasonCodes:[],providers:[]},report=evaluateClassificationStages({channel_name:'x',description:'y'},evidence,collection),corroboration=report.stages.find(stage=>stage.stage==='CORROBORATION')!;assert.equal(corroboration.disposition,'PASS');assert.equal(corroboration.metrics.sourceFamilies,2);});
test('migration is additive, governed, immutable, and disables observations by default',()=>{const migration=readFileSync(new URL('./db/migrations/040_entity_resolution_source_independence.sql',import.meta.url),'utf8'),module=readFileSync(new URL('./entityResolution.ts',import.meta.url),'utf8');for(const table of ['canonical_entities','source_families','source_family_memberships','entity_identifier_observations','entity_bindings','entity_resolution_proposals','entity_resolution_decisions','entity_projection_events'])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(migration,/entity_observation_enabled','false'/);assert.match(migration,/idx_entity_binding_approved_identifier/);assert.match(migration,/reject_immutable_event_mutation/);assert.match(module,/automaticMerge:false/);});
