import test from 'node:test';
import assert from 'node:assert/strict';
import { aggregateOsintEvidence, buildExternalOsintProposal, isOsintSnapshotFresh, normalizeExternalObservation, runOsintAdapter, selectBoundedOsintEvidence, type ExternalOsintObservationInput } from './externalOsint';

const input=(sourceId:string,correlationKey:string,country='BR',surface='mini índice rompimento',observedAt='2026-08-19T00:00:00Z'):ExternalOsintObservationInput=>({sourceId,sourceFamily:sourceId==='publication'?'PUBLICATION':'PUBLIC_COMMUNITY',sourceUrl:`https://example.test/${sourceId}`,externalId:'post-1',fetchedAt:observedAt,observedAt,country,locale:'pt-BR',language:'pt',surface,extractionMethod:'dom-heading',extractionVersion:'v1',confidence:.9,reliability:.9,relevance:.9,supportingEvidence:{heading:surface},correlationKey});

test('exact observation replay has deterministic identity and preserves original surface',()=>{const a=normalizeExternalObservation(input('forum','thread-a'));const b=normalizeExternalObservation(input('forum','thread-a'));assert.equal(a.observationId,b.observationId);assert.equal(a.surface,'mini índice rompimento');assert.equal(a.canonicalConcept,'mini índice rompimento');});
test('correlated mirrors do not increase independence',()=>{const rows=[normalizeExternalObservation(input('forum','repost-1')),normalizeExternalObservation(input('publication','repost-1'))];const [aggregate]=aggregateOsintEvidence(rows,new Date('2026-08-20'));assert.equal(aggregate.independentSourceCount,1);assert.equal(aggregate.eligible,false);});
test('independent sources corroborate a concept',()=>{const rows=[normalizeExternalObservation(input('forum','thread-a')),normalizeExternalObservation(input('publication','article-b'))];const [aggregate]=aggregateOsintEvidence(rows,new Date('2026-08-20'));assert.equal(aggregate.independentSourceCount,2);assert.equal(aggregate.eligible,true);const proposal=buildExternalOsintProposal(aggregate,2);assert.equal(proposal.proposalFamily,'EXTERNAL_OSINT');assert.deepEqual(proposal.supportingEvidence.observationIds,rows.map(x=>x.observationId).sort());});
test('stale evidence abstains and Phase 8 freshness fails closed',()=>{const rows=[normalizeExternalObservation(input('forum','a','BR','mini índice rompimento','2025-01-01')),normalizeExternalObservation(input('publication','b','BR','mini índice rompimento','2025-01-02'))];assert.equal(aggregateOsintEvidence(rows,new Date('2026-08-20'))[0].eligible,false);assert.equal(isOsintSnapshotFresh({proposalFamily:'EXTERNAL_OSINT',supportingEvidence:{observationIds:['a','b'],expiresAt:'2026-01-01'}},new Date('2026-08-20')),false);});
test('bounded fair materialization enforces global, source and country caps',()=>{const aggregates=[];for(const country of ['BR','DE','JP'])for(let i=0;i<5;i++)aggregates.push({...aggregateOsintEvidence([normalizeExternalObservation(input(`forum-${country}-${i}`,`a-${i}`,country,`trading setup ${i}`)),normalizeExternalObservation(input(`publication-${country}-${i}`,`b-${i}`,country,`trading setup ${i}`))],new Date('2026-08-20'))[0],sourceFamilies:['PUBLIC_COMMUNITY' as const]});const chosen=selectBoundedOsintEvidence(aggregates,{global:5,perSourceFamily:4,perCountry:2});assert.equal(chosen.length,4);assert.ok(new Set(chosen.map(x=>x.country)).size>=2);assert.ok([...new Set(chosen.map(x=>x.country))].every(c=>chosen.filter(x=>x.country===c).length<=2));});
test('provider failure degrades without manufacturing negative evidence',async()=>{const result=await runOsintAdapter({sourceId:'dead',sourceFamily:'PUBLICATION',timeoutMs:10,maxRequests:1,maxCost:1,retry:{attempts:0,backoffMs:0},fetch:async()=>{throw new Error('offline')}});assert.equal(result.degraded,true);assert.deepEqual(result.observations,[]);});
test('untrusted input limits reject URLs and oversized surfaces',()=>{assert.throws(()=>normalizeExternalObservation({...input('forum','a'),sourceUrl:'javascript:alert(1)'}),/OSINT_INVALID_URL/);assert.throws(()=>normalizeExternalObservation({...input('forum','a'),surface:'x'.repeat(161)}),/OSINT_INVALID_SURFACE/);});
