import { completeJob, finishQuotaReservation, getAppSetting, getDailyYouTubeQuotaBudget, getDb, tryReserveQuota, type DurableJob } from './db';
import { FEATURED_CHANNEL_ADAPTER_POLICY_VERSION, FEATURED_CHANNEL_PROVIDER_COST, featuredChannelAdapterOutcome, validateFeaturedChannelPayload } from './featuredChannelAdapter';
import { fetchYouTubeFeaturedChannels, type DiscoveredChannelRaw } from './youtube';
import { recordNomination } from './candidateAdmission/store';

/** Executes one depth-one featured section request. It never creates frontier actions or follows returned channels. */
export async function processFeaturedChannelInspectionJob(job:DurableJob,ingest:(raw:DiscoveredChannelRaw,country:string,source:'automated_query')=>Promise<unknown>):Promise<void>{
 const payload=validateFeaturedChannelPayload(job.payload),db=await getDb(),state=await db.query(`SELECT f.*,c.mode adapter_mode,c.paused adapter_paused,c.kill_switch adapter_kill_switch,c.max_fanout,p.id program_id,authority.enabled creator_enabled,authority.kill_switch creator_kill_switch,authority.serving_authority_enabled,authority.featured_channel_authority_enabled,authority.featured_channel_rollout_basis_points FROM frontier_actions f JOIN research_programs p ON p.id=f.program_id JOIN acquisition_adapter_controls c ON c.adapter_type='INSPECT_FEATURED_CHANNELS' JOIN creator_search_canary_control authority ON authority.singleton=true JOIN entity_bindings b ON b.id=$2 AND b.namespace='YOUTUBE_CHANNEL_ID' AND b.normalized_value=$3 AND b.status='APPROVED' WHERE f.id=$1`,[payload.actionId,payload.sourceCanonicalEntityId,payload.sourceChannelId]),row=state.rows[0];
 if(!row||row.adapter_mode!=='CANARY'||row.adapter_paused||row.adapter_kill_switch||!row.creator_enabled||row.creator_kill_switch||!row.serving_authority_enabled||!row.featured_channel_authority_enabled||Number(row.featured_channel_rollout_basis_points)<=0||row.action_type!=='INSPECT_FEATURED_CHANNELS'||row.policy_version!==payload.policyVersion||String(row.normalized_target)!==`channel:${payload.sourceChannelId}`)throw new Error('FEATURED_CHANNEL_CANARY_POLICY_REJECTED');
 const budget=getDailyYouTubeQuotaBudget(),percent=Number(await getAppSetting('featured_channel_canary_quota_percent','1'));
 if(!await tryReserveQuota({operationType:'INSPECT_FEATURED_CHANNELS',operationId:payload.actionId,allocation:'AUTONOMOUS',units:FEATURED_CHANNEL_PROVIDER_COST,dailyBudget:budget,allocationPercent:percent}))throw new Error('FEATURED_CHANNEL_CANARY_GLOBAL_QUOTA_EXHAUSTED');
 try{const provider=await fetchYouTubeFeaturedChannels(payload.sourceChannelId,Math.min(payload.maximumFanout,Number(row.max_fanout))),requestIdentity=`featured-channels:${row.semantic_action_key}`,attributed={...provider,providerRequestIdentity:requestIdentity};
  for(const [index,item] of provider.observations.entries()){const raw:DiscoveredChannelRaw={channelId:item.featuredChannelId,channelName:item.featuredChannelId,youtubeUrl:`https://www.youtube.com/channel/${item.featuredChannelId}`,description:'',videoTitles:[],videoDescriptions:[],matchedDocument:{type:'EXTERNAL',providerNativeId:item.featuredChannelId,locator:`youtube:channel-section:${payload.sourceChannelId}:${item.sectionId}`},discoveryJobId:job.id};const nomination=await recordNomination({channelId:item.featuredChannelId,sourceType:'FEATURED_CHANNEL',sourceActionId:payload.actionId,jobId:job.id,query:payload.sourceChannelId,querySemanticClasses:['FEATURED_CHANNEL_SECTION'],queryGenerationMode:'GOVERNED_ADAPTER',country:payload.targetCountry,retrievalLane:'FEATURED_CHANNEL',resultRank:index+1,matchedDocument:raw.matchedDocument!,rawObservation:{sourceChannelId:payload.sourceChannelId,sectionId:item.sectionId,explicitProviderIdentity:true}},'INVESTIGATION_QUEUED');raw.nominationId=nomination.id||undefined;await ingest(raw,payload.targetCountry,'automated_query');}
  const client=await db.connect();try{await client.query('BEGIN');for(const item of provider.observations){const canonicalKey=`channel:${item.featuredChannelId}`,existing=await client.query(`SELECT id FROM evidence_nodes WHERE node_type='CHANNEL' AND canonical_key=$1`,[canonicalKey]),node=existing.rows[0]||await client.query(`INSERT INTO evidence_nodes(node_type,canonical_key,attributes,first_observed_at) VALUES('CHANNEL',$1,$2,$3) RETURNING id`,[canonicalKey,JSON.stringify({channelId:item.featuredChannelId}),provider.observationTimestamp]).then(r=>r.rows[0]);await client.query(`INSERT INTO evidence_program_visits(program_id,node_id,action_id,visit_key,depth,attribution_path,status,policy_version) VALUES($1,$2,$3,$4,1,$5,'VISITED',$6) ON CONFLICT(program_id,visit_key) DO NOTHING`,[row.program_id,node.id,payload.actionId,`${row.semantic_action_key}:${canonicalKey}`,JSON.stringify([payload.sourceCanonicalEntityId,item.featuredChannelId]),FEATURED_CHANNEL_ADAPTER_POLICY_VERSION]);}
   await client.query(`INSERT INTO acquisition_adapter_runs(adapter_type,action_id,job_id,program_id,semantic_action_key,status,quota_reserved,quota_consumed,provider_request_key,policy_version,payload_schema_version,observed_at,outcome) VALUES('INSPECT_FEATURED_CHANNELS',$1,$2,$3,$4,'SUCCEEDED',1,1,$5,$6,1,$7,$8) ON CONFLICT(adapter_type,action_id) DO NOTHING`,[payload.actionId,job.id,row.program_id,row.semantic_action_key,requestIdentity,FEATURED_CHANNEL_ADAPTER_POLICY_VERSION,provider.observationTimestamp,JSON.stringify(featuredChannelAdapterOutcome(attributed))]);await client.query(`UPDATE frontier_actions SET lifecycle='COMPLETED' WHERE id=$1`,[payload.actionId]);await client.query('COMMIT');}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
  await finishQuotaReservation('INSPECT_FEATURED_CHANNELS',payload.actionId,true);await completeJob(job.id);
 }catch(error){await finishQuotaReservation('INSPECT_FEATURED_CHANNELS',payload.actionId,false);throw error;}
}
