import {getAppSetting,getDb} from './db';
import {assessUtility,utilityChecksum,type UtilityAssessment} from './utilityContract';
import {assignVoiCanary} from './voiEvidenceController';
import type {CreatorFocusDecision} from './evidenceEngine/classifierV4';

export const GAP_SCHEDULER_POLICY_VERSION='gap-specific-investigation-v1';
export type InvestigationGap='CHANNEL_METADATA_MISSING'|'RECENT_DOCUMENT_COVERAGE_INSUFFICIENT'|'TEMPORAL_COVERAGE_INSUFFICIENT'|'INDEPENDENCE_MISSING'|'LANGUAGE_UNSUPPORTED'|'LANGUAGE_LOW_CONFIDENCE'|'IDENTITY_UNRESOLVED'|'ALTERNATIVE_FOCUS_AMBIGUOUS'|'TRADING_HYPOTHESIS_AMBIGUOUS'|'PROVIDER_TRANSIENT_FAILURE'|'PROVIDER_CONFIGURATION_UNAVAILABLE'|'QUOTA_DEFERRED'|'REVIEW_JUDGMENT_REQUIRED';
export type GapAction='HYDRATE_CHANNEL_ABOUT'|'FETCH_RECENT_VIDEO_SAMPLE'|'FETCH_TEMPORAL_VIDEO_SAMPLE'|'FETCH_VIDEO_DESCRIPTIONS'|'FETCH_PLAYLIST_SAMPLE'|'FETCH_TRANSCRIPT_EXCERPT'|'RESOLVE_LANGUAGE'|'RESOLVE_ENTITY'|'CLASSIFY_DOCUMENTS'|'ASSESS_CREATOR_FOCUS'|'RETRY_PROVIDER'|'WAIT_FOR_QUOTA'|'PREPARE_HUMAN_REVIEW';
export interface GapActionDefinition{action:GapAction;resolves:InvestigationGap[];providerCost:number;reviewCost:number;latencyMs:number;adapter:'ENRICH_STAGE_1'|'ENRICH_STAGE_2'|'REVIEW'|'DEFER'|'UNAVAILABLE'}
export const GAP_ACTIONS:GapActionDefinition[]=[
 {action:'HYDRATE_CHANNEL_ABOUT',resolves:['CHANNEL_METADATA_MISSING'],providerCost:1,reviewCost:0,latencyMs:1500,adapter:'ENRICH_STAGE_1'},
 {action:'FETCH_RECENT_VIDEO_SAMPLE',resolves:['RECENT_DOCUMENT_COVERAGE_INSUFFICIENT','INDEPENDENCE_MISSING'],providerCost:101,reviewCost:0,latencyMs:3000,adapter:'ENRICH_STAGE_1'},
 {action:'FETCH_TEMPORAL_VIDEO_SAMPLE',resolves:['TEMPORAL_COVERAGE_INSUFFICIENT'],providerCost:202,reviewCost:0,latencyMs:6000,adapter:'UNAVAILABLE'},
 {action:'FETCH_VIDEO_DESCRIPTIONS',resolves:['TRADING_HYPOTHESIS_AMBIGUOUS','ALTERNATIVE_FOCUS_AMBIGUOUS'],providerCost:1,reviewCost:0,latencyMs:2500,adapter:'ENRICH_STAGE_2'},
 {action:'FETCH_PLAYLIST_SAMPLE',resolves:['RECENT_DOCUMENT_COVERAGE_INSUFFICIENT'],providerCost:100,reviewCost:0,latencyMs:4000,adapter:'ENRICH_STAGE_2'},
 {action:'FETCH_TRANSCRIPT_EXCERPT',resolves:['TRADING_HYPOTHESIS_AMBIGUOUS','LANGUAGE_LOW_CONFIDENCE'],providerCost:1,reviewCost:0,latencyMs:4000,adapter:'UNAVAILABLE'},
 {action:'RESOLVE_LANGUAGE',resolves:['LANGUAGE_UNSUPPORTED','LANGUAGE_LOW_CONFIDENCE'],providerCost:0,reviewCost:0,latencyMs:2000,adapter:'UNAVAILABLE'},
 {action:'RESOLVE_ENTITY',resolves:['IDENTITY_UNRESOLVED'],providerCost:0,reviewCost:0,latencyMs:2000,adapter:'UNAVAILABLE'},
 {action:'CLASSIFY_DOCUMENTS',resolves:['TRADING_HYPOTHESIS_AMBIGUOUS'],providerCost:0,reviewCost:0,latencyMs:1000,adapter:'UNAVAILABLE'},
 {action:'ASSESS_CREATOR_FOCUS',resolves:['ALTERNATIVE_FOCUS_AMBIGUOUS'],providerCost:0,reviewCost:0,latencyMs:1000,adapter:'UNAVAILABLE'},
 {action:'RETRY_PROVIDER',resolves:['PROVIDER_TRANSIENT_FAILURE'],providerCost:0,reviewCost:0,latencyMs:3000,adapter:'UNAVAILABLE'},
 {action:'WAIT_FOR_QUOTA',resolves:['QUOTA_DEFERRED'],providerCost:0,reviewCost:0,latencyMs:0,adapter:'DEFER'},
 {action:'PREPARE_HUMAN_REVIEW',resolves:['REVIEW_JUDGMENT_REQUIRED'],providerCost:0,reviewCost:1,latencyMs:0,adapter:'REVIEW'}];
export function deriveInvestigationGaps(d:CreatorFocusDecision):InvestigationGap[]{const gaps=new Set<InvestigationGap>();for(const s of d.stages){for(const r of s.reasonCodes){if(r==='IDENTITY_UNRESOLVED')gaps.add('IDENTITY_UNRESOLVED');if(r==='LANGUAGE_UNSUPPORTED')gaps.add('LANGUAGE_UNSUPPORTED');if(r==='DOCUMENT_COVERAGE_INSUFFICIENT')gaps.add('RECENT_DOCUMENT_COVERAGE_INSUFFICIENT');if(r==='INDEPENDENT_FAMILIES_REQUIRED')gaps.add('INDEPENDENCE_MISSING');if(r==='TEMPORAL_RELEVANCE_INSUFFICIENT')gaps.add('TEMPORAL_COVERAGE_INSUFFICIENT');if(r==='TRADING_FOCUS_NOT_DOMINANT')gaps.add('TRADING_HYPOTHESIS_AMBIGUOUS');if(r==='DOMINANT_ALTERNATIVE_FOCUS')gaps.add('ALTERNATIVE_FOCUS_AMBIGUOUS');}}if(!gaps.size)gaps.add('REVIEW_JUDGMENT_REQUIRED');return [...gaps].sort();}
export function planGapSpecificAction(input:{decision:CreatorFocusDecision;providerQuotaRemaining:number;caseQuotaRemaining:number;deadlineRemainingMs:number;reviewCapacity:number}){const gaps=deriveInvestigationGaps(input.decision),assessments={} as Record<GapAction,UtilityAssessment>;for(const a of GAP_ACTIONS)assessments[a.action]=assessUtility({decisionResolution:.5,confirmationRecall:.4,precisionProtection:1,coverageGain:.5,informationGain:.5,providerCost:a.providerCost,reviewCost:a.reviewCost,latencyMs:a.latencyMs,operationalRisk:.1},{decisionResolution:10,confirmationRecall:8,precisionProtection:12,coverageGain:2,informationGain:5,providerCost:.025,reviewCost:25,latencyMs:.0002,operationalRisk:4},{countryAllowed:true,terminalPrecisionProtected:true,providerQuotaRemaining:input.providerQuotaRemaining,caseQuotaRemaining:input.caseQuotaRemaining,latencyRemainingMs:input.deadlineRemainingMs,reviewCapacityRemaining:input.reviewCapacity,governedAction:true,prerequisitesSatisfied:a.adapter!=='UNAVAILABLE'&&a.resolves.some(g=>gaps.includes(g))},{providerCost:a.providerCost,reviewCost:a.reviewCost,latencyMs:a.latencyMs});const feasible=GAP_ACTIONS.filter(a=>assessments[a.action].feasible).sort((a,b)=>(assessments[b.action].score||0)-(assessments[a.action].score||0)||a.action.localeCompare(b.action));const selected=feasible[0];return {gaps,assessments,selectedAction:selected?.action,adapter:selected?.adapter,reasonCodes:selected?[`SELECTED_${selected.action}`]:['NO_FEASIBLE_ACTION','OPERATIONALLY_BLOCKED'],policyVersion:GAP_SCHEDULER_POLICY_VERSION};}
export async function recordGapSpecificPlan(input:{channelId:string;diagnosticId?:string;creatorFocusSnapshotId?:string;decision:CreatorFocusDecision;providerQuotaRemaining:number;caseQuotaRemaining:number;deadlineRemainingMs:number;reviewCapacity:number}){const configured=String(await getAppSetting('gap_specific_scheduler_mode','OFF')).toUpperCase();if(configured==='OFF')return {enabled:false,servingAuthority:false};const mode:'SHADOW'|'CANARY'=configured==='CANARY'?'CANARY':'SHADOW',basis=Math.min(10000,Math.max(0,Number(await getAppSetting('gap_specific_scheduler_canary_basis_points','0'))||0)),assignment=assignVoiCanary(`${input.channelId}|${input.diagnosticId||input.decision.classifierVersion}|${GAP_SCHEDULER_POLICY_VERSION}`,basis),plan=planGapSpecificAction(input),controllerAssigned=mode==='CANARY'&&assignment.controllerAssigned,appliedAction=controllerAssigned?plan.selectedAction:undefined,deadlineAt=new Date(Date.now()+input.deadlineRemainingMs).toISOString(),unsigned={channelId:input.channelId,diagnosticId:input.diagnosticId,mode,...plan,appliedAction,controllerAssigned,basis,randomizationValue:assignment.randomizationValue};const planKey=utilityChecksum(unsigned),db=await getDb();await db.query(`INSERT INTO gap_specific_investigation_plans(plan_key,channel_id,classification_diagnostic_id,creator_focus_snapshot_id,mode,gaps,action_assessments,selected_action,applied_action,provider_quota_remaining,case_quota_remaining,deadline_at,policy_version,utility_contract_version,assignment_basis_points,randomization_value,controller_assigned,reason_codes,plan_checksum) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'utility-constraints-v1',$14,$15,$16,$17,$18) ON CONFLICT(plan_key) DO NOTHING`,[planKey,input.channelId,input.diagnosticId||null,input.creatorFocusSnapshotId||null,mode,JSON.stringify(plan.gaps),JSON.stringify(plan.assessments),plan.selectedAction||'NONE',appliedAction||null,input.providerQuotaRemaining,input.caseQuotaRemaining,deadlineAt,plan.policyVersion,basis,assignment.randomizationValue,controllerAssigned,JSON.stringify([...plan.reasonCodes,controllerAssigned?'CANARY_CONTROLLER_ASSIGNED':'LEGACY_CONTROL_PRESERVED']),utilityChecksum(unsigned)]);return {enabled:true,mode,...plan,appliedAction,controllerAssigned,servingAuthority:false};}
export async function inspectGapSpecificPlans(limit=100){const db=await getDb();const [mode,rows]=await Promise.all([getAppSetting('gap_specific_scheduler_mode','OFF'),db.query('SELECT * FROM gap_specific_investigation_plans ORDER BY planned_at DESC,id LIMIT $1',[Math.min(500,Math.max(1,limit))])]);return {mode,automaticTerminalAuthority:false,actions:GAP_ACTIONS,rows:rows.rows};}
