import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { decideJobFailure, parseTransientRetryAgeMs, resolveTransientFailureAnchor } from './db';
import { investigationChecksum, parseInvestigationDeadlineMinutes, reduceInvestigation, shouldRefreshOperationalRetryDeadline } from './investigationWorkflow';

const active={state:'ACTIVE' as const,version:1,currentSequence:0,hasPendingSuccessor:false};
test('investigation projection advances monotonically and stays active with a successor',()=>{const scheduled=reduceInvestigation(active,{type:'SCHEDULE',sequence:1}),successor=reduceInvestigation(scheduled,{type:'SCHEDULE',sequence:2}),completed=reduceInvestigation(successor,{type:'COMPLETE',resultingStatus:'UNCERTAIN'});assert.equal(scheduled.currentSequence,1);assert.equal(completed.state,'ACTIVE');assert.equal(completed.currentSequence,2);assert.ok(completed.version>active.version);});
test('terminal evidence, policy changes, unresolved evidence, and exhausted retries produce explicit workflow outcomes',()=>{assert.equal(reduceInvestigation({...active,hasPendingSuccessor:false},{type:'COMPLETE',resultingStatus:'TRADING_CONFIRMED'}).state,'COMPLETED');assert.equal(reduceInvestigation(active,{type:'COMPLETE',resultingStatus:'POLICY_REJECTED'}).state,'SUPERSEDED');assert.equal(reduceInvestigation(active,{type:'COMPLETE',resultingStatus:'UNCERTAIN'}).state,'UNRESOLVED');assert.equal(reduceInvestigation(active,{type:'FAIL',terminal:true}).state,'OPERATIONALLY_BLOCKED');assert.equal(decideJobFailure({code:'INVESTIGATION_DEADLINE_EXCEEDED'},1,4).disposition,'FAILED');});
test('duplicate or out-of-order step sequences fail closed',()=>assert.throws(()=>reduceInvestigation({...active,currentSequence:2},{type:'SCHEDULE',sequence:2}),/must increase/));
test('workflow checksums are deterministic and bind policy input',()=>{assert.equal(investigationChecksum({b:2,a:1}),investigationChecksum({a:1,b:2}));assert.notEqual(investigationChecksum({policy:'a'}),investigationChecksum({policy:'b'}));});
test('operational enrichment retries alone may refresh an expired investigation deadline',()=>{assert.equal(shouldRefreshOperationalRetryDeadline('RETRYING','OperationalEnrichmentProviderError'),true);assert.equal(shouldRefreshOperationalRetryDeadline('RUNNING','OperationalEnrichmentProviderError'),false);assert.equal(shouldRefreshOperationalRetryDeadline('RETRYING','ProviderCallError'),false);assert.equal(shouldRefreshOperationalRetryDeadline('RETRYING','INVESTIGATION_DEADLINE_EXCEEDED'),false);});
test('investigation deadline parser preserves valid leading-zero values and rejects overflow safely',()=>{assert.equal(parseInvestigationDeadlineMinutes('00000000001'),1);assert.equal(parseInvestigationDeadlineMinutes('2147483647'),2147483647);assert.equal(parseInvestigationDeadlineMinutes('2147483648'),30);assert.equal(parseInvestigationDeadlineMinutes('9'.repeat(10000)),30);assert.equal(parseInvestigationDeadlineMinutes('0'),30);assert.equal(parseInvestigationDeadlineMinutes('not-a-number'),30);});
test('migration uses jobs as a transactional outbox and keeps only events immutable',()=>{const migration=readFileSync(new URL('./db/migrations/039_resumable_investigation_workflows.sql',import.meta.url),'utf8'),workflow=readFileSync(new URL('./investigationWorkflow.ts',import.meta.url),'utf8');for(const table of ['investigations','investigation_steps','investigation_events'])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(migration,/investigation_workflow_enabled','false'/);assert.match(migration,/investigation_events_immutable/);assert.doesNotMatch(migration,/investigations_immutable|investigation_steps_immutable/);assert.match(workflow,/await client\.query\('BEGIN'\)[\s\S]*INSERT INTO jobs[\s\S]*INSERT INTO investigation_steps[\s\S]*await client\.query\('COMMIT'\)/);assert.match(workflow,/INVESTIGATION_DEADLINE_EXCEEDED/);});
test('enrichment worker starts, heartbeats, completes, and fails workflow steps',()=>{const queue=readFileSync(new URL('./queueManager.ts',import.meta.url),'utf8');for(const operation of ['startInvestigationStep','heartbeatInvestigationStep','completeInvestigationStep','failInvestigationStep','recoverStaleInvestigationSteps','reconcileOrphanInvestigations'])assert.match(queue,new RegExp(operation));assert.match(queue,/channel\.scan_status = 'FAILED'/);assert.doesNotMatch(queue,/channel\.scan_status = 'NEEDS_REVIEW';\s*channel\.trading_status = 'NEEDS_REVIEW'/);});
test('repair projection preserves operational blockage and does not manufacture review debt',()=>{const workflow=readFileSync(new URL('./investigationWorkflow.ts',import.meta.url),'utf8');assert.match(workflow,/latest\?\.state==='FAILED'\?'OPERATIONALLY_BLOCKED'/);assert.match(workflow,/latest\?\.resulting_status==='NEEDS_REVIEW'\?'NEEDS_REVIEW':latest\?'UNRESOLVED'/);assert.match(workflow,/operationally_blocked/);});
test('transient retry age is anchored to the first transient failure rather than job creation',()=>{const now=Date.parse('2026-08-24T00:00:00Z'),first=Date.parse('2026-08-23T23:30:00Z');assert.equal(resolveTransientFailureAnchor({code:'ETIMEDOUT'},null,now),now);assert.equal(resolveTransientFailureAnchor({code:'ETIMEDOUT'},new Date(first).toISOString(),now),first);assert.equal(resolveTransientFailureAnchor({code:'VALIDATION_ERROR'},new Date(first).toISOString(),now),now);const dbSource=readFileSync(new URL('./db.ts',import.meta.url),'utf8');assert.match(dbSource,/SELECT attempts,max_attempts,first_transient_failure_at FROM jobs/);assert.doesNotMatch(dbSource,/new Date\(created_at\)\.getTime\(\)/);});
test('transient retry age configuration rejects malformed and undersized values',()=>{assert.equal(parseTransientRetryAgeMs(undefined),6*60*60_000);assert.equal(parseTransientRetryAgeMs('not-a-number'),6*60*60_000);assert.equal(parseTransientRetryAgeMs('59999'),6*60*60_000);assert.equal(parseTransientRetryAgeMs('60000'),60000);assert.equal(parseTransientRetryAgeMs('7200000'),7200000);});
test('migration 120 separates retry age from job creation provenance and only repairs provable first-attempt false terminals',()=>{const migration=readFileSync(new URL('./db/migrations/120_transient_retry_age_anchor.sql',import.meta.url),'utf8');assert.match(migration,/first_transient_failure_at TIMESTAMPTZ/);assert.match(migration,/OPERATIONALLY_BLOCKED_RETRY_REQUIRED:/);assert.match(migration,/COUNT\(\*\).*job_attempts/s);assert.match(migration,/attempt_rows = 1/);assert.match(migration,/first_transient_failure_at=NULL/);assert.doesNotMatch(migration,/created_at\s*=\s*now\(\)/);});
