import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { decideJobFailure } from './db';
import { investigationChecksum, reduceInvestigation } from './investigationWorkflow';

const active={state:'ACTIVE' as const,version:1,currentSequence:0,hasPendingSuccessor:false};
test('investigation projection advances monotonically and stays active with a successor',()=>{const scheduled=reduceInvestigation(active,{type:'SCHEDULE',sequence:1}),successor=reduceInvestigation(scheduled,{type:'SCHEDULE',sequence:2}),completed=reduceInvestigation(successor,{type:'COMPLETE',resultingStatus:'UNCERTAIN'});assert.equal(scheduled.currentSequence,1);assert.equal(completed.state,'ACTIVE');assert.equal(completed.currentSequence,2);assert.ok(completed.version>active.version);});
test('terminal evidence, policy changes, and exhausted retries produce explicit workflow outcomes',()=>{assert.equal(reduceInvestigation({...active,hasPendingSuccessor:false},{type:'COMPLETE',resultingStatus:'TRADING_CONFIRMED'}).state,'COMPLETED');assert.equal(reduceInvestigation(active,{type:'COMPLETE',resultingStatus:'POLICY_REJECTED'}).state,'SUPERSEDED');assert.equal(reduceInvestigation(active,{type:'FAIL',terminal:true}).state,'NEEDS_REVIEW');assert.equal(decideJobFailure({code:'INVESTIGATION_DEADLINE_EXCEEDED'},1,4).disposition,'FAILED');});
test('duplicate or out-of-order step sequences fail closed',()=>assert.throws(()=>reduceInvestigation({...active,currentSequence:2},{type:'SCHEDULE',sequence:2}),/must increase/));
test('workflow checksums are deterministic and bind policy input',()=>{assert.equal(investigationChecksum({b:2,a:1}),investigationChecksum({a:1,b:2}));assert.notEqual(investigationChecksum({policy:'a'}),investigationChecksum({policy:'b'}));});
test('migration uses jobs as a transactional outbox and keeps only events immutable',()=>{const migration=readFileSync(new URL('./db/migrations/039_resumable_investigation_workflows.sql',import.meta.url),'utf8'),workflow=readFileSync(new URL('./investigationWorkflow.ts',import.meta.url),'utf8');for(const table of ['investigations','investigation_steps','investigation_events'])assert.match(migration,new RegExp(`CREATE TABLE IF NOT EXISTS ${table}`));assert.match(migration,/investigation_workflow_enabled','false'/);assert.match(migration,/investigation_events_immutable/);assert.doesNotMatch(migration,/investigations_immutable|investigation_steps_immutable/);assert.match(workflow,/await client\.query\('BEGIN'\)[\s\S]*INSERT INTO jobs[\s\S]*INSERT INTO investigation_steps[\s\S]*await client\.query\('COMMIT'\)/);assert.match(workflow,/INVESTIGATION_DEADLINE_EXCEEDED/);});
test('enrichment worker starts, heartbeats, completes, and fails workflow steps',()=>{const queue=readFileSync(new URL('./queueManager.ts',import.meta.url),'utf8');for(const operation of ['startInvestigationStep','heartbeatInvestigationStep','completeInvestigationStep','failInvestigationStep','recoverStaleInvestigationSteps','reconcileOrphanInvestigations'])assert.match(queue,new RegExp(operation));});
