import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import { buildKnowledgeArtifact, classifierFeatures, discoveryAtoms, verifyKnowledgeArtifact, type GovernedConcept } from './knowledgePlane';

const concept: GovernedConcept = { conceptId: 'concept-1', conceptVersion: 3, conceptClass: 'STRATEGY', meaning: 'Order-flow trading analysis', surfaces: [{ surfaceId: 'surface-fr', text: "Flux d'ordres", normalized: "flux d'ordres", language: 'fr', script: 'Latn', locale: 'fr-FR', sense: 'PRIMARY' }], provenance: [{ evidenceId: 'evidence-1', sourceType: 'REVIEWED_CREATOR', sourceEntityId: 'channel-1', observedAt: '2026-07-01T00:00:00.000Z', checksum: 'a'.repeat(64) }], policy: { lanes: ['CLASSIFICATION', 'DISCOVERY'], countries: ['FR'], locales: ['fr-FR'], status: 'APPROVED' } };
const artifact = (lane: 'CLASSIFICATION' | 'DISCOVERY') => buildKnowledgeArtifact({ publicationId: `publication-${lane}`, publicationVersion: 1, scope: { country: 'FR', locale: 'fr-FR', lane }, policyVersion: 'knowledge-policy-1', createdAt: '2026-07-31T00:00:00.000Z', concepts: [concept] });

test('knowledge publications are canonical, deterministic, and tamper evident', () => { const a = artifact('CLASSIFICATION'), b = artifact('CLASSIFICATION'); assert.equal(a.checksum, b.checksum); assert.equal(verifyKnowledgeArtifact(a), true); assert.equal(verifyKnowledgeArtifact({ ...a, policyVersion: 'tampered' }), false); });
test('classification and discovery consume lane-specific projections with one concept identity and pin', () => { const classification = classifierFeatures(artifact('CLASSIFICATION'))[0], discovery = discoveryAtoms(artifact('DISCOVERY'))[0]; assert.equal(classification.conceptId, discovery.conceptId); assert.equal(classification.conceptVersion, 3); assert.equal(discovery.publicationVersion, 1); assert.throws(() => classifierFeatures(artifact('DISCOVERY')), /INVALID_CLASSIFICATION/); });
test('mutable, unapproved, or unproven concepts cannot be published', () => { assert.throws(() => buildKnowledgeArtifact({ publicationId: 'bad', publicationVersion: 1, scope: { country: 'FR', locale: 'fr-FR', lane: 'DISCOVERY' }, policyVersion: 'p', createdAt: '2026-07-31T00:00:00.000Z', concepts: [{ ...concept, policy: { ...concept.policy, status: 'RETIRED' } }] }), /NOT_ELIGIBLE/); });
test('priority 10 migration preserves immutable history, atomic pointers, rollback, and consumer pins', () => { const sql = fs.readFileSync('server/db/migrations/035_unified_governed_knowledge_plane.sql', 'utf8'); assert.doesNotMatch(sql, /\bDROP\s+(?:TABLE|COLUMN)\b/i); assert.match(sql, /active_knowledge_pointers/); assert.match(sql, /reject_immutable_event_mutation/); assert.match(sql, /ROLLBACK/); assert.match(sql, /knowledge_consumption_records/); });
