import { createHash, randomUUID } from 'node:crypto';
import { completeJob, enqueueJob, getDb } from './db';

export type CachedObservation={country:string;lane:string;verified:number;relevant:number;results:number;coverageKeys:string[];quotaCost:number;reviewCost:number};
export type EvaluationPolicy={minResults:number;minPrecision:number;minVerifiedQuality:number;minCoverageGain:number;maxQuotaCostPerVerified:number;maxReviewCost:number};
export type OfflineResult={decision:'ACCEPT'|'REJECT'|'INSUFFICIENT_EVIDENCE';metrics:Record<string,number>;uncertainty:{sampleSize:number;precisionRadius:number};guardrailReasons:string[]};
const stable=(value:unknown):string=>JSON.stringify(value,(_k,v)=>v&&typeof v==='object'&&!Array.isArray(v)?Object.fromEntries(Object.entries(v).sort(([a],[b])=>a.localeCompare(b))):v);
export const checksum=(value:unknown):string=>createHash('sha256').update(stable(value)).digest('hex');
export function evaluateCachedCandidate(rows:CachedObservation[],curatedCoverage:Set<string>,policy:EvaluationPolicy):OfflineResult{
  const results=rows.reduce((n,r)=>n+r.results,0),relevant=rows.reduce((n,r)=>n+r.relevant,0),verified=rows.reduce((n,r)=>n+r.verified,0);
  const precision=results?relevant/results:0,quality=results?verified/results:0;
  const newCoverage=new Set(rows.flatMap(r=>r.coverageKeys).filter(k=>!curatedCoverage.has(k))).size;
  const quota=rows.reduce((n,r)=>n+r.quotaCost,0),review=rows.reduce((n,r)=>n+r.reviewCost,0),quotaPerVerified=verified?quota/verified:quota;
  const radius=results?1.96*Math.sqrt(precision*(1-precision)/results):1;
  const metrics={results,relevant,verified,precision,verifiedQuality:quality,incrementalCoverage:newCoverage,quotaCostProxy:quota,quotaCostPerVerified:quotaPerVerified,reviewCostProxy:review};
  if(results<policy.minResults)return {decision:'INSUFFICIENT_EVIDENCE',metrics,uncertainty:{sampleSize:results,precisionRadius:radius},guardrailReasons:['MINIMUM_SAMPLE_NOT_MET']};
  const reasons:string[]=[];if(precision-radius<policy.minPrecision)reasons.push('PRECISION_LOWER_BOUND');if(quality<policy.minVerifiedQuality)reasons.push('VERIFIED_QUALITY');
  if(newCoverage<policy.minCoverageGain)reasons.push('DUPLICATES_CURATED_COVERAGE');if(quotaPerVerified>policy.maxQuotaCostPerVerified)reasons.push('QUOTA_COST_PROXY');if(review>policy.maxReviewCost)reasons.push('REVIEW_COST_PROXY');
  return {decision:reasons.length?'REJECT':'ACCEPT',metrics,uncertainty:{sampleSize:results,precisionRadius:radius},guardrailReasons:reasons};
}
export function catalogChecksum(entries:Array<{candidateKey:string;country:string;lane:string;resultChecksum:string}>):string{return checksum([...entries].sort((a,b)=>`${a.country}|${a.lane}|${a.candidateKey}`.localeCompare(`${b.country}|${b.lane}|${b.candidateKey}`)));}
export function selectShadowCandidate(entries:Array<{candidateKey:string;country:string;lane:string;ordinal:number}>,country:string,lane:string){return entries.filter(e=>e.country===country&&e.lane===lane).sort((a,b)=>a.ordinal-b.ordinal||a.candidateKey.localeCompare(b.candidateKey))[0]?.candidateKey??null;}
function assertPolicy(policy:EvaluationPolicy){for(const [name,value] of Object.entries(policy))if(!Number.isFinite(value)||value<0)throw new Error(`Invalid evaluation policy field: ${name}.`);if(policy.minPrecision>1||policy.minVerifiedQuality>1)throw new Error('Precision and quality thresholds must be between zero and one.');}

export async function createEvaluation(input:{policyVersion:string;policy:EvaluationPolicy;datasetVersion:string;datasetChecksum:string;codeVersion:string;candidateKeys:string[];actor:string;timeSplitAt?:string;nonComparableReason?:string}){
  if(!input.candidateKeys?.length)throw new Error('candidateKeys is required.');assertPolicy(input.policy);for(const name of ['policyVersion','datasetVersion','datasetChecksum','codeVersion'] as const)if(!String(input[name]||'').trim())throw new Error(`${name} is required.`);const policyChecksum=checksum(input.policy);const policyKey=checksum({version:input.policyVersion,policyChecksum:policyChecksum,codeVersion:input.codeVersion});
  const runKey=checksum({policyKey,datasetVersion:input.datasetVersion,datasetChecksum:input.datasetChecksum,codeVersion:input.codeVersion,candidateKeys:[...new Set(input.candidateKeys)].sort(),timeSplitAt:input.timeSplitAt||null});const db=await getDb();
  const inserted=await db.query(`INSERT INTO evaluation_policy_versions(policy_key,version,definition,definition_checksum,code_version,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(policy_key) DO NOTHING RETURNING id`,[policyKey,input.policyVersion,JSON.stringify(input.policy),policyChecksum,input.codeVersion,input.actor]);const p=inserted.rowCount?inserted:await db.query('SELECT id FROM evaluation_policy_versions WHERE policy_key=$1',[policyKey]);
  const run=await db.query(`INSERT INTO candidate_evaluation_runs(run_key,policy_id,dataset_version,dataset_checksum,code_version,non_comparable,non_comparable_reason,time_split_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(run_key) DO UPDATE SET run_key=excluded.run_key RETURNING *`,[runKey,p.rows[0].id,input.datasetVersion,input.datasetChecksum,input.codeVersion,!!input.nonComparableReason,input.nonComparableReason||null,input.timeSplitAt||null,input.actor]);
  await enqueueJob('OFFLINE_CANDIDATE_EVALUATION',{payloadSchemaVersion:1,runId:run.rows[0].id,candidateKeys:[...new Set(input.candidateKeys)].sort(),policy:input.policy},{priority:1,maxAttempts:3,idempotencyKey:`offline-evaluation:${runKey}`});return run.rows[0];
}
export async function processOfflineEvaluationJob(job:{id:string;payload:any}){const p=job.payload;if(p.payloadSchemaVersion!==1)throw new Error('Unsupported OFFLINE_CANDIDATE_EVALUATION payload version.');
  const db=await getDb();const control=await db.query('SELECT provider_access_allowed FROM offline_evaluation_controls WHERE singleton=true');if(!control.rowCount||control.rows[0].provider_access_allowed)throw new Error('OFFLINE_NO_NETWORK_INVARIANT');
  const run=await db.query('SELECT dataset_version,dataset_checksum FROM candidate_evaluation_runs WHERE id=$1',[p.runId]);if(!run.rowCount)throw new Error('Evaluation run not found.');
  const curated=await db.query('SELECT normalized_term FROM canonical_trading_terms WHERE search_eligible=true');const curatedCoverage=new Set<string>(curated.rows.map(r=>r.normalized_term));
  for(const candidateKey of p.candidateKeys){const cached=await db.query(`SELECT country,lane,verified,relevant,results,coverage_keys "coverageKeys",quota_cost "quotaCost",review_cost "reviewCost" FROM offline_cached_observations WHERE candidate_key=$1 AND dataset_version=$2 AND dataset_checksum=$3 AND retention_permitted=true AND (retention_expires_at IS NULL OR retention_expires_at>now()) ORDER BY observed_at,observation_key`,[candidateKey,run.rows[0].dataset_version,run.rows[0].dataset_checksum]);
    const partitions=new Map<string,CachedObservation[]>();for(const row of cached.rows){const key=`${row.country}\u0000${row.lane}`;partitions.set(key,[...(partitions.get(key)||[]),row]);}if(!partitions.size)partitions.set('und\u0000UNKNOWN',[]);
    for(const [segment,rows] of partitions){const [country,lane]=segment.split('\u0000');const result=evaluateCachedCandidate(rows,curatedCoverage,p.policy);const sum=checksum({candidateKey,country,lane,...result});await db.query(`INSERT INTO candidate_evaluation_results(run_id,candidate_key,country,lane,metrics,uncertainty,guardrail_reasons,decision,result_checksum) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING`,[p.runId,candidateKey,country,lane,JSON.stringify(result.metrics),JSON.stringify(result.uncertainty),JSON.stringify(result.guardrailReasons),result.decision,sum]);}}
  await db.query(`UPDATE candidate_evaluation_runs SET status='COMPLETED',completed_at=now() WHERE id=$1 AND status='PENDING'`,[p.runId]);await completeJob(job.id);
}
export async function buildCatalog(runId:string,actor:string){const db=await getDb();const rows=await db.query(`SELECT id,candidate_key,country,lane,result_checksum,metrics,uncertainty,guardrail_reasons FROM candidate_evaluation_results WHERE run_id=$1 AND decision='ACCEPT' ORDER BY country,lane,candidate_key`,[runId]);const entries=rows.rows.map(r=>({candidateKey:r.candidate_key,country:r.country,lane:r.lane,resultChecksum:r.result_checksum}));const sum=catalogChecksum(entries);const run=await db.query(`SELECT policy_id FROM candidate_evaluation_runs WHERE id=$1 AND status='COMPLETED'`,[runId]);if(!run.rowCount)throw new Error('Evaluation run is not complete.');const client=await db.connect();try{await client.query('BEGIN');const catalog=await client.query(`INSERT INTO candidate_catalogs(catalog_key,evaluation_run_id,policy_id,version,checksum,created_by) VALUES($1,$2,$3,COALESCE((SELECT max(version)+1 FROM candidate_catalogs),1),$4,$5) ON CONFLICT(catalog_key) DO UPDATE SET catalog_key=excluded.catalog_key RETURNING *`,[checksum({runId,sum}),runId,run.rows[0].policy_id,sum,actor]);for(let i=0;i<rows.rows.length;i++){const r=rows.rows[i];await client.query(`INSERT INTO candidate_catalog_entries(catalog_id,evaluation_result_id,ordinal,candidate_key,country,lane,decision_explanation,entry_checksum) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING`,[catalog.rows[0].id,r.id,i,r.candidate_key,r.country,r.lane,JSON.stringify({metrics:r.metrics,uncertainty:r.uncertainty,guardrailReasons:r.guardrail_reasons}),r.result_checksum]);}await client.query('COMMIT');return catalog.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function reviewCatalog(input:{catalogId:string;decision:'APPROVE_SHADOW'|'REJECT';idempotencyKey:string;actor:string;reason:string}){if(!input.idempotencyKey||!input.reason)throw new Error('idempotencyKey and reason are required.');const db=await getDb();const client=await db.connect();try{await client.query('BEGIN');const old=await client.query('SELECT * FROM catalog_publication_approvals WHERE idempotency_key=$1',[input.idempotencyKey]);if(old.rowCount){await client.query('COMMIT');return old.rows[0];}const catalog=await client.query(`SELECT status FROM candidate_catalogs WHERE id=$1`,[input.catalogId]);if(!catalog.rowCount||catalog.rows[0].status!=='DRAFT')throw new Error('CATALOG_REVIEW_CONFLICT');const saved=await client.query(`INSERT INTO catalog_publication_approvals(id,idempotency_key,catalog_id,decision,expected_status,actor,reason) VALUES($1,$2,$3,$4,'DRAFT',$5,$6) RETURNING *`,[randomUUID(),input.idempotencyKey,input.catalogId,input.decision,input.actor,input.reason]);await client.query(`UPDATE candidate_catalogs SET status=$1 WHERE id=$2`,[input.decision==='APPROVE_SHADOW'?'REVIEWED':'REJECTED',input.catalogId]);await client.query('COMMIT');return saved.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function inspectEvaluations(limit=100){const db=await getDb();const n=Math.min(500,Math.max(1,limit));const [controls,runs,results,catalogs]=await Promise.all([db.query('SELECT * FROM offline_evaluation_controls WHERE singleton=true'),db.query('SELECT * FROM candidate_evaluation_runs ORDER BY created_at DESC LIMIT $1',[n]),db.query('SELECT * FROM candidate_evaluation_results ORDER BY created_at DESC LIMIT $1',[n]),db.query(`SELECT c.*,COUNT(e.id)::int entry_count FROM candidate_catalogs c LEFT JOIN candidate_catalog_entries e ON e.catalog_id=c.id GROUP BY c.id ORDER BY c.created_at DESC LIMIT $1`,[n])]);return {mode:'SHADOW_ONLY',productionSource:'PHASE_F',controls:controls.rows[0],runs:runs.rows,results:results.rows,catalogs:catalogs.rows};}
