import assert from 'node:assert/strict';import test from 'node:test';import fs from 'node:fs';
import { catalogChecksum, checksum, evaluateCachedCandidate, selectShadowCandidate } from './offlineEvaluation';
const policy={minResults:20,minPrecision:.7,minVerifiedQuality:.2,minCoverageGain:1,maxQuotaCostPerVerified:10,maxReviewCost:30};
test('golden replay and catalog checksums are order-independent and reproducible',()=>{const a={b:2,a:1};assert.equal(checksum(a),checksum({a:1,b:2}));const entries=[{candidateKey:'b',country:'FR',lane:'VIDEO',resultChecksum:'2'},{candidateKey:'a',country:'FR',lane:'VIDEO',resultChecksum:'1'}];assert.equal(catalogChecksum(entries),catalogChecksum([...entries].reverse()));});
test('missing cached counterfactual evidence is not treated as a negative outcome',()=>{const result=evaluateCachedCandidate([],new Set(),policy);assert.equal(result.decision,'INSUFFICIENT_EVIDENCE');assert.deepEqual(result.guardrailReasons,['MINIMUM_SAMPLE_NOT_MET']);});
test('duplicate curated coverage and uncertainty lower bound reject a candidate',()=>{const result=evaluateCachedCandidate([{country:'FR',lane:'VIDEO',verified:8,relevant:16,results:20,coverageKeys:['curated'],quotaCost:10,reviewCost:10}],new Set(['curated']),policy);assert.equal(result.decision,'REJECT');assert.ok(result.guardrailReasons.includes('DUPLICATES_CURATED_COVERAGE'));assert.ok(result.guardrailReasons.includes('PRECISION_LOWER_BOUND'));});
test('qualified incremental evidence passes all predeclared guardrails',()=>{const result=evaluateCachedCandidate([{country:'FR',lane:'VIDEO',verified:30,relevant:95,results:100,coverageKeys:['new-cluster'],quotaCost:20,reviewCost:10}],new Set(['curated']),policy);assert.equal(result.decision,'ACCEPT');assert.equal(result.metrics.incrementalCoverage,1);});
test('shadow selection is deterministic, segmented, and cannot replace production',()=>{const entries=[{candidateKey:'z',country:'FR',lane:'VIDEO',ordinal:1},{candidateKey:'a',country:'FR',lane:'VIDEO',ordinal:0},{candidateKey:'x',country:'IT',lane:'VIDEO',ordinal:0}];assert.equal(selectShadowCandidate(entries,'FR','VIDEO'),'a');assert.equal(selectShadowCandidate(entries,'US','VIDEO'),null);});
test('phase 11 migration is expand-only, offline, immutable, and publication-disabled',()=>{const sql=fs.readFileSync('server/db/migrations/026_offline_catalog_governance.sql','utf8');assert.doesNotMatch(sql,/\bDROP\s+(?:TABLE|COLUMN)\b/i);assert.match(sql,/provider_access_allowed BOOLEAN NOT NULL DEFAULT false/);assert.match(sql,/publication_enabled BOOLEAN NOT NULL DEFAULT false/);assert.match(sql,/CHECK\(publication_enabled=false\)/);assert.match(sql,/candidate_evaluation_results/);assert.match(sql,/catalog_publication_approvals/);assert.match(sql,/reject_immutable_event_mutation/);});
