import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { coverageEstimate, deterministicCoverageLifecycle, ecosystemOverlap, expandCoverageHierarchy } from './persistentResearchPhase4';

const cutoff='2026-08-02T00:00:00.000Z';
test('coverage hierarchy expands every specified dimension with stable parents',()=>{const cells=expandCoverageHierarchy({country:'Japan',language:'ja',market:'futures',concept:'order-flow',contentStyle:'live',provider:'youtube-search'});assert.equal(cells.length,6);assert.deepEqual(cells.at(-1)?.coordinates,{country:'Japan',language:'ja',market:'futures',concept:'order-flow',contentStyle:'live',provider:'youtube-search'});assert.equal(cells[1].parentCellKey,cells[0].cellKey);assert.notEqual(cells[3].coordinates.concept,'all');});
test('unseen mass requires independent lanes and uses capture-recapture when available',()=>{assert.equal(coverageEstimate({youtube:['a','b']}).estimatedUnseen,null);const estimate=coverageEstimate({search:['a','b'],playlist:['b','c']});assert.equal(estimate.observed,3);assert.ok(estimate.estimatedUnseen!==null);assert.equal(estimate.laneCount,2);});
test('ecosystem overlap combines results, semantics, components and source families',()=>{const prior={resultEntities:new Set(['a','b']),semanticTerms:new Set(['order','flow']),creatorComponents:new Set(['component']),sourceFamilies:new Set(['youtube'])},same=ecosystemOverlap(prior,[prior]),distinct=ecosystemOverlap({resultEntities:new Set(['z']),semanticTerms:new Set(['gamma']),creatorComponents:new Set(['other']),sourceFamilies:new Set(['external'])},[prior]);assert.equal(same.penalty,1);assert.equal(distinct.penalty,0);assert.equal(same.components.semantic,1);});
test('coverage lifecycle uses the pinned cutoff and explicit triggers',()=>{const sleeping=deterministicCoverageLifecycle({lifecycle:'SLEEPING',cutoff,lastProbedAt:'2026-07-20T00:00:00Z',observedCreators:50,estimatedUnseen:0,uncertainty:.01,marginalYield:.01,triggerTypes:['HUMAN_NOMINATION']});assert.equal(sleeping.toLifecycle,'ACTIVE');assert.equal(sleeping.triggerType,'HUMAN_NOMINATION');const scheduled=deterministicCoverageLifecycle({lifecycle:'SLEEPING',cutoff,lastProbedAt:'2025-01-01T00:00:00Z',observedCreators:50,estimatedUnseen:0,uncertainty:.01,marginalYield:.01,triggerTypes:[]});assert.equal(scheduled.triggerType,'SCHEDULED_PROBE');});
test('phase four migration and controller provide immutable replayable lifecycle',()=>{const sql=fs.readFileSync(new URL('./db/migrations/049_persistent_research_phase4_coverage.sql',import.meta.url),'utf8'),controller=fs.readFileSync(new URL('./persistentResearchController.ts',import.meta.url),'utf8');for(const table of ['coverage_projection_snapshots','discovery_action_ecosystem_signatures','research_program_lifecycle_events'])assert.match(sql,new RegExp(table));assert.match(sql,/reject_immutable_event_mutation/);assert.doesNotMatch(sql,/DROP TABLE|DROP COLUMN|TRUNCATE/i);for(const token of ['expandCoverageHierarchy','coverageEstimate','coverage_lifecycle_decision_events','updateProgramCoverageLifecycle','ecosystemOverlap','coverageReactivationTriggers'])assert.match(controller,new RegExp(token));assert.doesNotMatch(controller,/Date\.now\(\).*coverage|coverage.*Date\.now\(\)/);});
