import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { allocateContextualPortfolio, coverageCellKey, decideResearchSleep, estimateUnseenPopulation, generateCoverageGapActions, mineCorpusCandidates, proposeCrossLanguageActions, providerSupports, researchChecksum, semanticOverlapPenalty, type ContextualPolicy, type DiscoveryActionCandidate } from './persistentResearch';

const now='2026-08-02T00:00:00.000Z';
const action=(id:string,patch:Partial<DiscoveryActionCandidate>={}):DiscoveryActionCandidate=>({actionId:id,programId:'p1',actionType:'SEARCH_YOUTUBE',providerKey:'youtube-search',target:id,coordinates:{country:'Japan',language:'ja',market:'futures'},sourceFamilyIds:['f1','f2'],depth:0,clusterKey:id,expectedIncrementalCreators:1,expectedInformationGain:.5,expectedCoverageGain:.5,uncertainty:.2,providerCost:1,reviewCost:0,overlapPenalty:0,priority:1,createdAt:now,provenance:{sourceBound:true},...patch});
const policy:ContextualPolicy={providerBudget:3,reviewBudget:2,programFloors:{p2:1},actionCaps:{INSPECT_PLAYLIST:1},clusterCap:1,curatedSearchFloor:1,explorationBasisPoints:2000,weights:{incremental:4,information:2,coverage:2,uncertainty:1,freshness:0,providerCost:.2,reviewCost:.5,overlap:3,risk:2}};

test('research and hierarchical cell identities are stable and coordinate-sensitive',()=>{assert.equal(researchChecksum({b:2,a:1}),researchChecksum({a:1,b:2}));assert.equal(coverageCellKey({country:'JP',language:'ja'}),coverageCellKey({language:'ja',country:'JP'}));assert.notEqual(coverageCellKey({country:'JP',language:'ja'}),coverageCellKey({country:'JP',language:'en'}));});

test('corpus miner remains source-bound and requires creator and source diversity',()=>{const rows=[{documentId:'d1',sourceFamilyId:'youtube-title',creatorId:'c1',field:'VIDEO_TITLE' as const,text:'板読み スキャルピング',language:'ja',observedAt:now},{documentId:'d2',sourceFamilyId:'youtube-playlist',creatorId:'c2',field:'PLAYLIST_TITLE' as const,text:'板読み 入門',language:'ja',observedAt:now}];const candidate=mineCorpusCandidates(rows).find(x=>x.surface==='板読み');assert.equal(candidate?.lifecycle,'VALIDATED');assert.deepEqual(candidate?.sourceDocumentIds,['d1','d2']);assert.ok(candidate?.reasonCodes.includes('EXACT_SOURCE_SPAN'));assert.equal(mineCorpusCandidates(rows.slice(0,1))[0].lifecycle,'CANDIDATE');});

test('cross-language exploration abstains without independence and emits governed trials',()=>{const actions=proposeCrossLanguageActions({programId:'p',conceptId:'order-flow',knownSurfaces:['order flow'],coordinates:{country:'Japan',market:'futures'},createdAt:now,surfaces:[{surface:'order flow',language:'en',sourceFamilyIds:['a','b']},{surface:'板読み',language:'ja',locale:'ja-JP',sourceFamilyIds:['a','b']},{surface:'薄商い',language:'ja',locale:'ja-JP',sourceFamilyIds:['a']}]});assert.equal(actions.length,1);assert.equal(actions[0].actionType,'TEST_CROSS_LANGUAGE_SURFACE');assert.equal(actions[0].provenance.automaticPublication,false);});

test('capture-recapture is uncertainty-aware and refuses unsupported estimates',()=>{assert.equal(estimateUnseenPopulation([new Set(['a'])]).estimatedUnseen,null);const estimate=estimateUnseenPopulation([new Set(['a','b']),new Set(['b','c'])]);assert.equal(estimate.observed,3);assert.ok(estimate.estimatedUnseen!==null);assert.ok(estimate.reasonCodes.includes('SOURCE_CORRELATION_MUST_BE_AUDITED'));});

test('coverage gaps prioritize uncertainty and schedule stale probes',()=>{const actions=generateCoverageGapActions('p',[{cellKey:'fresh',coordinates:{country:'US'},observedCreators:2,estimatedUnseen:2,uncertainty:.2,marginalYield:.1,lastProbedAt:'2026-08-01T00:00:00Z',reachable:true,lifecycle:'ACTIVE'},{cellKey:'stale',coordinates:{country:'JP'},observedCreators:1,estimatedUnseen:5,uncertainty:.9,marginalYield:.2,lastProbedAt:'2025-01-01T00:00:00Z',reachable:true,lifecycle:'ACTIVE'}],now);assert.equal(actions[0].target,'stale');assert.equal(actions[0].provenance.scheduledProbe,true);});

test('contextual portfolio preserves floors, search controls, clusters and budgets deterministically',()=>{const actions=[action('search'),action('graph',{programId:'p2',actionType:'INSPECT_PLAYLIST',providerKey:'youtube-playlist',uncertainty:.9,providerCost:1,reviewCost:1,expectedInformationGain:2}),action('duplicate-cluster',{clusterKey:'search',expectedIncrementalCreators:10}),action('expensive',{providerCost:10})];const first=allocateContextualPortfolio(actions,policy),second=allocateContextualPortfolio([...actions].reverse(),policy);assert.deepEqual(first,second);assert.equal(first.find(x=>x.actionId==='graph')?.selected,true);assert.ok(first.filter(x=>x.selected).reduce((n,x)=>n+x.providerCost,0)<=3);assert.ok(first.filter(x=>x.selected&&x.clusterKey==='search').length<=1);assert.ok(first.some(x=>x.selected&&x.actionType==='SEARCH_YOUTUBE'));});

test('semantic overlap penalizes duplicate ecosystems',()=>{assert.equal(semanticOverlapPenalty(new Set(['a','b']),[new Set(['a','b'])]),1);assert.equal(semanticOverlapPenalty(new Set(['c']),[new Set(['a','b'])]),0);});

test('provider registry gates unsupported and non-serving providers',()=>{const candidate=action('a');assert.equal(providerSupports({key:'youtube-search',family:'youtube',kind:'RETRIEVAL',capabilities:['SEARCH_YOUTUBE'],quotaDomain:'youtube',mode:'ACTIVE',dailyCostCap:100},candidate),true);assert.equal(providerSupports({key:'shadow',family:'x',kind:'RETRIEVAL',capabilities:['SEARCH_YOUTUBE'],quotaDomain:'x',mode:'SHADOW',dailyCostCap:0},candidate),false);});

test('sleep remains conservative and scheduled probes force reactivation',()=>{const base={evidenceCount:100,minimumEvidence:10,bestFrontierUpperBound:.01,costAwareThreshold:.1,rediscoveryRate:.95,minimumRediscoveryRate:.9,uncoveredReachableCells:0,highInformationActions:0,delayedBacklog:0,maximumDelayedBacklog:0,marginalUniqueYield:.01,confidenceUpperBound:.02,scheduledProbeDue:false};assert.equal(decideResearchSleep(base).shouldSleep,true);assert.equal(decideResearchSleep({...base,scheduledProbeDue:true}).shouldSleep,false);});

test('migration is expand-only, fail-closed and keeps attribution immutable',()=>{const sql=fs.readFileSync(new URL('./db/migrations/043_persistent_research_system.sql',import.meta.url),'utf8');assert.match(sql,/mode TEXT NOT NULL DEFAULT 'SHADOW'/);assert.match(sql,/kill_switch BOOLEAN NOT NULL DEFAULT true/);assert.match(sql,/persistent_research_enabled','false'/);assert.match(sql,/discovery_action_assignments','discovery_action_outcomes/);assert.match(sql,/reject_immutable_event_mutation/);assert.doesNotMatch(sql,/DROP TABLE|DROP COLUMN|TRUNCATE/i);assert.match(sql,/structured-external-nominations[\s\S]*'PAUSED'/);});
