import { deterministicUuid, entityChecksum, normalizeIdentifier, sourceFamilyIdentity } from './entityResolution';
import { getDb } from './db';
import { PERSISTENT_RESEARCH_POLICY_VERSION, researchChecksum } from './persistentResearch';

export const CREATOR_RELATIONSHIP_EXTRACTOR_VERSION='creator-relationships-v1';
export type ExtractedCreatorRelationship={targetNamespace:'YOUTUBE_CHANNEL_ID'|'PLATFORM_ACCOUNT';targetValue:string;relationshipType:'COLLABORATES_WITH'|'FEATURES'|'MENTIONS'|'LINKS_TO';startOffset:number;endOffset:number;confidenceBasisPoints:number};
const channelId=/\bUC[A-Za-z0-9_-]{22}\b/gu,handle=/(?:youtube\.com\/@|(?<![\p{L}\p{N}_])@)([\p{L}\p{N}_.-]{3,30})/gu;
export function extractCreatorRelationships(text:string,maxFanout=10):ExtractedCreatorRelationship[]{const items:ExtractedCreatorRelationship[]=[];for(const match of text.matchAll(channelId)){const nearby=text.slice(Math.max(0,match.index!-40),Math.min(text.length,match.index!+match[0].length+40)).toLocaleLowerCase('und'),type=nearby.includes('featured')?'FEATURES':/(with|guest|collab)/u.test(nearby)?'COLLABORATES_WITH':'LINKS_TO';items.push({targetNamespace:'YOUTUBE_CHANNEL_ID',targetValue:match[0],relationshipType:type,startOffset:match.index!,endOffset:match.index!+match[0].length,confidenceBasisPoints:type==='LINKS_TO'?9000:9500});}for(const match of text.matchAll(handle)){const nearby=text.slice(Math.max(0,match.index!-40),Math.min(text.length,match.index!+match[0].length+40)).toLocaleLowerCase('und'),type=nearby.includes('featured')?'FEATURES':/(with|guest|collab)/u.test(nearby)?'COLLABORATES_WITH':'MENTIONS';items.push({targetNamespace:'PLATFORM_ACCOUNT',targetValue:`@${match[1]}`,relationshipType:type,startOffset:match.index!,endOffset:match.index!+match[0].length,confidenceBasisPoints:type==='MENTIONS'?7500:8500});}return [...new Map(items.map(item=>[`${item.targetNamespace}|${item.targetValue}|${item.relationshipType}`,item])).values()].sort((a,b)=>b.confidenceBasisPoints-a.confidenceBasisPoints||a.targetValue.localeCompare(b.targetValue)).slice(0,Math.min(50,Math.max(0,maxFanout)));}
export function graphExperimentAssignment(key:string,graphBasisPoints=5000){if(graphBasisPoints<1||graphBasisPoints>9999)throw new Error('INVALID_GRAPH_EXPERIMENT_ALLOCATION');const bucket=Number.parseInt(researchChecksum({key,policy:CREATOR_RELATIONSHIP_EXTRACTOR_VERSION}).slice(0,8),16)%10000;return {arm:bucket<graphBasisPoints?'GRAPH' as const:'SEARCH_CONTROL' as const,propensityBasisPoints:bucket<graphBasisPoints?graphBasisPoints:10000-graphBasisPoints,randomizationValue:bucket};}

export async function ensureArtifactSourceFamily(input:{artifactId:string;observedAt:string}){const family=sourceFamilyIdentity({provider:'corpus-artifact',artifactId:input.artifactId}),db=await getDb();await db.query(`INSERT INTO source_families(id,family_key,family_type,root_locator,policy_version) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING`,[family.familyId,family.familyKey,family.familyType,family.rootLocator,PERSISTENT_RESEARCH_POLICY_VERSION]);await db.query(`INSERT INTO source_family_memberships(membership_key,family_id,source_artifact_id,observed_at,policy_version) VALUES($1,$2,$3,$4,$5) ON CONFLICT(membership_key) DO NOTHING`,[researchChecksum({familyId:family.familyId,artifactId:input.artifactId}),family.familyId,input.artifactId,input.observedAt,PERSISTENT_RESEARCH_POLICY_VERSION]);return family.familyId;}

export async function resolveExactYouTubeRelationshipTarget(input:{channelId:string;displayName?:string;sourceArtifactId:string;sourceEntityId:string;observedAt:string}){const channelId=normalizeIdentifier('YOUTUBE_CHANNEL_ID',input.channelId);if(!/^UC[A-Za-z0-9_-]{22}$/u.test(channelId))throw new Error('INVALID_YOUTUBE_CHANNEL_ID');const entityId=deterministicUuid('youtube-channel',channelId),family=sourceFamilyIdentity({provider:'youtube',nativeId:channelId}),db=await getDb(),client=await db.connect();try{await client.query('BEGIN');await client.query(`INSERT INTO canonical_entities(id,entity_type,status,display_name) VALUES($1,'CHANNEL','ACTIVE',$2) ON CONFLICT(id) DO NOTHING`,[entityId,input.displayName||channelId]);await client.query(`INSERT INTO source_families(id,family_key,family_type,root_locator,policy_version) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING`,[family.familyId,family.familyKey,family.familyType,family.rootLocator,PERSISTENT_RESEARCH_POLICY_VERSION]);await client.query(`INSERT INTO entity_identifier_observations(observation_key,namespace,normalized_value,entity_id,source_family_id,source_artifact_id,observed_at,policy_version) VALUES($1,'YOUTUBE_CHANNEL_ID',$2,$3,$4,$5,$6,$7) ON CONFLICT(observation_key) DO NOTHING`,[entityChecksum({entityId,channelId,artifactId:input.sourceArtifactId}),channelId,entityId,family.familyId,input.sourceArtifactId,input.observedAt,PERSISTENT_RESEARCH_POLICY_VERSION]);await client.query(`INSERT INTO entity_bindings(entity_id,namespace,normalized_value,status,confidence_basis_points,resolution_basis) VALUES($1,'YOUTUBE_CHANNEL_ID',$2,'APPROVED',10000,'EXACT_PROVIDER_NATIVE') ON CONFLICT(entity_id,namespace,normalized_value) DO NOTHING`,[entityId,channelId]);await client.query(`INSERT INTO entity_projection_events(event_key,entity_id,event_type,payload,policy_version,actor) VALUES($1,$2,'NATIVE_IDENTIFIER_BOUND',$3,$4,'system:relationship-resolver') ON CONFLICT(event_key) DO NOTHING`,[entityChecksum({entityId,channelId}),entityId,JSON.stringify({channelId,sourceArtifactId:input.sourceArtifactId,sourceEntityId:input.sourceEntityId}),PERSISTENT_RESEARCH_POLICY_VERSION]);await client.query('COMMIT');return {entityId,sourceFamilyId:family.familyId,channelId};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
