import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { normalizeExternalNominations, researchPolicyFromConfiguration } from './persistentResearchController';
import { actionUtility, type DiscoveryActionCandidate } from './persistentResearch';

test('external nominations normalize, deduplicate and stay bounded without network access',()=>{const item={providerNativeId:'  speaker-1 ',displayName:'  Trader One ',youtubeLocator:' https://youtube.test/c/one ',country:'US',language:'en',sourceFamilyId:'conference-2026',sourceLocator:{page:'speakers'},observedAt:'2026-08-02T00:00:00Z'};const result=normalizeExternalNominations('approved-directory',[item,item],10);assert.equal(result.length,1);assert.equal(result[0].providerNativeId,'speaker-1');assert.equal(result[0].displayName,'Trader One');assert.match(result[0].nominationKey,/^[a-f0-9]{64}$/);});

test('server policy always conserves control-plane budgets and uses configured weights',()=>{const policy=researchPolicyFromConfiguration({clusterCap:3,weights:{freshness:4,incremental:10}},{provider:120,review:7,exploration:500});assert.equal(policy.providerBudget,120);assert.equal(policy.reviewBudget,7);assert.equal(policy.explorationBasisPoints,500);assert.equal(policy.clusterCap,3);assert.equal(policy.weights.freshness,4);});

test('freshness contributes to contextual utility instead of being a dead policy field',()=>{const base:DiscoveryActionCandidate={actionId:'a',programId:'p',actionType:'SEARCH_YOUTUBE',providerKey:'youtube-search',target:'x',coordinates:{country:'US'},sourceFamilyIds:['a','b'],depth:0,clusterKey:'x',expectedIncrementalCreators:0,expectedInformationGain:0,expectedCoverageGain:0,uncertainty:0,providerCost:0,reviewCost:0,overlapPenalty:0,priority:0,createdAt:'2026-08-02T00:00:00Z',provenance:{}};const policy=researchPolicyFromConfiguration({weights:{freshness:2}},{provider:1,review:1,exploration:0});assert.ok(actionUtility({...base,freshnessValue:1},policy)>actionUtility(base,policy));});

test('orchestration migration is additive, immutable, leased and policy-gated',()=>{const sql=fs.readFileSync(new URL('./db/migrations/044_persistent_research_orchestration.sql',import.meta.url),'utf8');assert.doesNotMatch(sql,/DROP TABLE|DROP COLUMN|TRUNCATE/i);assert.match(sql,/lease_token UUID/);assert.match(sql,/discovery_observation_events/);assert.match(sql,/persistent_research_policy_evaluations/);assert.match(sql,/external_nomination_observations/);assert.match(sql,/reject_immutable_event_mutation/);assert.match(sql,/FOR EACH ROW/);const triggerBlock=sql.slice(sql.indexOf('DO $$'));assert.doesNotMatch(triggerBlock,/persistent_research_cycles/);});

test('controller uses canonical rows, immutable attribution, leases and existing durable adapters',()=>{const source=fs.readFileSync(new URL('./persistentResearchController.ts',import.meta.url),'utf8');assert.match(source,/FROM discovery_actions a JOIN discovery_provider_registry/);assert.match(source,/persistent_research_policy_evaluations/);assert.match(source,/discovery_observation_events/);assert.match(source,/discovery_action_outcomes/);assert.match(source,/enqueuePlaylistCanary/);assert.match(source,/observeTerminology/);assert.match(source,/lease_expires_at/);assert.doesNotMatch(source,/fetch\(|axios|cheerio/);});

test('direct client-owned allocation endpoint is rejected',()=>{const server=fs.readFileSync(new URL('../server.ts',import.meta.url),'utf8');assert.match(server,/SERVER_OWNED_ALLOCATION_REQUIRED/);assert.match(server,/runPersistentResearchCycle/);});

test('completion migration adds immutable entity captures, lifecycle decisions and policy replay',()=>{const sql=fs.readFileSync(new URL('./db/migrations/045_persistent_research_completion.sql',import.meta.url),'utf8');assert.match(sql,/discovery_entity_captures/);assert.match(sql,/coverage_lifecycle_decision_events/);assert.match(sql,/research_policy_replay_runs/);assert.match(sql,/reject_immutable_event_mutation/);assert.doesNotMatch(sql,/DROP TABLE|DROP COLUMN|TRUNCATE/i);});

test('canonical allocation checks provider capabilities and fails rather than slicing selected constraints',()=>{const source=fs.readFileSync(new URL('./persistentResearchController.ts',import.meta.url),'utf8');assert.match(source,/p\.capabilities \? a\.action_type/);assert.match(source,/RESEARCH_CYCLE_CAP_CONFLICT/);assert.match(source,/projectEntityCaptures/);});

test('phase 1 projects entity captures, deterministic review origins, multi-path credit and controls',()=>{const source=fs.readFileSync(new URL('./persistentResearchController.ts',import.meta.url),'utf8'),sql=fs.readFileSync(new URL('./db/migrations/046_persistent_research_phase1_attribution.sql',import.meta.url),'utf8');assert.match(source,/projectEntityCaptures/);assert.match(source,/EARLIEST_RESEARCH_SIGHTING/);assert.match(source,/projectEntityCredits/);assert.match(source,/projectIncrementality/);assert.match(sql,/discovery_entity_credit_snapshots/);assert.match(sql,/discovery_incrementality_snapshots/);});
