import {getAppSetting,getDb} from './db';
import {evaluationChecksum} from './decisionEvaluation';
export const PHASE_B_SHADOW_POLICY_VERSION='phase-b-shadow-v1';

export async function recordProjectionObservation(input:{channelId:string;diagnosticId?:string;inputChecksum:string;equivalent:boolean;documentCount:number;assertionCount:number;projectedEvidenceCount:number;excludedEvidenceIds:string[];coveragePersisted:boolean;durationMs:number;reasonCodes:string[];observedAt:string}){
 const db=await getDb(),key=evaluationChecksum({...input,version:PHASE_B_SHADOW_POLICY_VERSION});
 await db.query(`INSERT INTO evidence_projection_observations(observation_key,channel_id,classification_diagnostic_id,input_checksum,equivalent,document_count,assertion_count,projected_evidence_count,excluded_evidence_ids,coverage_persisted,duration_ms,reason_codes,dual_write_version,observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'evidence-dual-write-v1',$13) ON CONFLICT(observation_key) DO NOTHING`,[key,input.channelId,input.diagnosticId||null,input.inputChecksum,input.equivalent,input.documentCount,input.assertionCount,input.projectedEvidenceCount,JSON.stringify(input.excludedEvidenceIds),input.coveragePersisted,input.durationMs,JSON.stringify(input.reasonCodes),input.observedAt]);
}

export async function validateEvidenceProjection(input:{windowStart:string;cutoffAt:string;actor:string;maximumP95DurationMs?:number}){
 if(!input.actor.trim())throw new Error('ACTOR_REQUIRED');const start=new Date(input.windowStart),cutoff=new Date(input.cutoffAt);if(!Number.isFinite(start.getTime())||!Number.isFinite(cutoff.getTime())||start>=cutoff)throw new Error('INVALID_VALIDATION_WINDOW');
 const db=await getDb(),result=await db.query(`SELECT (SELECT count(*) FROM production_classification_diagnostics WHERE created_at>=$1 AND created_at<$2)::int diagnostic_count,count(*)::int observed_count,count(*) FILTER(WHERE equivalent)::int equivalent_count,count(*) FILTER(WHERE document_count>0 AND coverage_persisted)::int complete_count,count(*) FILTER(WHERE classification_diagnostic_id IS NOT NULL)::int lineage_count,coalesce(percentile_disc(.95) WITHIN GROUP(ORDER BY duration_ms),0)::int p95_duration_ms,(SELECT count(*) FROM phase_b_observation_outbox WHERE observation_type='PRODUCTION_DIAGNOSTIC' AND status<>'COMPLETED' AND created_at>=$1 AND created_at<$2)::int pending_observation_count FROM evidence_projection_observations WHERE observed_at>=$1 AND observed_at<$2`,[input.windowStart,input.cutoffAt]),m=result.rows[0],reasons:string[]=[];
 if(!Number(m.observed_count))reasons.push('INSUFFICIENT_OBSERVATIONS');if(Number(m.observed_count)<Number(m.diagnostic_count))reasons.push('DIAGNOSTIC_COVERAGE_GAP');if(Number(m.equivalent_count)<Number(m.observed_count))reasons.push('PROJECTION_MISMATCH');if(Number(m.complete_count)<Number(m.observed_count))reasons.push('DOCUMENT_OR_COVERAGE_INCOMPLETE');if(Number(m.lineage_count)<Number(m.observed_count))reasons.push('DIAGNOSTIC_LINEAGE_GAP');if(Number(m.pending_observation_count))reasons.push('OBSERVATION_RECONCILIATION_PENDING');if(Number(m.p95_duration_ms)>(input.maximumP95DurationMs??250))reasons.push('PERFORMANCE_BUDGET_EXCEEDED');
 const status=reasons.includes('INSUFFICIENT_OBSERVATIONS')?'INSUFFICIENT_EVIDENCE':reasons.length?'FAIL':'PASS',metrics={...m,coverageRatio:Number(m.diagnostic_count)?Number(m.observed_count)/Number(m.diagnostic_count):0,equivalenceRatio:Number(m.observed_count)?Number(m.equivalent_count)/Number(m.observed_count):0,completenessRatio:Number(m.observed_count)?Number(m.complete_count)/Number(m.observed_count):0,lineageRatio:Number(m.observed_count)?Number(m.lineage_count)/Number(m.observed_count):0},key=evaluationChecksum({input,metrics,status,policy:PHASE_B_SHADOW_POLICY_VERSION});
 const saved=await db.query(`INSERT INTO evidence_projection_validation_runs(validation_key,cutoff_at,window_start,diagnostic_count,observed_count,equivalent_count,complete_count,lineage_count,p95_duration_ms,status,metrics,reason_codes,policy_version,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(validation_key) DO NOTHING RETURNING *`,[key,input.cutoffAt,input.windowStart,m.diagnostic_count,m.observed_count,m.equivalent_count,m.complete_count,m.lineage_count,m.p95_duration_ms,status,JSON.stringify(metrics),JSON.stringify(reasons),PHASE_B_SHADOW_POLICY_VERSION,input.actor]);return saved.rows[0]||(await db.query('SELECT * FROM evidence_projection_validation_runs WHERE validation_key=$1',[key])).rows[0];
}

export async function activateAssertionDualWrite(input:{validationRunId:string;actor:string;reason:string}){
 if(!input.actor.trim()||!input.reason.trim())throw new Error('ACTOR_AND_REASON_REQUIRED');const db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const validation=await client.query(`SELECT * FROM evidence_projection_validation_runs WHERE id=$1 AND status='PASS' FOR SHARE`,[input.validationRunId]);if(!validation.rowCount)throw new Error('PASSING_DOCUMENT_VALIDATION_REQUIRED');const prior=await client.query(`SELECT setting_value FROM app_settings WHERE setting_key='evidence_assertion_dual_write_enabled' FOR UPDATE`),priorValue=prior.rows[0]?.setting_value||'false',eventKey=evaluationChecksum({control:'EVIDENCE_ASSERTIONS',priorValue,resultingValue:'true',validationRunId:input.validationRunId,policy:PHASE_B_SHADOW_POLICY_VERSION});await client.query(`INSERT INTO phase_b_shadow_control_events(event_key,control,prior_value,resulting_value,validation_run_id,reason,changed_by,policy_version) VALUES($1,'EVIDENCE_ASSERTIONS',$2,'true',$3,$4,$5,$6)`,[eventKey,priorValue,input.validationRunId,input.reason,input.actor,PHASE_B_SHADOW_POLICY_VERSION]);await client.query(`INSERT INTO app_settings(setting_key,setting_value) VALUES('evidence_assertion_dual_write_enabled','true') ON CONFLICT(setting_key) DO UPDATE SET setting_value='true'`);await client.query('COMMIT');return {enabled:true,servingAuthority:false,automaticPromotion:false,validationRunId:input.validationRunId};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
}
export async function disablePhaseBShadowControl(input:{control:'EVALUATION_SAMPLING'|'EVIDENCE_DOCUMENTS'|'EVIDENCE_ASSERTIONS'|'CREATOR_FOCUS_SHADOW';actor:string;reason:string}){if(!input.actor.trim()||!input.reason.trim())throw new Error('ACTOR_AND_REASON_REQUIRED');const setting={EVALUATION_SAMPLING:'decision_evaluation_sampling_enabled',EVIDENCE_DOCUMENTS:'evidence_document_dual_write_enabled',EVIDENCE_ASSERTIONS:'evidence_assertion_dual_write_enabled',CREATOR_FOCUS_SHADOW:'creator_focus_classifier_mode'}[input.control],resulting=input.control==='CREATOR_FOCUS_SHADOW'?'OFF':'false',db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const prior=await client.query('SELECT setting_value FROM app_settings WHERE setting_key=$1 FOR UPDATE',[setting]),priorValue=prior.rows[0]?.setting_value||resulting,eventKey=evaluationChecksum({control:input.control,priorValue,resulting,actor:input.actor,reason:input.reason,policy:PHASE_B_SHADOW_POLICY_VERSION});await client.query(`INSERT INTO phase_b_shadow_control_events(event_key,control,prior_value,resulting_value,reason,changed_by,policy_version) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(event_key) DO NOTHING`,[eventKey,input.control,priorValue,resulting,input.reason,input.actor,PHASE_B_SHADOW_POLICY_VERSION]);await client.query(`INSERT INTO app_settings(setting_key,setting_value) VALUES($1,$2) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value`,[setting,resulting]);await client.query('COMMIT');return {control:input.control,priorValue,resultingValue:resulting,servingAuthority:false};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}}
export async function inspectPhaseBShadow(){return {policyVersion:PHASE_B_SHADOW_POLICY_VERSION,servingAuthority:false,automaticPromotion:false,settings:{sampling:await getAppSetting('decision_evaluation_sampling_enabled','false'),documents:await getAppSetting('evidence_document_dual_write_enabled','false'),assertions:await getAppSetting('evidence_assertion_dual_write_enabled','false'),creatorFocus:await getAppSetting('creator_focus_classifier_mode','OFF')}};}
