import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {classifyEvidenceDocuments} from './evidenceEngine/documentSemanticProvider';import type {EvidenceAssertionObservation,EvidenceDocumentObservation} from './evidenceEngine/documentTypes';
const document=(documentKey:string,documentType:EvidenceDocumentObservation['documentType'],sourceFamilyId='family'):EvidenceDocumentObservation=>({documentKey,canonicalDocumentId:documentKey,subjectEntityId:'subject',channelId:'channel',documentType,provider:'youtube',canonicalLocator:{},sourceFamilyId,observedAt:'2026-01-01T00:00:00Z',normalizedText:'content',textChecksum:'t',rawPayloadChecksum:'r',provenance:{},schemaVersion:'v1'});
const assertion=(documentKey:string,label:string):EvidenceAssertionObservation=>({assertionKey:`a:${documentKey}`,subjectEntityId:'subject',channelId:'channel',assertionType:label==='FINANCIAL_NEWS'?'NON_TRADING_ADJACENT':'METHODOLOGY_CONCEPT',hypothesis:'CREATOR_FOCUS',polarity:label==='FINANCIAL_NEWS'?'NEGATIVE':'POSITIVE',confidenceBasisPoints:9000,reliability:'HIGH',documentKeys:[documentKey],sourceFamilyIds:['family'],modelOrRuleVersion:'m',provider:'semantic',languageCapability:{},reasonCodes:['ATTRIBUTED'],derivation:{evidenceItem:{provenance:{semantic:{taxonomyLabel:label}}}},observedAt:'2026-01-01T00:00:00Z'});
test('unmatched creator documents remain explicit ambiguous coverage',()=>{const [result]=classifyEvidenceDocuments([document('about','CHANNEL_ABOUT')],[]);assert.equal(result.distribution.AMBIGUOUS,1);assert.deepEqual(result.reasonCodes,['UNMATCHED_DOCUMENT_REQUIRES_SEMANTIC_COVERAGE']);assert.equal(result.sourceAssertionKeys.length,0);});
test('alternative-focus semantic assertions map to creator-level alternatives',()=>{const [result]=classifyEvidenceDocuments([document('news','VIDEO_TITLE')],[assertion('news','FINANCIAL_NEWS')]);assert.equal(result.distribution.FINANCIAL_NEWS,1);assert.equal(result.distribution.ACTIVE_TRADING_CREATOR,0);});
test('search-match context cannot establish creator focus',()=>{assert.deepEqual(classifyEvidenceDocuments([document('search','SEARCH_MATCH_CONTEXT')],[assertion('search','ACTIVE_TRADING')]),[]);});
test('Phase B migration enables only sampling, documents, and non-authoritative shadow',()=>{const sql=readFileSync('server/db/migrations/063_phase_b_shadow_evaluation.sql','utf8'),classifier=readFileSync('server/evidenceEngine/classifierV4.ts','utf8'),phase=readFileSync('server/phaseBShadow.ts','utf8');assert.match(sql,/decision_evaluation_sampling_enabled','true'/);assert.match(sql,/evidence_document_dual_write_enabled','true'/);assert.match(sql,/evidence_assertion_dual_write_enabled','false'/);assert.match(sql,/creator_focus_classifier_mode','SHADOW'/);assert.match(sql,/reject_immutable_event_mutation/);assert.match(phase,/PASSING_DOCUMENT_VALIDATION_REQUIRED/);assert.match(phase,/PERFORMANCE_BUDGET_EXCEEDED/);assert.match(phase,/disablePhaseBShadowControl/);assert.match(phase,/servingAuthority:false,automaticPromotion:false/);assert.match(classifier,/automaticTerminalAuthority:false/);});
test('Phase B benchmark is sealed, segmented, no-network, and non-authoritative',()=>{const evaluation=readFileSync('server/decisionEvaluation.ts','utf8'),benchmark=readFileSync('server/phaseBBenchmark.ts','utf8');for(const segment of ['discoveryOrigin','retrievalLane','queryIntent','queryGenerationMode','matchedDocumentType','creatorType','enrichmentStage','activityBand'])assert.match(evaluation,new RegExp(segment));assert.match(evaluation,/calibrationFrom < testFrom <= cutoffAt/);assert.match(benchmark,/CREATOR_FOCUS_SNAPSHOT_COVERAGE_GAP/);assert.match(benchmark,/servingAuthority:false,automaticPromotion:false/);assert.doesNotMatch(benchmark,/fetch\s*\(/);});
