import {createHash} from 'node:crypto';
import {getDb} from './db';

export const PORTFOLIO_POLICY_SCHEMA_VERSION=1;
export type Candidate={actionId:string;programId:string;actionType:string;priority:number;expectedReward:number;providerCost:number;reviewCost:number;clusterKey:string;createdAt:string};
export type PortfolioConfig={totalProviderBudget:number;totalReviewBudget:number;programFloors:Record<string,number>;actionCaps:Record<string,number>;clusterCap:number;curatedSearchFloor:number};
export type PortfolioChoice=Candidate&{selected:boolean;rank:number|null;score:number;propensityBasisPoints:number;reason:string};

function finiteNonnegative(value:number){return Number.isFinite(value)&&value>=0;}
export function validatePortfolioConfig(c:PortfolioConfig):void{
  if(!Number.isInteger(c.totalProviderBudget)||c.totalProviderBudget<0||!Number.isInteger(c.totalReviewBudget)||c.totalReviewBudget<0)throw new Error('INVALID_PORTFOLIO_BUDGET');
  if(!Number.isInteger(c.clusterCap)||c.clusterCap<1||!Number.isInteger(c.curatedSearchFloor)||c.curatedSearchFloor<0)throw new Error('INVALID_PORTFOLIO_GUARDRAIL');
  for(const values of [Object.values(c.programFloors),Object.values(c.actionCaps)])if(values.some(v=>!Number.isInteger(v)||v<0))throw new Error('INVALID_PORTFOLIO_GUARDRAIL');
  if(Object.values(c.programFloors).reduce((a,b)=>a+b,0)>c.totalProviderBudget)throw new Error('FAIRNESS_FLOORS_EXCEED_BUDGET');
}
function compare(a:Candidate,b:Candidate){const as=a.expectedReward/Math.max(1,a.providerCost+a.reviewCost),bs=b.expectedReward/Math.max(1,b.providerCost+b.reviewCost);return bs-as||b.priority-a.priority||a.createdAt.localeCompare(b.createdAt)||a.actionId.localeCompare(b.actionId);}
/** Transparent deterministic best-first allocation. Floors are satisfied first; all constraints are conserved. */
export function allocateBestFirst(candidates:Candidate[],config:PortfolioConfig):PortfolioChoice[]{
  validatePortfolioConfig(config);for(const c of candidates)if(!finiteNonnegative(c.expectedReward)||!Number.isInteger(c.providerCost)||c.providerCost<0||!Number.isInteger(c.reviewCost)||c.reviewCost<0)throw new Error('INVALID_CANDIDATE_COST');
  const ordered=[...new Map(candidates.map(c=>[c.actionId,c])).values()].sort(compare);let provider=0,review=0,rank=0;
  const programs=new Map<string,number>(),actions=new Map<string,number>(),clusters=new Map<string,number>(),selected=new Set<string>();
  const can=(c:Candidate)=>provider+c.providerCost<=config.totalProviderBudget&&review+c.reviewCost<=config.totalReviewBudget&&(actions.get(c.actionType)||0)<(config.actionCaps[c.actionType]??Number.MAX_SAFE_INTEGER)&&(clusters.get(c.clusterKey)||0)<config.clusterCap;
  const take=(c:Candidate)=>{if(selected.has(c.actionId)||!can(c))return false;selected.add(c.actionId);provider+=c.providerCost;review+=c.reviewCost;programs.set(c.programId,(programs.get(c.programId)||0)+c.providerCost);actions.set(c.actionType,(actions.get(c.actionType)||0)+1);clusters.set(c.clusterKey,(clusters.get(c.clusterKey)||0)+1);return true;};
  for(const [program,floor] of Object.entries(config.programFloors).sort())for(const c of ordered.filter(x=>x.programId===program))if((programs.get(program)||0)<floor)take(c);
  const search=ordered.filter(c=>c.actionType==='SEARCH_TERM');for(const c of search)if([...selected].filter(id=>ordered.find(x=>x.actionId===id)?.actionType==='SEARCH_TERM').length<config.curatedSearchFloor)take(c);
  for(const c of ordered)take(c);
  return ordered.map(c=>{const yes=selected.has(c.actionId);return {...c,selected:yes,rank:yes?++rank:null,score:c.expectedReward/Math.max(1,c.providerCost+c.reviewCost),propensityBasisPoints:yes?10000:0,reason:yes?'FIXED_BEST_FIRST':'CONSTRAINT_OR_BUDGET'};});
}
function stableJson(value:unknown):string{if(Array.isArray(value))return `[${value.map(stableJson).join(',')}]`;if(value&&typeof value==='object')return `{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${JSON.stringify(k)}:${stableJson(v)}`).join(',')}}`;return JSON.stringify(value);}
export function policyChecksum(config:unknown){return createHash('sha256').update(stableJson(config)).digest('hex');}

export async function inspectPortfolio(limit=100){const db=await getDb();const n=Math.min(500,Math.max(1,Math.trunc(limit)));const [p,e,d]=await Promise.all([db.query('SELECT * FROM portfolio_policies ORDER BY created_at DESC LIMIT $1',[n]),db.query('SELECT * FROM portfolio_policy_evaluations ORDER BY created_at DESC LIMIT $1',[n]),db.query(`SELECT d.*,p.policy_key FROM portfolio_decisions d JOIN portfolio_allocations a ON a.id=d.allocation_id JOIN portfolio_policies p ON p.id=a.policy_id ORDER BY d.decided_at DESC,d.decision_key LIMIT $1`,[n])]);return {schemaVersion:PORTFOLIO_POLICY_SCHEMA_VERSION,adaptiveAssignmentsEnabled:p.rows.some((x:any)=>x.status==='CANARY'&&x.policy_type==='CONTEXTUAL_BANDIT'),fallback:'FIXED_BEST_FIRST_THEN_ROTATING_SCHEDULER',policies:p.rows,evaluations:e.rows,decisions:d.rows};}

export async function createPolicy(input:{policyKey:string;policyType:'FIXED_BEST_FIRST'|'CONTEXTUAL_BANDIT';configuration:PortfolioConfig;actor:string}){validatePortfolioConfig(input.configuration);const db=await getDb();const version=await db.query('SELECT COALESCE(MAX(version),0)+1 version FROM portfolio_policies WHERE policy_key=$1',[input.policyKey]);const checksum=policyChecksum(input.configuration);const r=await db.query(`INSERT INTO portfolio_policies(policy_key,version,policy_type,status,configuration,configuration_checksum,created_by) VALUES($1,$2,$3,'DRAFT',$4,$5,$6) RETURNING *`,[input.policyKey,version.rows[0].version,input.policyType,JSON.stringify(input.configuration),checksum,input.actor]);return r.rows[0];}

export async function transitionPolicy(input:{id:string;action:'APPROVE'|'CANARY'|'PAUSE'|'ROLLBACK';reason:string;idempotencyKey:string;actor:string}){if(!input.reason?.trim()||!input.idempotencyKey?.trim())throw new Error('POLICY_REASON_AND_IDEMPOTENCY_REQUIRED');const db=await getDb();const client=await db.connect();try{await client.query('BEGIN');const r=await client.query('SELECT * FROM portfolio_policies WHERE id=$1 FOR UPDATE',[input.id]);if(!r.rowCount)throw new Error('PORTFOLIO_POLICY_NOT_FOUND');const p=r.rows[0];const target=input.action==='APPROVE'?'APPROVED':input.action==='CANARY'?'CANARY':input.action==='PAUSE'?'PAUSED':'RETIRED';const allowed:Record<string,string[]>={DRAFT:['APPROVED'],APPROVED:['CANARY','PAUSED'],CANARY:['PAUSED','RETIRED'],PAUSED:['CANARY','RETIRED']};if(!allowed[p.status]?.includes(target))throw new Error('INVALID_POLICY_TRANSITION');if((target==='APPROVED'||target==='CANARY')&&p.policy_type==='CONTEXTUAL_BANDIT'){const ev=await client.query(`SELECT 1 FROM portfolio_policy_evaluations WHERE policy_id=$1 AND status='PASS'`,[p.id]);if(!ev.rowCount)throw new Error('ADAPTIVE_POLICY_EVALUATION_REQUIRED');}if(target==='CANARY')await client.query(`UPDATE portfolio_policies SET status='PAUSED' WHERE status='CANARY' AND id<>$1`,[p.id]);await client.query(`UPDATE portfolio_policies SET status=$1,approved_by=CASE WHEN $1='APPROVED' THEN $2 ELSE approved_by END,approved_at=CASE WHEN $1='APPROVED' THEN now() ELSE approved_at END WHERE id=$3`,[target,input.actor,p.id]);await client.query(`INSERT INTO portfolio_policy_transitions(policy_id,transition_key,from_status,to_status,actor,reason) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(transition_key) DO NOTHING`,[p.id,input.idempotencyKey,p.status,target,input.actor,input.reason]);await client.query('COMMIT');return {...p,status:target};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
