import test from 'node:test'; import assert from 'node:assert/strict';
import { executeProviderCall, classifyProviderError, ProviderCallError, decideGeminiCapacity, type ProviderCallEvent } from './providerResilience';

test('successful calls emit bounded, payload-free cost telemetry',async()=>{const events:ProviderCallEvent[]=[];const result=await executeProviderCall({context:{provider:'fake',operation:'read',actualCost:3,requestId:'r',runId:'run-1',jobId:'job-1',requestMetadata:{regionCode:'FR',relevanceLanguage:'fr'},attempt:2},timeoutMs:50,call:async()=>({secret:'not logged'}),emit:async e=>{events.push(e)}});assert.equal(result.secret,'not logged');assert.equal(events[0].status,'SUCCESS');assert.equal(events[0].actualCost,3);assert.equal(events[0].requestId,'r');assert.equal(events[0].runId,'run-1');assert.equal(events[0].jobId,'job-1');assert.deepEqual(events[0].requestMetadata,{regionCode:'FR',relevanceLanguage:'fr'});assert.equal(events[0].attempt,2);assert.equal(JSON.stringify(events).includes('not logged'),false)});
test('deadline aborts a fake provider and produces a retryable typed timeout',async()=>{const events:ProviderCallEvent[]=[];await assert.rejects(executeProviderCall({context:{provider:'fake',operation:'hang'},timeoutMs:10,call:signal=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')))),emit:async e=>{events.push(e)}}),(e:any)=>e instanceof ProviderCallError&&e.errorClass==='TIMEOUT'&&e.retryable);assert.equal(events[0].status,'TIMEOUT')});
test('rate-limit classification preserves provider diagnostics',()=>{const source=Object.assign(new Error('YouTube HTTP 429 RESOURCE_EXHAUSTED (RATE_LIMIT_EXCEEDED)'),{status:429,quotaExceeded:false,providerReasons:['RATE_LIMIT_EXCEEDED']});const error=classifyProviderError(source);assert.equal(error.status,429);assert.equal(error.quotaExceeded,false);assert.deepEqual(error.providerReasons,['RATE_LIMIT_EXCEEDED']);assert.equal(error.cause,source)});
test('permanent input classification preserves safe status metadata',()=>{const source=Object.assign(new Error('bad request'),{status:400,providerReasons:['INVALID_ARGUMENT']});const error=classifyProviderError(source);assert.equal(error.errorClass,'PERMANENT_INPUT');assert.equal(error.status,400);assert.deepEqual(error.providerReasons,['INVALID_ARGUMENT']);assert.equal(error.retryable,false)});
test('cancellation and retry classes are deterministic',()=>{assert.equal(classifyProviderError(Object.assign(new Error('x'),{status:429})).errorClass,'RATE_LIMIT');assert.equal(classifyProviderError(Object.assign(new Error('x'),{status:400})).retryable,false);assert.equal(classifyProviderError(Object.assign(new Error('x'),{status:503})).errorClass,'TRANSIENT')});

test('telemetry sink failure cannot convert provider success into failure',async()=>{const result=await executeProviderCall({context:{provider:'fake',operation:'read'},timeoutMs:50,call:async()=>({ok:true}),emit:async()=>{throw new Error('telemetry unavailable')}});assert.equal(result.ok,true)});

test('vocabulary is deferred during recent Gemini rate pressure',()=>{const now=1_000_000;const decision=decideGeminiCapacity('vocabulary-extraction',{nowMs:now,lastRateLimitAtMs:now-1_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'DEFER');assert.equal(decision.reasonCode,'VOCABULARY_DEFERRED_RATE_PRESSURE')});

test('vocabulary yields to recent semantic classification even without a rate limit',()=>{const now=1_000_000;const decision=decideGeminiCapacity('vocabulary-extraction',{nowMs:now,lastSemanticAtMs:now-30_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'DEFER');assert.equal(decision.reasonCode,'VOCABULARY_DEFERRED_SEMANTIC_PRIORITY')});

test('semantic calls defer long rate-pressure cooldowns instead of sleeping a worker',()=>{const now=1_000_000;const decision=decideGeminiCapacity('multilingual-semantic-classification',{nowMs:now,lastRateLimitAtMs:now-30_000,lastGeminiAtMs:now-2_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'DEFER');assert.equal(decision.reasonCode,'SEMANTIC_DEFERRED_RATE_PRESSURE');assert.equal(decision.waitMs,0)});

test('semantic calls may wait briefly for global spacing',()=>{const now=1_000_000;const decision=decideGeminiCapacity('multilingual-semantic-classification',{nowMs:now,lastGeminiAtMs:now-2_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'WAIT');assert.equal(decision.waitMs,4_000)});

test('vocabulary defers long capacity waits instead of occupying a worker',()=>{const now=1_000_000;const decision=decideGeminiCapacity('vocabulary-extraction',{nowMs:now,lastVocabularyAtMs:now-5_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'DEFER');assert.equal(decision.reasonCode,'VOCABULARY_DEFERRED_CAPACITY_WAIT')});

test('semantic calls run once cooldown and global spacing are clear',()=>{const now=1_000_000;const decision=decideGeminiCapacity('multilingual-semantic-classification',{nowMs:now,lastRateLimitAtMs:now-100_000,lastGeminiAtMs:now-10_000},{globalMinIntervalMs:6_000,semanticRateLimitCooldownMs:90_000,vocabularyRateLimitSuppressionMs:900_000,vocabularySemanticQuietMs:120_000,vocabularyMinIntervalMs:30_000,maxInlineWaitMs:8_000});assert.equal(decision.action,'RUN');assert.equal(decision.waitMs,0)});
