import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {evaluateVerifiedQueryRewards,validateQueryRewardPolicy,type QueryRewardPolicy,type VerifiedQueryExample} from './queryFeedbackEvaluation';
const policy:QueryRewardPolicy={verifiedTradingReward:1,verifiedNonTradingReward:-1,correctiveReward:0,minimumVerifiedSamples:3,confidenceZ:1.96,minimumSegmentSamples:2,explorationFloor:.2,proxyOutcomesAuthoritative:false};
const example=(key:string,outcome:VerifiedQueryExample['outcome'],country='DE'):VerifiedQueryExample=>({key,outcome,segment:{country,retrievalLane:'VIDEO',intent:'strategy',generationMode:'EXPLORATION'}});
test('delayed verified rewards exclude corrective outcomes from finalized samples',()=>{const result=evaluateVerifiedQueryRewards([example('1','TRADING_CONFIRMED'),example('2','NON_TRADING'),example('3','CORRECTIVE_UNCERTAIN')],{...policy,minimumVerifiedSamples:2});assert.equal(result.overall.sampleSize,3);assert.equal(result.overall.finalizedSampleSize,2);assert.equal(result.overall.meanReward,0);assert.ok(result.overall.confidenceInterval);});
test('reward policies are versioned, verified-only, and reject proxy authority',()=>{assert.throws(()=>validateQueryRewardPolicy({...policy,proxyOutcomesAuthoritative:true as false}),/PROXY_OUTCOMES/);const source=readFileSync('server/queryFeedbackEvaluation.ts','utf8');assert.match(source,/MAX\(version\)|ORDER BY version DESC/);assert.match(source,/query_reward_policy_versions/);});
test('sample size and segment uncertainty fail closed',()=>{const result=evaluateVerifiedQueryRewards([example('1','TRADING_CONFIRMED','DE'),example('2','TRADING_CONFIRMED','FR')],policy);assert.equal(result.status,'INSUFFICIENT_EVIDENCE');assert.ok(result.reasonCodes.includes('MINIMUM_VERIFIED_SAMPLE_NOT_MET'));assert.ok(result.reasonCodes.some(code=>code.startsWith('SEGMENT_SAMPLE_NOT_MET')));});
test('sufficient segmented feedback is offline-ready without online authority',()=>{const rows=[example('1','TRADING_CONFIRMED'),example('2','NON_TRADING'),example('3','TRADING_CONFIRMED')],result=evaluateVerifiedQueryRewards(rows,{...policy,minimumSegmentSamples:3});assert.equal(result.status,'READY_FOR_OFFLINE_INCORPORATION');assert.equal(result.onlineQueryAuthority,false);assert.equal(result.explorationFloor,.2);});
test('Phase E preserves immutable history and online query authority isolation',()=>{const migration=readFileSync('server/db/migrations/066_query_feedback_refinement.sql','utf8'),evaluation=readFileSync('server/queryFeedbackEvaluation.ts','utf8'),planner=readFileSync('server/queryIntelligence.ts','utf8');assert.match(migration,/query_runs_completed_immutable/);assert.match(migration,/query_verified_outcome_attributions[^]*CREATE TRIGGER %I_immutable/);assert.match(migration,/proxy and verified outcomes remain separate/);assert.match(evaluation,/onlineQueryAuthority:false/);assert.doesNotMatch(evaluation,/UPDATE query_library|performance_score\s*=/);assert.match(planner,/UCB1 formula/);assert.match(planner,/explorationRatio/);});
test('AI terminology remains governed input and never query authority',()=>{const planner=readFileSync('server/queryPlanner.ts','utf8'),evaluation=readFileSync('server/queryFeedbackEvaluation.ts','utf8');assert.match(planner,/provenTerminology/);assert.doesNotMatch(evaluation,/getAIClient|generateContent|fetch\s*\(/);});
