import { createHash, randomUUID } from 'node:crypto';
import { getDb } from './db';
import { checksum } from './offlineEvaluation';

export type TrialArm={armKey:string;kind:'CURATED_CONTROL'|'CANDIDATE'|'CURATED_AA';candidateKey?:string;weight:number;querySpec:Record<string,unknown>};
export type TrialPolicy={minSamples:number;rewardThreshold:number;confidenceZ:number;maxHarmRate:number;maxReviewCost:number;maxQuotaCost:number;dailyAssignmentCap:number;dailyQuotaCap:number;mode:'SHADOW'|'LIVE'};
export type RewardEvent={component:string;value:number;provisional:boolean};
export function deterministicAssignment(seed:string,actionKey:string,arms:TrialArm[]){
 if(!arms.length||arms.some(a=>!Number.isInteger(a.weight)||a.weight<=0))throw new Error('Positive integer arm weights are required.');
 const total=arms.reduce((n,a)=>n+a.weight,0);const hex=createHash('sha256').update(`${seed}\0${actionKey}`).digest('hex').slice(0,13);
 const value=parseInt(hex,16)/0x10000000000000;let cursor=value*total;let selected=arms[arms.length-1];for(const arm of arms){if(cursor<arm.weight){selected=arm;break;}cursor-=arm.weight;}
 return {arm:selected,propensity:selected.weight/total,randomizationValue:value};
}
export function analyzeRewards(events:RewardEvent[],z=1.96){
 const byAssignment=events.map(e=>e.value),n=byAssignment.length,mean=n?byAssignment.reduce((a,b)=>a+b,0)/n:0;
 const variance=n>1?byAssignment.reduce((s,x)=>s+(x-mean)**2,0)/(n-1):0,se=n?Math.sqrt(variance/n):Infinity;
 return {sampleSize:n,finalizedSampleSize:events.filter(e=>!e.provisional).length,mean,standardError:se,lowerBound:Number.isFinite(se)?mean-z*se:null,upperBound:Number.isFinite(se)?mean+z*se:null};
}
export function decideStop(metrics:{sampleSize:number;lowerBound:number|null;harmRate:number;reviewCost:number;quotaCost:number},p:TrialPolicy){
 if(metrics.harmRate>p.maxHarmRate)return {decision:'AUTO_STOP',reason:'HARM_GUARDRAIL'} as const;
 if(metrics.reviewCost>p.maxReviewCost)return {decision:'AUTO_PAUSE',reason:'REVIEW_CAPACITY_GUARDRAIL'} as const;
 if(metrics.quotaCost>p.maxQuotaCost)return {decision:'AUTO_PAUSE',reason:'QUOTA_GUARDRAIL'} as const;
 if(metrics.sampleSize<p.minSamples)return {decision:'CONTINUE',reason:'MINIMUM_SAMPLE_NOT_MET'} as const;
 return metrics.lowerBound!==null&&metrics.lowerBound>p.rewardThreshold?{decision:'GO',reason:'LOWER_BOUND_PASSES'} as const:{decision:'NO_GO',reason:'LOWER_BOUND_NOT_MET'} as const;
}
function validatePolicy(p:TrialPolicy){if(p.mode==='LIVE'&&p.dailyQuotaCap<=0)throw new Error('Live trials require a positive quota cap.');for(const [k,v] of Object.entries(p))if(k!=='mode'&&(typeof v!=='number'||!Number.isFinite(v)||v<0))throw new Error(`Invalid trial policy: ${k}.`);if(p.maxHarmRate>1)throw new Error('maxHarmRate must be at most one.');}
export async function createExperiment(input:{name:string;catalogId:string;seed:string;policy:TrialPolicy;arms:TrialArm[];strata:Array<{key:string;country:string;lane:string;ordering:string;timeBlock:string}>;actor:string}){
 validatePolicy(input.policy);if(input.arms.filter(a=>a.kind==='CURATED_CONTROL'||a.kind==='CURATED_AA').length<1)throw new Error('A curated control arm is required.');if(!input.strata.length)throw new Error('At least one stratum is required.');
 const db=await getDb(),key=checksum({name:input.name,catalogId:input.catalogId,seed:input.seed,policy:input.policy,arms:input.arms,strata:input.strata});const client=await db.connect();try{await client.query('BEGIN');
 const ex=await client.query(`INSERT INTO terminology_experiments(experiment_key,name,randomization_seed,policy,policy_checksum,catalog_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(experiment_key) DO UPDATE SET experiment_key=excluded.experiment_key RETURNING *`,[key,input.name,input.seed,JSON.stringify(input.policy),checksum(input.policy),input.catalogId,input.actor]);
 for(const a of input.arms)await client.query(`INSERT INTO terminology_experiment_arms(experiment_id,arm_key,kind,candidate_key,weight,query_spec) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,[ex.rows[0].id,a.armKey,a.kind,a.candidateKey||null,a.weight,JSON.stringify(a.querySpec)]);
 for(const s of input.strata)await client.query(`INSERT INTO terminology_experiment_strata(experiment_id,stratum_key,country,lane,ordering,time_block,daily_assignment_cap,daily_quota_cap) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING`,[ex.rows[0].id,s.key,s.country,s.lane,s.ordering,s.timeBlock,input.policy.dailyAssignmentCap,input.policy.dailyQuotaCap]);await client.query('COMMIT');return ex.rows[0];}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function transitionExperiment(input:{id:string;expectedVersion:number;action:'SHADOW'|'RUNNING'|'PAUSED'|'STOPPED';reason:string;idempotencyKey:string;actor:string}){if(!input.reason||!input.idempotencyKey)throw new Error('reason and idempotencyKey are required.');const db=await getDb(),client=await db.connect();try{await client.query('BEGIN');const existing=await client.query('SELECT * FROM terminology_stop_decisions WHERE idempotency_key=$1',[input.idempotencyKey]);if(existing.rowCount){await client.query('COMMIT');return existing.rows[0];}const controls=await client.query('SELECT * FROM terminology_trial_controls WHERE singleton=true');if(input.action==='RUNNING'&&(controls.rows[0].kill_switch||controls.rows[0].live_allocation_basis_points===0))throw new Error('LIVE_TRIALS_DISABLED');const ex=await client.query('SELECT * FROM terminology_experiments WHERE id=$1 FOR UPDATE',[input.id]);if(!ex.rowCount||ex.rows[0].version!==input.expectedVersion)throw new Error('EXPERIMENT_VERSION_CONFLICT');await client.query('UPDATE terminology_experiments SET status=$1,version=version+1,updated_at=now() WHERE id=$2',[input.action,input.id]);if(input.action==='PAUSED'||input.action==='STOPPED')await client.query(`INSERT INTO terminology_stop_decisions(id,experiment_id,idempotency_key,from_status,to_status,expected_version,reason,actor) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),input.id,input.idempotencyKey,ex.rows[0].status,input.action,input.expectedVersion,input.reason,input.actor]);await client.query('COMMIT');return {...ex.rows[0],status:input.action,version:input.expectedVersion+1};}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}
export async function inspectExperiments(limit=100){const db=await getDb(),n=Math.min(500,Math.max(1,limit));const [controls,experiments,stats,guards]=await Promise.all([db.query('SELECT * FROM terminology_trial_controls WHERE singleton=true'),db.query('SELECT * FROM terminology_experiments ORDER BY created_at DESC LIMIT $1',[n]),db.query('SELECT * FROM terminology_sufficient_statistics ORDER BY created_at DESC LIMIT $1',[n]),db.query('SELECT * FROM terminology_guardrail_events ORDER BY created_at DESC LIMIT $1',[n])]);return {controls:controls.rows[0],experiments:experiments.rows,sufficientStatistics:stats.rows,guardrails:guards.rows,causalHistoryPolicy:'RANDOMIZED_ASSIGNMENTS_ONLY'};}
