import {getDb} from './db';
import {utilityChecksum} from './utilityContract';
import type {EvidenceActionType} from './voiEvidenceController';
const VOI_CALIBRATION_POLICY_VERSION='voi-evidence-v1';

export interface ObservedActionCalibration{outcomes:number;resolutionProbability:number;averageProviderCost:number;averageLatencyMs:number;averageReviewCost:number;informationValue:number}
export async function calibrateVoiFromOutcomes(input:{windowStart:string;cutoffAt:string;actor:string;minimumOutcomes:number}){
 const start=new Date(input.windowStart),cutoff=new Date(input.cutoffAt);if(!input.actor.trim()||!Number.isInteger(input.minimumOutcomes)||input.minimumOutcomes<1||!Number.isFinite(start.getTime())||!Number.isFinite(cutoff.getTime())||start>=cutoff)throw new Error('INVALID_VOI_CALIBRATION_INPUT');
 const db=await getDb(),rows=await db.query(`SELECT d.applied_action,CASE WHEN c.activity_score>=70 THEN 'HIGH' WHEN c.activity_score>=35 THEN 'MEDIUM' ELSE 'LOW' END activity_band,COUNT(*)::int outcomes,AVG((o.resulting_status IN('TRADING_CONFIRMED','NON_TRADING'))::int)::float resolution_probability,AVG(o.provider_cost)::float average_provider_cost,AVG(o.latency_ms)::float average_latency_ms,AVG(CASE WHEN d.applied_action='HUMAN_REVIEW' THEN 1 ELSE 0 END)::float average_review_cost,AVG(CASE WHEN o.resulting_status IS NOT NULL THEN 1 ELSE 0 END)::float information_value FROM evidence_acquisition_outcomes o JOIN evidence_acquisition_decisions d ON d.id=o.decision_id LEFT JOIN channels c ON c.channel_id=d.channel_id WHERE o.completed_at>=$1 AND o.completed_at<$2 GROUP BY d.applied_action,activity_band ORDER BY d.applied_action,activity_band`,[input.windowStart,input.cutoffAt]);
 const metrics=Object.fromEntries(rows.rows.map((row:any)=>[`${row.applied_action}|${row.activity_band}`,{outcomes:Number(row.outcomes),resolutionProbability:Number(row.resolution_probability),averageProviderCost:Number(row.average_provider_cost),averageLatencyMs:Number(row.average_latency_ms),averageReviewCost:Number(row.average_review_cost),informationValue:Number(row.information_value)} satisfies ObservedActionCalibration])),outcomeCount=rows.rows.reduce((sum:any,row:any)=>sum+Number(row.outcomes),0),status=rows.rows.length&&rows.rows.every((row:any)=>Number(row.outcomes)>=input.minimumOutcomes)?'APPROVED':'INSUFFICIENT_EVIDENCE',definition={dimensions:['applied_action','activity_band'],windowStart:input.windowStart,cutoffAt:input.cutoffAt},key=utilityChecksum({definition,metrics,minimumOutcomes:input.minimumOutcomes,policyVersion:VOI_CALIBRATION_POLICY_VERSION});
 const saved=await db.query(`INSERT INTO voi_calibration_runs(calibration_key,cutoff_at,window_start,segment_definition,action_metrics,minimum_outcomes,outcome_count,status,policy_version,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(calibration_key) DO NOTHING RETURNING *`,[key,input.cutoffAt,input.windowStart,JSON.stringify(definition),JSON.stringify(metrics),input.minimumOutcomes,outcomeCount,status,VOI_CALIBRATION_POLICY_VERSION,input.actor]);return saved.rows[0]||(await db.query('SELECT * FROM voi_calibration_runs WHERE calibration_key=$1',[key])).rows[0];
}

export async function loadObservedActionCalibration(action:EvidenceActionType,activityBand:string):Promise<ObservedActionCalibration|undefined>{const db=await getDb(),row=await db.query(`SELECT action_metrics->$1 metric FROM voi_calibration_runs WHERE status='APPROVED' AND action_metrics ? $1 ORDER BY cutoff_at DESC,id DESC LIMIT 1`,[`${action}|${activityBand}`]);return row.rows[0]?.metric;}
