import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { assessUtility } from './utilityContract';
import { assignVoiCanary, deriveEvidenceGaps, planEvidenceAction } from './voiEvidenceController';

const decision=(overrides:any={})=>({status:'UNCERTAIN',confidenceScore:50,positiveEvidence:[],negativeEvidence:[],totalPositiveWeight:0,totalNegativeWeight:0,evidenceCollection:{sufficiency:'INSUFFICIENT',sparseMetadata:true,degraded:false,fieldsPresent:['channel_title'],reasonCodes:[],providers:[]},stagedClassification:{pipelineVersion:'test',lifecycleAction:'ENRICH',stages:[{stage:'AVAILABILITY',disposition:'ABSTAIN',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}},{stage:'CANDIDATE_DETECTION',disposition:'ABSTAIN',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}},{stage:'CORROBORATION',disposition:'ABSTAIN',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}}]},...overrides}) as any;
test('shared hard constraints dominate utility and cannot be traded for recall',()=>{const vector={decisionResolution:1,confirmationRecall:1,precisionProtection:1,coverageGain:1,informationGain:1,providerCost:1,reviewCost:0,latencyMs:1,operationalRisk:0},weights={decisionResolution:1,confirmationRecall:1,precisionProtection:1,coverageGain:1,informationGain:1,providerCost:0,reviewCost:0,latencyMs:0,operationalRisk:0},result=assessUtility(vector,weights,{countryAllowed:true,terminalPrecisionProtected:false,providerQuotaRemaining:100,caseQuotaRemaining:100,latencyRemainingMs:100,reviewCapacityRemaining:1,governedAction:true,prerequisitesSatisfied:true},{providerCost:1,reviewCost:0,latencyMs:1});assert.equal(result.feasible,false);assert.equal(result.score,null);assert.deepEqual(result.violations,['TERMINAL_PRECISION']);});
test('missing sparse evidence selects bounded metadata before expensive review',()=>{const plan=planEvidenceAction({decision:decision(),rawInput:{channel_name:'Sparse',description:'',enrichment_stage:0},mode:'CANARY',providerQuotaRemaining:1000});assert.ok(plan.gaps.includes('METADATA_SPARSE'));assert.equal(plan.selectedAction,'CHANNEL_RECENT_METADATA');assert.equal(plan.appliedAction,'CHANNEL_RECENT_METADATA');});
test('corroboration gap after metadata selects playlist evidence and never repeats stage one',()=>{const d=decision({evidenceCollection:{sufficiency:'SUFFICIENT',sparseMetadata:false,degraded:false,fieldsPresent:['channel_bio','video_title'],reasonCodes:[],providers:[]},stagedClassification:{pipelineVersion:'test',lifecycleAction:'ENRICH',stages:[{stage:'AVAILABILITY',disposition:'PASS',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}},{stage:'CANDIDATE_DETECTION',disposition:'PASS',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}},{stage:'CORROBORATION',disposition:'ABSTAIN',reasonCodes:[],evidenceIds:[],fields:[],metrics:{}}]}}),plan=planEvidenceAction({decision:d,rawInput:{channel_name:'Candidate',description:'rich',enrichment_stage:1},mode:'CANARY',providerQuotaRemaining:1000});assert.deepEqual(deriveEvidenceGaps(d),['CORROBORATION_MISSING']);assert.equal(plan.selectedAction,'VIDEO_PLAYLIST_CORROBORATION');assert.ok(plan.assessments.CHANNEL_RECENT_METADATA.violations.includes('PREREQUISITE'));});
test('shadow mode records the counterfactual but preserves legacy action',()=>{const plan=planEvidenceAction({decision:decision(),rawInput:{channel_name:'Sparse',description:'',enrichment_stage:0},mode:'SHADOW',providerQuotaRemaining:1000});assert.equal(plan.selectedAction,'CHANNEL_RECENT_METADATA');assert.equal(plan.appliedAction,plan.legacyAction);assert.ok(plan.reasonCodes.includes('LEGACY_ACTION_PRESERVED'));});
test('canary assignment is deterministic, bounded, and defaults to control',()=>{assert.deepEqual(assignVoiCanary('case:one',1000),assignVoiCanary('case:one',1000));assert.equal(assignVoiCanary('case:one',0).controllerAssigned,false);assert.equal(assignVoiCanary('case:one',10000).controllerAssigned,true);assert.throws(()=>assignVoiCanary('case:one',10001),/basis points/);});
test('quota and completed stages fail closed to review',()=>{const plan=planEvidenceAction({decision:decision(),rawInput:{channel_name:'Spent',description:'',enrichment_stage:2},mode:'CANARY',providerQuotaRemaining:0});assert.equal(plan.selectedAction,'HUMAN_REVIEW');assert.equal(plan.appliedAction,'HUMAN_REVIEW');assert.ok(plan.assessments.VIDEO_PLAYLIST_CORROBORATION.violations.includes('PROVIDER_QUOTA'));});
test('a hard policy violation cannot fall through to an infeasible action',()=>assert.throws(()=>planEvidenceAction({decision:decision(),rawInput:{channel_name:'Blocked',description:'',enrichment_stage:0},mode:'CANARY',providerQuotaRemaining:1000,countryAllowed:false}),/NO_FEASIBLE_EVIDENCE_ACTION/));
test('migration and integration remain immutable, off by default, and action bounded',()=>{const migration=readFileSync(new URL('./db/migrations/038_voi_evidence_controller.sql',import.meta.url),'utf8'),controller=readFileSync(new URL('./voiEvidenceController.ts',import.meta.url),'utf8');assert.match(migration,/voi_evidence_controller_mode','OFF'/);assert.match(migration,/voi_evidence_canary_basis_points','0'/);assert.match(migration,/reject_immutable_event_mutation/);for(const action of ['CHANNEL_RECENT_METADATA','VIDEO_PLAYLIST_CORROBORATION','HUMAN_REVIEW'])assert.match(migration,new RegExp(action));assert.match(controller,/plan\.appliedAction=controllerAssigned\?plan\.selectedAction:input\.legacyAction/);assert.doesNotMatch(controller,/selectedAction.*trading_status/);});
