import { getAppSetting, getDb } from './db';
import type { RawChannelInput, StagedClassificationReport, VerificationDecision } from './evidenceEngine';
import { assessUtility, utilityChecksum, type ConstraintContext, type UtilityAssessment, type UtilityVector, type UtilityWeights } from './utilityContract';
import {assignRelease5Serving} from './release5/rollout';
import {loadObservedActionCalibration,type ObservedActionCalibration} from './voiCalibration';

export const VOI_POLICY_VERSION='voi-evidence-v2';
export type EvidenceActionType='CHANNEL_RECENT_METADATA'|'VIDEO_PLAYLIST_CORROBORATION'|'PROVIDER_RETRY'|'HUMAN_REVIEW';
export type EvidenceGap='METADATA_MISSING'|'METADATA_SPARSE'|'PROVIDER_DEGRADED'|'SEMANTIC_CANDIDATE_MISSING'|'CORROBORATION_MISSING'|'UNSUPPORTED_LANGUAGE'|'DECISION_AMBIGUOUS';
export interface EvidenceActionDefinition {action:EvidenceActionType;enrichmentStage:null|1|2|3;providerCost:number;reviewCost:number;latencyMs:number;resolves:EvidenceGap[];governed:boolean}
export interface VoiPolicy {policyVersion:string;weights:UtilityWeights;caseQuotaCap:number;latencyDeadlineMs:number;reviewCapacity:number;minimumActionScore:number;resolutionEstimates:Record<EvidenceActionType,number>}
export interface EvidenceActionPlan {gaps:EvidenceGap[];selectedAction:EvidenceActionType;legacyAction:EvidenceActionType;appliedAction:EvidenceActionType;assessments:Record<EvidenceActionType,UtilityAssessment>;mode:'OFF'|'SHADOW'|'CANARY';reasonCodes:string[];policyVersion:string;checksum:string;decisionId?:string;assignmentBasisPoints?:number;randomizationValue?:number;controllerAssigned?:boolean}
export interface VitalityScheduling{activityBand:'HIGH'|'MEDIUM'|'LOW';recheckCadenceDays:number;jobPriorityDelta:number;evidenceUrgencyMultiplier:number;reviewPriorityDelta:number}

export const ACTIONS:EvidenceActionDefinition[]=[
  {action:'CHANNEL_RECENT_METADATA',enrichmentStage:1,providerCost:101,reviewCost:0,latencyMs:2500,resolves:['METADATA_MISSING','METADATA_SPARSE','PROVIDER_DEGRADED','SEMANTIC_CANDIDATE_MISSING'],governed:true},
  {action:'VIDEO_PLAYLIST_CORROBORATION',enrichmentStage:2,providerCost:202,reviewCost:0,latencyMs:5000,resolves:['CORROBORATION_MISSING','SEMANTIC_CANDIDATE_MISSING','UNSUPPORTED_LANGUAGE','DECISION_AMBIGUOUS'],governed:true},
  // Stage 3 is intentionally a single bounded replay of the richest creator
  // evidence bundle. It exists only to distinguish an operational provider
  // failure from genuine evidentiary ambiguity before asking a human to review.
  {action:'PROVIDER_RETRY',enrichmentStage:3,providerCost:202,reviewCost:0,latencyMs:5000,resolves:['PROVIDER_DEGRADED'],governed:true},
  {action:'HUMAN_REVIEW',enrichmentStage:null,providerCost:0,reviewCost:1,latencyMs:0,resolves:['METADATA_MISSING','METADATA_SPARSE','PROVIDER_DEGRADED','SEMANTIC_CANDIDATE_MISSING','CORROBORATION_MISSING','UNSUPPORTED_LANGUAGE','DECISION_AMBIGUOUS'],governed:true}
];
export const DEFAULT_VOI_POLICY:VoiPolicy={policyVersion:VOI_POLICY_VERSION,weights:{decisionResolution:10,confirmationRecall:8,precisionProtection:12,coverageGain:2,informationGain:5,providerCost:.025,reviewCost:25,latencyMs:.0002,operationalRisk:4},caseQuotaCap:505,latencyDeadlineMs:15000,reviewCapacity:1,minimumActionScore:0,resolutionEstimates:{CHANNEL_RECENT_METADATA:.35,VIDEO_PLAYLIST_CORROBORATION:.55,PROVIDER_RETRY:.5,HUMAN_REVIEW:.9}};
export function deriveVitalityScheduling(activity?:RawChannelInput['activity_metadata'],asOf?:string):VitalityScheduling{const score=Math.min(100,Math.max(0,Number(activity?.activity_score??50))),latest=activity?.latest_upload_at?Date.parse(activity.latest_upload_at):NaN,reference=Date.parse(asOf||activity?.observed_at||activity?.latest_upload_at||'1970-01-01T00:00:00Z'),days=Number.isFinite(latest)&&Number.isFinite(reference)?Math.max(0,(reference-latest)/86400000):Infinity,activityBand:VitalityScheduling['activityBand']=score>=70&&days<=90?'HIGH':score>=35&&days<=365?'MEDIUM':'LOW';return activityBand==='HIGH'?{activityBand,recheckCadenceDays:14,jobPriorityDelta:10,evidenceUrgencyMultiplier:1.2,reviewPriorityDelta:10}:activityBand==='MEDIUM'?{activityBand,recheckCadenceDays:30,jobPriorityDelta:5,evidenceUrgencyMultiplier:1,reviewPriorityDelta:5}:{activityBand,recheckCadenceDays:90,jobPriorityDelta:0,evidenceUrgencyMultiplier:.75,reviewPriorityDelta:0};}

const stage=(report:StagedClassificationReport|undefined,name:string)=>report?.stages.find(item=>item.stage===name);
export function assignVoiCanary(subjectKey:string,basisPoints:number){if(!subjectKey.trim()||!Number.isInteger(basisPoints)||basisPoints<0||basisPoints>10000)throw new Error('Valid canary subject and basis points are required.');const randomizationValue=parseInt(utilityChecksum(subjectKey).slice(0,8),16)%10000;return {assignmentBasisPoints:basisPoints,randomizationValue,controllerAssigned:randomizationValue<basisPoints};}
export function deriveEvidenceGaps(decision:VerificationDecision):EvidenceGap[]{const gaps=new Set<EvidenceGap>(),collection=decision.evidenceCollection;if(collection.sufficiency==='MISSING')gaps.add('METADATA_MISSING');if(collection.sufficiency==='INSUFFICIENT'||collection.sparseMetadata)gaps.add('METADATA_SPARSE');if(collection.degraded)gaps.add('PROVIDER_DEGRADED');if(stage(decision.stagedClassification,'CANDIDATE_DETECTION')?.disposition!=='PASS')gaps.add('SEMANTIC_CANDIDATE_MISSING');if(stage(decision.stagedClassification,'CORROBORATION')?.disposition!=='PASS')gaps.add('CORROBORATION_MISSING');if(collection.providers.some(provider=>provider.outcome==='ABSTAINED_UNSUPPORTED_LANGUAGE'))gaps.add('UNSUPPORTED_LANGUAGE');if(!gaps.size)gaps.add('DECISION_AMBIGUOUS');return [...gaps].sort();}
function actionVector(action:EvidenceActionDefinition,gaps:EvidenceGap[],policy:VoiPolicy,calibration:ObservedActionCalibration|undefined,vitality:VitalityScheduling):UtilityVector{const overlap=action.resolves.filter(gap=>gaps.includes(gap)).length,resolution=(calibration?.resolutionProbability??policy.resolutionEstimates[action.action])*Math.min(1,overlap/Math.max(1,gaps.length));return {decisionResolution:resolution,confirmationRecall:action.action==='HUMAN_REVIEW'?.4:resolution,precisionProtection:action.action==='HUMAN_REVIEW'?1:.8,coverageGain:0,informationGain:(calibration?.informationValue??overlap/Math.max(1,gaps.length))*vitality.evidenceUrgencyMultiplier,providerCost:calibration?.averageProviderCost??action.providerCost,reviewCost:calibration?.averageReviewCost??action.reviewCost,latencyMs:calibration?.averageLatencyMs??action.latencyMs,operationalRisk:action.action==='VIDEO_PLAYLIST_CORROBORATION'||action.action==='PROVIDER_RETRY'?.15:.05};}
export function planEvidenceAction(input:{decision:VerificationDecision;rawInput:RawChannelInput;mode:'OFF'|'SHADOW'|'CANARY';policy?:VoiPolicy;providerQuotaRemaining:number;countryAllowed?:boolean;calibration?:Partial<Record<EvidenceActionType,ObservedActionCalibration>>}):EvidenceActionPlan{
  const policy=input.policy||DEFAULT_VOI_POLICY,gaps=deriveEvidenceGaps(input.decision),currentStage=Math.max(0,input.rawInput.enrichment_stage||0),legacyAction:EvidenceActionType=currentStage===2&&input.decision.evidenceCollection.degraded?'PROVIDER_RETRY':currentStage>=2?'HUMAN_REVIEW':currentStage===1?'VIDEO_PLAYLIST_CORROBORATION':'CHANNEL_RECENT_METADATA',assessments={} as Record<EvidenceActionType,UtilityAssessment>;
  const vitality=deriveVitalityScheduling(input.rawInput.activity_metadata,input.decision.timestamp);for(const action of ACTIONS){const calibrated=input.calibration?.[action.action],costs={providerCost:calibrated?.averageProviderCost??action.providerCost,reviewCost:calibrated?.averageReviewCost??action.reviewCost,latencyMs:calibrated?.averageLatencyMs??action.latencyMs},constraints:ConstraintContext={countryAllowed:input.countryAllowed!==false,terminalPrecisionProtected:true,providerQuotaRemaining:input.providerQuotaRemaining,caseQuotaRemaining:Math.max(0,policy.caseQuotaCap-(currentStage>=3?505:currentStage>=2?303:currentStage===1?101:0)),latencyRemainingMs:policy.latencyDeadlineMs,reviewCapacityRemaining:policy.reviewCapacity,governedAction:action.governed,prerequisitesSatisfied:action.resolves.some(gap=>gaps.includes(gap))&&(action.enrichmentStage===null||action.enrichmentStage>currentStage)};assessments[action.action]=assessUtility(actionVector(action,gaps,policy,calibrated,vitality),policy.weights,constraints,costs);}
  const feasible=ACTIONS.filter(action=>assessments[action.action].feasible&&assessments[action.action].score!>=policy.minimumActionScore).sort((a,b)=>assessments[b.action].score!-assessments[a.action].score!||a.action.localeCompare(b.action));if(!feasible.length)throw new Error('NO_FEASIBLE_EVIDENCE_ACTION');const selectedAction=feasible[0].action,appliedAction=input.mode==='CANARY'?selectedAction:legacyAction,reasonCodes=[`SELECTED_${selectedAction}`,input.mode==='CANARY'?'VOI_ACTION_APPLIED':'LEGACY_ACTION_PRESERVED'];const unsigned={gaps,selectedAction,legacyAction,appliedAction,assessments,mode:input.mode,reasonCodes,policyVersion:policy.policyVersion};return {...unsigned,checksum:utilityChecksum(unsigned)};
}

export async function planAndRecordEvidenceAction(input:{channelId:string;diagnosticId?:string;decision:VerificationDecision;rawInput:RawChannelInput;legacyAction:EvidenceActionType;providerQuotaRemaining:number}):Promise<EvidenceActionPlan>{
 const configured=String(await getAppSetting('voi_evidence_controller_mode','OFF')).toUpperCase(),[rollout,workflowAssignment]=await Promise.all([assignRelease5Serving('VOI_EVIDENCE_ACTIONS',input.channelId),assignRelease5Serving('INVESTIGATION_WORKFLOW',input.channelId)]),mode:'OFF'|'SHADOW'|'CANARY'=rollout.mode==='CANARY'?'CANARY':configured==='SHADOW'?'SHADOW':'OFF',vitality=deriveVitalityScheduling(input.rawInput.activity_metadata,input.decision.timestamp),calibration=(mode==='OFF'?{}:Object.fromEntries(await Promise.all(ACTIONS.map(async action=>[action.action,await loadObservedActionCalibration(action.action,vitality.activityBand)])))) as Partial<Record<EvidenceActionType,ObservedActionCalibration>>,plan=planEvidenceAction({decision:input.decision,rawInput:input.rawInput,mode,providerQuotaRemaining:input.providerQuotaRemaining,calibration});
 // Operational degradation at the fully enriched stage gets exactly one bounded
 // automated retry even when the VOI controller is OFF/SHADOW. This is a safety
 // correction: a provider outage must not be converted into human ambiguity.
 const currentStage=Math.max(0,input.rawInput.enrichment_stage||0),effectiveLegacyAction:EvidenceActionType=currentStage===2&&input.decision.evidenceCollection.degraded?'PROVIDER_RETRY':input.legacyAction;
 plan.legacyAction=effectiveLegacyAction;const legacyAssignment=assignVoiCanary(`${input.channelId}|${input.diagnosticId||input.decision.timestamp}|${plan.policyVersion}`,0),acquisitionAction=plan.selectedAction!=='HUMAN_REVIEW',controllerAssigned=mode==='CANARY'&&!!rollout.assigned&&!!workflowAssignment.assigned&&acquisitionAction;plan.assignmentBasisPoints=rollout.assignmentBasisPoints??legacyAssignment.assignmentBasisPoints;plan.randomizationValue=rollout.randomizationValue??legacyAssignment.randomizationValue;plan.controllerAssigned=controllerAssigned;plan.appliedAction=controllerAssigned?plan.selectedAction:effectiveLegacyAction;plan.reasonCodes=[...plan.reasonCodes.filter(code=>code!=='VOI_ACTION_APPLIED'&&code!=='LEGACY_ACTION_PRESERVED'),currentStage===2&&input.decision.evidenceCollection.degraded?'DEGRADED_PROVIDER_BOUNDED_RETRY':mode==='CANARY'?(controllerAssigned?'CANARY_CONTROLLER_ASSIGNED':!acquisitionAction?'VOI_ACQUISITION_ACTION_REQUIRED':rollout.assigned?'INVESTIGATION_CANARY_REQUIRED':'CANARY_CONTROL_ASSIGNED'):'LEGACY_ACTION_PRESERVED',`VITALITY_${vitality.activityBand}`,`RECHECK_CADENCE_${vitality.recheckCadenceDays}_DAYS`];plan.checksum=utilityChecksum({...plan,checksum:undefined,decisionId:undefined});if(mode==='OFF')return plan;
 const db=await getDb(),key=utilityChecksum({channelId:input.channelId,diagnosticId:input.diagnosticId||input.decision.timestamp,policyVersion:plan.policyVersion,mode,activationId:rollout.activationId||null}),saved=await db.query(`INSERT INTO evidence_acquisition_decisions(decision_key,channel_id,classification_diagnostic_id,mode,policy_version,utility_contract_version,gaps,eligible_actions,selected_action,legacy_action,applied_action,assignment_basis_points,randomization_value,controller_assigned,reason_codes,decision_checksum) VALUES($1,$2,$3,$4,$5,'utility-constraints-v1',$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) ON CONFLICT(decision_key) DO NOTHING RETURNING id`,[key,input.channelId,input.diagnosticId||null,mode,plan.policyVersion,JSON.stringify(plan.gaps),JSON.stringify(plan.assessments),plan.selectedAction,plan.legacyAction,plan.appliedAction,plan.assignmentBasisPoints,plan.randomizationValue,controllerAssigned,JSON.stringify(plan.reasonCodes),plan.checksum]);const row=saved.rowCount?saved:await db.query('SELECT id FROM evidence_acquisition_decisions WHERE decision_key=$1',[key]);return {...plan,decisionId:row.rows[0].id};
}
export async function recordEvidenceActionOutcome(input:{decisionId:string;jobId:string;attempt:number;status:'SUCCEEDED'|'FAILED'|'SKIPPED';resultingStatus?:string;providerCost:number;latencyMs:number;reasonCode:string}){const db=await getDb(),key=utilityChecksum(input);await db.query(`INSERT INTO evidence_acquisition_outcomes(outcome_key,decision_id,job_id,attempt,status,resulting_status,provider_cost,latency_ms,reason_code) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(outcome_key) DO NOTHING`,[key,input.decisionId,input.jobId,input.attempt,input.status,input.resultingStatus||null,input.providerCost,input.latencyMs,input.reasonCode]);}
export async function inspectVoiEvidenceController(limit=100){const db=await getDb(),n=Math.min(500,Math.max(1,Math.trunc(limit))),[settings,decisions,outcomes,metrics]=await Promise.all([getAppSetting('voi_evidence_controller_mode','OFF'),db.query('SELECT * FROM evidence_acquisition_decisions ORDER BY decided_at DESC LIMIT $1',[n]),db.query('SELECT * FROM evidence_acquisition_outcomes ORDER BY completed_at DESC LIMIT $1',[n]),db.query(`SELECT d.applied_action,COUNT(o.id)::int outcomes,COUNT(o.id) FILTER(WHERE o.status='SUCCEEDED')::int succeeded,COUNT(o.id) FILTER(WHERE o.status='FAILED')::int failed,COUNT(o.id) FILTER(WHERE o.resulting_status IN('TRADING_CONFIRMED','NON_TRADING'))::int resolved,AVG(o.provider_cost)::float average_provider_cost,AVG(o.latency_ms)::float average_latency_ms FROM evidence_acquisition_decisions d LEFT JOIN evidence_acquisition_outcomes o ON o.decision_id=d.id GROUP BY d.applied_action ORDER BY d.applied_action`)]);return {policyVersion:VOI_POLICY_VERSION,mode:settings,automaticTerminalDecisions:false,registeredActions:ACTIONS,actionMetrics:metrics.rows,decisions:decisions.rows,outcomes:outcomes.rows};}
