from pathlib import Path

p=Path('server/db.ts')
text=p.read_text()
anchor="""let pool: InstanceType<typeof Pool> | null = null;\nlet initPromise: Promise<InstanceType<typeof Pool>> | null = null;\n"""
insert="""let pool: InstanceType<typeof Pool> | null = null;\nlet initPromise: Promise<InstanceType<typeof Pool>> | null = null;\n\nconst TRANSIENT_PG_STARTUP_CODES = new Set(['57P03','57P01','53300','08000','08001','08003','08006']);\nconst TRANSIENT_PG_NETWORK_CODES = new Set(['ECONNREFUSED','ECONNRESET','ETIMEDOUT','EAI_AGAIN','ENETUNREACH','EHOSTUNREACH']);\n\nfunction isTransientPostgresStartupError(error: any): boolean {\n  const code = String(error?.code || '');\n  if (TRANSIENT_PG_STARTUP_CODES.has(code) || TRANSIENT_PG_NETWORK_CODES.has(code)) return true;\n  const message = String(error?.message || error || '').toLowerCase();\n  return message.includes('database system is starting up') ||\n    message.includes('consistent recovery state has not been yet reached') ||\n    message.includes('cannot connect now') ||\n    message.includes('the database system is in recovery mode');\n}\n\nfunction sleep(ms: number): Promise<void> { return new Promise(resolve => setTimeout(resolve, ms)); }\n\nasync function waitForPostgresReady(db: InstanceType<typeof Pool>): Promise<void> {\n  const maxWaitMs = Math.max(30_000, Number(process.env.POSTGRES_STARTUP_MAX_WAIT_MS || '300000'));\n  const started = Date.now();\n  let attempt = 0;\n  while (true) {\n    attempt++;\n    try {\n      await db.query('SELECT 1');\n      if (attempt > 1) console.log(`[PostgreSQL] Ready after ${attempt} startup checks.`);\n      return;\n    } catch (error: any) {\n      if (!isTransientPostgresStartupError(error)) throw error;\n      const elapsed = Date.now() - started;\n      if (elapsed >= maxWaitMs) {\n        console.error(`[PostgreSQL] Still unavailable after ${elapsed}ms; giving up startup retry.`, { code: error?.code, message: error?.message });\n        throw error;\n      }\n      const delayMs = Math.min(10_000, 1_000 * Math.pow(2, Math.min(attempt - 1, 3)));\n      console.warn(`[PostgreSQL] Database temporarily unavailable during startup (code=${error?.code || 'unknown'}). Retrying in ${delayMs}ms.`);\n      await sleep(delayMs);\n    }\n  }\n}\n"""
if anchor not in text: raise SystemExit('anchor missing')
text=text.replace(anchor,insert,1)
old="""      await pool.query('SELECT 1');\n      await runMigrations();\n"""
new="""      await waitForPostgresReady(pool);\n      await runMigrations();\n"""
if old not in text: raise SystemExit('startup query anchor missing')
text=text.replace(old,new,1)
p.write_text(text)
