import fs from 'node:fs/promises';
import { performance } from 'node:perf_hooks';
import type { RawChannelInput } from '../server/evidenceEngine/types.js';
import { documentRef } from '../server/evidenceEngine/canonicalEvidencePlane.js';

type GroundTruth = 'TRADING_CONFIRMED' | 'NON_TRADING' | 'UNCERTAIN';
type Case = { id:string; input:RawChannelInput; ground_truth:GroundTruth; gemini?:{label?:string;confidence?:number;status?:GroundTruth;model?:string} };
type Result = { id:string;provider:'groq';model:string;latency_ms:number;http_status?:number;ok:boolean;schema_valid:boolean;label?:string;confidence?:number;status?:GroundTruth;error?:string };
const MODEL=process.env.GROQ_BENCHMARK_MODEL||'openai/gpt-oss-120b';
const CASES=process.env.SEMANTIC_BENCHMARK_CASES||'benchmark/semantic-cases.jsonl';
const OUT=process.env.SEMANTIC_BENCHMARK_OUT||'benchmark/results/groq-semantic.json';
const TAXONOMY=['ACTIVE_TRADING','INVESTING_EDUCATION','FINANCIAL_NEWS','PERSONAL_FINANCE','HYPE','UNRELATED','AMBIGUOUS'];
const PROMPT_VERSION='priority2-multilingual-structured-1';
function fieldDocuments(input:RawChannelInput){
 if(input.evidence_corpus?.length)return input.evidence_corpus.filter(d=>!['activity_metadata','search_match_context','country','language'].includes(d.field)).slice(0,40).map(d=>({ref:documentRef(d),text:d.text}));
 return [{ref:{field:'channel_title'},text:input.channel_name},{ref:{field:'channel_bio'},text:input.description},...(input.videos||(input.video_titles||[]).map((title,index)=>({title,description:input.video_descriptions?.[index]}))).slice(0,12).flatMap((video,index)=>[{ref:{field:'video_title',index},text:video.title},{ref:{field:'video_description',index},text:video.description||''}]),...(input.playlists||[]).slice(0,6).flatMap((p,index)=>[{ref:{field:'playlist_name',index},text:p.name},{ref:{field:'playlist_description',index},text:p.description||''}]),...(input.transcript_excerpts||[]).slice(0,4).map((e,index)=>({ref:{field:'transcript_excerpt',index},text:e.text}))].filter(d=>d.text?.trim()).map(d=>({...d,text:d.text.slice(0,1200)}));
}
function buildPrompt(input:RawChannelInput){return JSON.stringify({task:'CANDIDATE',promptVersion:PROMPT_VERSION,closedTaxonomy:TAXONOMY,instructions:['Infer meaning across languages, scripts, transliteration, loanwords, and code-switching.','Classify creator focus, not isolated keywords. Cite only supplied field references.','Set supportedLanguage=false and label=AMBIGUOUS when meaning cannot be reliably interpreted.','Distinguish active trading, investing education, financial news, personal finance, hype, and unrelated content.','Return JSON with label, confidence 0..100, supportedLanguage, reasonCodes, explanation, concepts, languages, citations.'],declaredCountry:input.country||null,declaredLanguageHints:input.detected_languages||[],documents:fieldDocuments(input)});}
function normalize(raw:any){const label=TAXONOMY.includes(raw?.label)?raw.label:'AMBIGUOUS';const confidence=Math.max(0,Math.min(100,Number(raw?.confidence)||0));const schemaValid=typeof raw?.label==='string'&&TAXONOMY.includes(raw.label)&&typeof raw?.confidence==='number'&&typeof raw?.supportedLanguage==='boolean'&&Array.isArray(raw?.reasonCodes)&&typeof raw?.explanation==='string'&&Array.isArray(raw?.concepts)&&Array.isArray(raw?.languages)&&Array.isArray(raw?.citations);return{label,confidence,schemaValid};}
function toStatus(label:string):GroundTruth{if(label==='ACTIVE_TRADING'||label==='INVESTING_EDUCATION')return'TRADING_CONFIRMED';if(label==='UNRELATED'||label==='HYPE'||label==='FINANCIAL_NEWS'||label==='PERSONAL_FINANCE')return'NON_TRADING';return'UNCERTAIN';}
async function callGroq(prompt:string){const key=process.env.GROQ_API_KEY;if(!key)throw new Error('GROQ_API_KEY is not configured.');const started=performance.now();const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,messages:[{role:'user',content:`${prompt}\nReturn JSON only. Do not include markdown.`}],temperature:0,reasoning_effort:'medium',include_reasoning:false,response_format:{type:'json_schema',json_schema:{name:'semantic_classification',strict:true,schema:{type:'object',additionalProperties:false,properties:{label:{type:'string',enum:TAXONOMY},confidence:{type:'number',minimum:0,maximum:100},supportedLanguage:{type:'boolean'},reasonCodes:{type:'array',items:{type:'string'}},explanation:{type:'string'},concepts:{type:'array',items:{type:'string'}},languages:{type:'array',items:{type:'object',additionalProperties:false,properties:{language:{type:'string'},script:{type:'string'},confidence:{type:'number',minimum:0,maximum:100},field:{type:'string'}},required:['language','script','confidence','field']}},citations:{type:'array',items:{type:'object',additionalProperties:false,properties:{field:{type:'string'},index:{type:['integer','null']},sourceId:{type:['string','null']}},required:['field','index','sourceId']}}},required:['label','confidence','supportedLanguage','reasonCodes','explanation','concepts','languages','citations']}}}})});const latency=Math.round(performance.now()-started);const text=await response.text();if(!response.ok)throw Object.assign(new Error(`Groq HTTP ${response.status}: ${text.slice(0,500)}`),{status:response.status,latency});const content=JSON.parse(text)?.choices?.[0]?.message?.content;if(typeof content!=='string')throw Object.assign(new Error('Groq returned no message content.'),{status:response.status,latency});return{raw:JSON.parse(content),latency};}
async function main(){const cases:Case[]=(await fs.readFile(CASES,'utf8')).split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(x=>JSON.parse(x));if(!cases.length)throw new Error(`No benchmark cases found in ${CASES}`);const results:Result[]=[];for(const item of cases){try{const{raw,latency}=await callGroq(buildPrompt(item.input));const n=normalize(raw);results.push({id:item.id,provider:'groq',model:MODEL,latency_ms:latency,ok:true,schema_valid:n.schemaValid,label:n.label,confidence:n.confidence,status:toStatus(n.label)});}catch(error:any){results.push({id:item.id,provider:'groq',model:MODEL,latency_ms:Number(error?.latency||0),http_status:error?.status,ok:false,schema_valid:false,error:String(error?.message||error)});}}
 const valid=results.filter(r=>r.ok&&r.schema_valid&&r.status);const pairs=cases.map(c=>({truth:c.ground_truth,result:results.find(r=>r.id===c.id)})).filter(x=>x.result?.ok&&x.result?.schema_valid);const tp=pairs.filter(x=>x.truth==='TRADING_CONFIRMED'&&x.result?.status==='TRADING_CONFIRMED').length;const fp=pairs.filter(x=>x.truth!=='TRADING_CONFIRMED'&&x.result?.status==='TRADING_CONFIRMED').length;const fn=pairs.filter(x=>x.truth==='TRADING_CONFIRMED'&&x.result?.status!=='TRADING_CONFIRMED').length;const tn=pairs.filter(x=>x.truth!=='TRADING_CONFIRMED'&&x.result?.status!=='TRADING_CONFIRMED').length;const precision=tp+fp?tp/(tp+fp):0,recall=tp+fn?tp/(tp+fn):0,f1=precision+recall?2*precision*recall/(precision+recall):0;const latencies=valid.map(r=>r.latency_ms).sort((a,b)=>a-b);const pct=(p:number)=>latencies.length?latencies[Math.min(latencies.length-1,Math.floor((latencies.length-1)*p))]:null;const report={generated_at:new Date().toISOString(),model:MODEL,prompt_version:PROMPT_VERSION,cases:cases.length,completed:valid.length,failures:results.length-valid.length,schema_valid_rate:results.length?valid.length/results.length:0,confusion:{tp,tn,fp,fn},precision,recall,f1,latency_ms:{p50:pct(.5),p95:pct(.95),mean:latencies.length?latencies.reduce((a,b)=>a+b,0)/latencies.length:null},results};await fs.mkdir(OUT.split('/').slice(0,-1).join('/')||'.',{recursive:true});await fs.writeFile(OUT,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
main().catch(error=>{console.error(error);process.exit(1);});